openSUSE/openSUSE-release-tools

metrics/grafana/openqa.json
Since data is collected at the same interval it avoids grouping at smaller
intervals when zoomed in which reveals gaps between the data points.
@coolo Resolves the small issue noted in #1731.
Goes from:
to:
like magic.
I have used this in other dashboards, just had to remember.
=> metrics/grafana/openqa: set minimum interval of 10s to avoid gaps.

osc-staging.py, osclib/select_command.py
- 41dc359580d3def3dcac84d2499a028ae62d8e9e:
osc-staging: select: document --move and --filter-from options.
- ef9ff661bb7b08f1a5743a174cc33e53e2619d0a:
osc-staging: select: replace --from with --filter-from.
--from no longer serves a purpose since requests should never live in
more than one staging (apparent from linking).
Since no one indicated a reason for `--from` in the issue. @Vogtinator please verify this works as you expect and does not break other workflows as you are doing more staging than I at the moment.
Fixes #1708.
=> osc-staging: select: replace --from with --filter-from.

dist/package/openSUSE-release-tools.spec, rabbit-openqa.py
- 2 python modules required
- apiurl shouldn't take the default from config not from getopt
- fix typo in user name
=> Fix deployment problems on rabbit-openqa

osclib/core.py, repo_checker.py
- 1e34a8f47e9e05c649e22d1d64960caf9f337a02:
repo_checker: filter repository published check by arch.
- 30a42af6ca72192b72f3a6b61a557b9d37e0de44:
repo_checker: repository_state_last(): switch to simulate_merge as arg.
For the sake of consistency now that repository_state() also requires it.
- 12c9819614c1ecfa531754c69904f4e3a846335e:
repo_checker: repository_state(): limit meta revision to simulate merge.
Only staging projects are allowed to have psuedometa that makes it relevant
to include the project meta revision.
- ff722f03b898cb4dae5a48ccedbe51afa53970ff:
repo_checker: repository_state(): filter by relevant archs.
- dc91518b0a9657e1d38dc4a8033340f9cc3c60f6:
repo_checker: extract arch determination as target_archs_from_prairs().
- 83688cf0ed2fe56d55b8d5121fd98123e3b949bd:
osclib/core: …
=> repo_checker: filter repository state and published checks by relevant architectures.

osc-staging.py
Fixes #1738.
I'll move some adi packages around if no one tests this before me.
=> osc-staging: handle None value for --filter-from.

totest-manager.py
This block was not indended to be part of the loop body.
Untested.
=> Fix indentation in is_snapshottable

osclib/select_command.py
=> osclib/select: only check filter-from logic if argument was passed.

osclib/core.py
Without this if `x86_64` completes before `i586` and the imported `*-32bit` binaries cause an issue repo-checker may have accepted the reviews before it sees that. This is only possible recently after #1748 and I have not observed a case of this, but remembered this rather broken OBS behavior and confirmed in home project.
=> osclib/core: repository_published() make x86_64 dependent on i586.

devel-project.py
Now that the bug related to openSUSE/open-build-service#5571 has been fixed
the inverted behavior of exclude_target_projects no longer works. As such
the argument should be removed and only way to get the desired behavior
is to override include_request_from_project which includes request sourced
from specific project. For the purposes of `devel-projects requests` only
interested in requests targeting a specific project.
See also commit 0b342a5.
Observed the odd reminder comments on requests like: [644831](https://build.opensuse.org/request/show/644831). This is due to the fact that the request is not expected to be returned via the query.
=> devel-projects: remove workaround for OBS xpath bug during request search.

osclib/list_command.py, osclib/request_splitter.py
Without this, the relative rarer types of requests seen in projects with
staging and handled by list command will be included in staging proposal.
However, since they are not stageable the select operation will fail. This
change ensures that a filter is always present when stageable is True to
exclude non-stableable requests. The list command sets stageable to false
in order to list out the non-stageable requests of interest.
Without this change the following occurs until non-stageable requests are handled.
```
0#devel@YaST:Head:
bootstrap_required: false
group: YaST:Head
requests:
176229: yast2-storage-ng
176234: libstorage-ng
staging: E
strategy:
name: devel
1#none@all:
bootstrap_required: false
group: all
requests:
176055: llvm7
176057: vpp
176158: live-langset-data
176235: oprofile …
```
=> osclib/request_splitter: provide stageable option and make default True.

rabbit-openqa.py, systemd/osrt-rabbit-openqa.service
There were still exceptions not caught - and I have the suspicion
that the memory leaks we see in production are caused by the reconnects
(if you google for python memory leaks you end up with pika and lxml
examples - both we use here, so a restart every couple of hours can't
hurt)
=> Fail rabbit-openqa and have systemd restart it

userscript/README.md, userscript/staging-move-drag-n-drop.user.js
Since it has been mentioned a few times before as very desirable I took a stab at it for a couple hours. I would wager the result is well worth the effort.
Could follow this up with a server (hosted locally or remote with a bit more thought) to actually run the commands. In fact depending on how it is desired the remote server could be configured to allow for community members to be given selective move writes where the actually commands are run under `staging-bot` user. Essentially giving them limited staging access. I would expect the server to be simple to build.
For the initial version it just collects the moves and generates commands.
Activate via `ctrl+m` (for move) as indicated in legend once installed. Enjoy!
=> userscript/staging-move-drag-n-drop: provide initial version.

totest-manager.py
The LiveCD products (JeOS) for ARM will never follow
the same iso build numbers (and don't produce iso's to begin with)
than the main project. In lack of a "ignore mismatch for livecd
products only" option we just skip the syncing globally. that should
be fine as hopefully the main products always produce the same build.
=> [ARM] Skip build number comparison

dist/package/openSUSE-release-tools.spec, obs_operator.py, systemd/osrt-obs-operator.service, userscript/staging-move-drag-n-drop.user.js
- 408f8fb031091147d399f1daa064d7e506b54304:
dist/spec: provide obs-operator subpackage.
- 24d56d8eed79f044b13967d48e3e1a94496920b7:
userscript/staging-move-drag-n-drop: rework to utilize OBS Operator server.
- 3d0832f97d5bb2ae349d4b9a53272645ab846797:
obs_operator: provide initial version of server.
- 880bd1b638fb931448485d2b87d32bcdf91d0e20:
userscript/staging-move-drag-n-drop: provide option to click to start.
- d1e776379112c18164d83f1e94add038911499a2:
userscript/staging-move-drag-n-drop: move browser compatability check to init
I verified this by moving adi requests in both Leap and Factory that needed moving using the browser interface to trigger the OBS Operator server to make the selection changes (ie. drag-n-drop and press apply in browser).
=> obs_operator: provide initial version of server and update userscript/staging-move-drag-n-drop

totest-manager.py
exemple of output after change:
```
$./totest-manager.py --dry  --debug run Factory:PowerPC 2>&1
2018-11-05 09:59:23,874 - totest-manager:299 INFO job
opensuse-Tumbleweed-DVD-ppc64-Build-RAID5@ppc64 failed, but was ignored
2018-11-05 09:59:24,069 - totest-manager:299 INFO job
opensuse-Tumbleweed-DVD-ppc64-Build-RAID10@ppc64 failed, but was ignored
2018-11-05 09:59:24,259 - totest-manager:299 INFO job
opensuse-Tumbleweed-DVD-ppc64le-Build-extra_tests_in_textmode@ppc64le
failed, but was ignored
2018-11-05 09:59:24,480 - totest-manager:299 INFO job
opensuse-Tumbleweed-DVD-ppc64le-Build-gnome@ppc64le failed, but was
ignored
2018-11-05 09:59:24,679 - totest-manager:311 INFO job
opensuse-Tumbleweed-DVD-ppc64le-Build-extra_tests_on_gnome@ppc64le
failed, see …
```
=> [ttm] remove ppc64 (BE) for TW tempo bypass boo#1112920

ReviewBot.py, check_maintenance_incidents.py
Ignore is used to wait for a change to occur while patchinfo should never
affect the result. Since all actions must be accepted for the request to
be accepted setting patchinfo to accept is the correct way to ignore it.
Fixes #1730.
=> ReviewBot: accept patchinfo action reviews instead of ignore.

.travis.yml
I setup this internal list a few weeks ago, but haven't used it for anything yet. The idea being for more spamming topics really only relevant to us in addition to potentially using for third-party account e-mail address so everyone on team has access instead of bus factor 1.
Related #1770.
=> travis: configure notification e-mail to internal list.

.travis.yml
Allows for incremental work towards support while being able to see tests results and not have them mark every build as failing. Had to drop urlgrabber from python 3 install and adjust requirements.txt in travis since the real file should still point at `osc@master`.
=> travis: add test jobs against osc python3 branch for both python 2 and 3.

totest-manager.py
Containers are built in prj/images and released into prj:ToTest/containers.
openQA uses registry.opensuse.org to pull the publish enabled (!) containers
from there and test them.
If the test was successful, the containers are released from :ToTest.
I tested this code by doing a dry-run against `home:favogt:releasetest` (with some hacks to allow that).
WIP because `openSUSE:Factory:ToTest/containers` needs to be set up before merging this.
=> Add release workflow for container products

osclib/stagingapi.py
In some cases yaml.load(description_text) can return a string value 'none'. 
This will be fetched with isinstance(data, str)
=> fetch string value 'none' of data

osclib/conf.py
@aplanas and me checked - and the config still works with StringIO. As unicode and string have the same hash value for all keys we pass
=> Checked with aplanas: using stringio is preferred

osclib/stagingapi.py
Follow up with https://github.com/openSUSE/openSUSE-release-tools/pull/1774/commits/7a3b86fed17566f0680ee4eb8ad64238a70b77b9 , a regression happens, fixes UnboundLocalError: local variable 'disable_build' referenced before assignment error.
Hot-patched on packagelists.
=> stagingapi: No longer build disable to sub packages

osclib/stagingapi.py, staging-report.py
I received the following notification email:
```
Staging Bot wrote in project openSUSE:Factory:Staging:K:
Checks:
- pending
- [openqa:rescue_system](https://openqa.opensuse.org/tests/799404)
- [openqa:RAID0](https://openqa.opensuse.org/tests/799406)
- [openqa:cryptlvm](https://openqa.opensuse.org/tests/799407)
- [openqa:gnome](https://openqa.opensuse.org/tests/799408)
- [openqa:kde@64bit](https://openqa.opensuse.org/tests/799409)
- [openqa:kde@USBboot_64](https://openqa.opensuse.org/tests/799410)
- and 5 more...
```
This can only occur with new status report API and the new state "pending". The checks do not show as pending on a fresh staging, but do after it has been reset. It would be more consistent to show them in `missing_checks` as the openqa _placeholder_ is on fresh staging. …
=>  staging-report: ignore projects not in a final state.

pkglistgen.py
Fix a bug that NonFree repo solv data has not get updated.
=> pkglistgen: for nonefree repo handling should update to tool's repos rather than commandline's repos

totest-manager.py
- Has a different name than 15.0 images, so need to split from 15.0
=> Adjust JeOS for 15.1 images

dist/kiwi/osrt-worker-obs.kiwi, dist/kubernetes/app.yaml, dist/kubernetes/components/obs-operator/params.libsonnet, dist/kubernetes/components/obs-operator/service.jsonnet, dist/kubernetes/components/service.libsonnet, dist/kubernetes/environments/heroes/globals.libsonnet, dist/kubernetes/environments/heroes/params.libsonnet, dist/package/openSUSE-release-tools.spec, obs_operator.py
- 6b02225c75b7c26c2e7d900ce6430d474f7ebdb5:
dist/kubernetes: utilize new image home in openSUSE:Tools:Images.
- 2e50be7557f80c3c0f60d3efe9b53d1199e73878:
dist/package: include worker kiwi to allow extraction via _service.
Since the kiwi file will reside in the source package, it needs to be
referenced in order to appease Factory rpmlint.
- a75f4fbabbaff83ad047973bb7eb1ce0343a7bf1:
dist/kiwi/worker: include obs-operator subpackage.
- 6b1003fb062aabc542103ee3b91103d18f85d9e4:
obs_operator: use unbuffered output to work properly in systemd.
- 3ac0086154c85807a56c5be9914ef4caba87bf82:
dist/kubernetes: provide OBS Operator component.
Should accept [OBS request 649089](https://build.opensuse.org/request/show/649089) after merged to allow for kiwi file to be updated. Created [temporary branched …
=> dist/kubernetes: provide OBS Operator component (and related changes)

dist/package/openSUSE-release-tools.spec
This kiwi file is built in all places where this package ends, including
openSUSE:Factory, where it creates a problem as there is no tumbleweed#current
And we really don't want to build it again there, we only want it in
openSUSE:Tools(:Images)
=> Revert extracted kiwi again

ReviewBot.py
Sometimes maintenance adds specific containers to build in the
incident
ibs#177934 was declined by legal-auto because of some maintenance hackery. But legal-auto is not supposed to judge maintenace hackeries, but legal status. And that was actually fine.
returning False without setting a message is problematic anyway - as the legal-auto review was declined as 'ok'
=> If we can't resolve the package name, it's no reason to decline

.travis.yml
Rather silly there is not better solution, but as noted by others this is the only relatively sane way to do it.
- travis-ci/travis-ci#1094
- travis-ci/travis-ci#5063
- mozilla/build-tools@c13a297
An issue since coolo enabled testing in a fork a few weeks ago.
=> travis: use ecrypted e-mail address to avoid spam from forks.

osclib/check_duplicate_binaries_command.py
See https://github.com/openSUSE/openSUSE-release-tools/issues/1820
```
i586:
python3-clang:
- llvm5
- llvm7
x86_64:
gnome-themes-accessibility:
- gnome-themes-extra
- gnome-themes-standard
gnome-themes-accessibility-gtk2:
- gnome-themes-extra
- gnome-themes-standard
gtk2-metatheme-adwaita:
- gnome-themes-extra
- gnome-themes-standard
gtk2-theming-engine-adwaita:
- gnome-themes-extra
- gnome-themes-standard
gtk3-metatheme-adwaita:
- gnome-themes-extra
- gnome-themes-standard
libc++-devel:
- llvm5
- llvm7
libc++1:
- llvm5
- llvm7
libc++abi-devel:
- llvm5
- llvm7
libc++abi1:
- llvm5
- llvm7
metatheme-adwaita-common:
- gnome-themes-extra
- gnome-themes-standard
python2-astroid:
- python-astroid
- python2-astroid
python2-cmd2:
- python-cmd2
- python2-cmd2
python2-matplotlib:
- …
```
=> check_duplicate_binaries: set arch key to string instead of the list

suppkg_rebuild.py
view=binarylist is too expensive, use view=binaryversions instead.
see https://github.com/openSUSE/openSUSE-release-tools/issues/1826
=> suppkg_rebuild: use the binaryverions query instead

totest-manager.py
Apparently this is different to how x86 does it, and
we don't want to be different
=> ARM: don't set the snapshot version

totest-manager.py
same as already done for ToTest151ARM
Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>
=> ttm: remove set_snapshot_number in ToTest151PowerPC

pkglistgen/cli.py, pkglistgen/tool.py
So far I only cared for single projects, but never tested all staging projects in a loop while developing, so I didn't notice the problem
=> pkglistgen: Reset the tool between projects

osc-cycle.py
Most of the time I copy/paste a comma-separated package list from the obs WEBUI to the command line. With this, I don't have to worry about the commas in the list and we just strip them away. A few minutes won whenever this is used.
=> osc cycle: correctly handle comma-separated arg list

pkglistgen/cli.py
please note that this is an incompatible change, but all our openSUSE product pool repo listings are currently anyway broken.
=> fix incompatible repo id tagging for openSUSE products

osclib/core.py, repo_checker.py
This is based on a discussion with @jberry-suse. The way we currently rely on the target project is just too problematic, so we no longer - at the price of reporting more problems as ring problems.
Most requires should come from the staging project itself - if it's just too expensive, binaries to ignore can be put in repo_checker-binary-whitelist-ring in the target project's config.
I setup Factory this way, reported 9 bugs for SLE15 and created an extensive blacklist there - and started to do the same for leap (WIP).  
What I tested:
- Factory letter stagings
- Factory adi stagings
- Leap letter stagings
- SLE15 letter stagings
=> Change repo checker to expect non-leaky rings

rebuildpacs.pl
(and this causes a 404 on rebuildpac, which might stop the rest)
=> Remove openSUSE-images from rebuildpacs - long gone

osclib/list_command.py
- 01d9504d90a403b8dddc44bf1f1208bb312f5f24:
osclib/list_command: 24ae4ba81 broke formatting.
```
The author was attempting to port for python3, but changed the meaning:
- print ' ', line
+ print(' ' + line)
The first prints "  $line", while the second:
" $line".
This changes console output from:
science
666254 libArcus-lulzbot               -> delete       (delete request)
3 more users
back to:
science
666254 libArcus-lulzbot               -> delete       (delete request)
3 more users
(ignore lines up and standard double space indent used)
```
=> osclib/list_command: 24ae4ba broke formatting.

compare_pkglist.py
silly me! I'm the only user though.
=> compare_pkglist: fix return code handling introduced by 2e339acffb03b6786c902c2ebd250d1c3720e315

totest-manager.py
Mostly untested - not sure how that could be done.
=> Add kubic-kured-image and kubic-pause-image to container_products

staging-report.py
Having suse and opensuse bots on the same service requires to differ by
apiurl
=> Need apiurl for staging report

.travis.yml, dist/ci/flake-extra, dist/obs/OSRT:OriginConfig.xml, dist/package/openSUSE-release-tools.spec, origin-manager.py, osclib/cache.py, osclib/conf.py, osclib/core.py, osclib/origin.py, osclib/stagingapi.py, osclib/util.py, systemd/osrt-origin-manager.service, systemd/osrt-origin-manager.timer, tests/obs.py
- 04d09cd81d9afd54667d55921eebdc173eaaa034:
travis: add check to complain about product references in origin-manager.
- d1f13210f26da99d5d5eeabe5a0a2889c7ccb0a3:
dist/package: provide origin-manager sub-package.
- cc404de74a732b78d2f6c4fac8abafacddf3f8d8:
systemd: provide osrt-origin-manager service and timer.
- 33ffa4bb8047c9f11c1a0837e9c3edcb24e57478:
origin-manager: provide ReviewBot utilizing osclib.origin.
- f73166a3784456f811c5912c5b468bed7f97a2dd:
osclib/origin: provide origin management functions.
- e86194bb04105e80e00fc7ff7384988784d69101:
dist/obs: provide OSRT:OriginConfig definition.
- fa13a011f6cfc8f93c6f19980b4d2a7faeee83d1:
osclib/util: project_version(): return 0 instead of None for invalid project.
This allows for lists with invalid projects to still be sorted which is …
=> origin-manager: core implementation (replace leaper/manager_42)

build-fail-reminder.py
Following a change in OBS, the project parameter is always required in the project/status route.
The commit:
openSUSE/open-build-service@f795712#diff-61c12a5866566c0d732134f0c447d788
Thank you to @lnussel for reporting this on IRC.
=> Fix project/status route

dist/kiwi/osrt-worker-obs.kiwi, dist/kubernetes/app.yaml, dist/kubernetes/components/origin-manager/params.libsonnet, dist/kubernetes/components/origin-manager/review.jsonnet, dist/package/openSUSE-release-tools.spec
For posterity since lacking proper authentication setup on k8s cluster to allow other release managers access.
=>  dist/kubernetes: add origin-manager component.

osc-cycle.py
Allow for the plugin to easily be usable outside of openSUSE:Factory as well
=> cycle: Add command line parameter support

dist/ci/Dockerfile
There is no need for Tumbleweed base as only the latest stable osc tools
and openSUSE:Tools packages should be needed. Unlike run-time for
repo-checker which is limited by latest solver stack the distribution
test suite has no need.
Currently, there is a zypper related segfault, #1887, that breaks the
test suite and demonstrates an advantage to switching to Leap.
Fixes #1887.
=> dist/ci/Dockerfile: change from Tumbleweed to Leap for build host.

devel-project.py, dist/package/openSUSE-release-tools.spec, osc-origin.py, osclib/core.py, osclib/origin.py, osclib/util.py, systemd/osrt-origin-manager-report@.service, systemd/osrt-origin-manager-report@.timer
- 3a8e54c4b82f2761d2a6d26176d5e8ae81944b6e:
dist: provide origin-manager report service and timer.
- 6ce6fd46796aa76f58e4a082fed19ec40a1a2894:
dist/package: provide osc-plugin-origin package.
- 04e9b29f2090765d6f26def572dfa2ff5cb50a01:
osc-origin: provide initial origin osc subcommand.
- ecb00c7c4c10ed40166eb533401fea0f6f96f6a5:
osclib/core: package_list_without_links(): ignore meta packages (00 prefix).
- eb1cd60d063d10e7b4b4118494bd17c1ee2e08ad:
osclib/origin: provide __str__ method that indicates pending.
- 98dc37f56088b7e30b94313a4348061694dceaa3:
osclib/origin: config_resolve_create_family(): force origin_expanded to string.
Drops the lxml string element reference which is cumbersome when printing.
- 99675253d8035d53b35bcbbef3f4e99bc3ff784c:
osclib/util: mail_send(): allow a from_key …
=> origin-manager: osc plugin (origin) and report service

devel-project.py
As requested in [poo#39467](https://progress.opensuse.org/issues/39467). Other uses of `mail_send()` use mailing lists as to address and should explode if they fail.
=> devel-project: notify: catch smtp exceptions rather than crashing.

osclib/stagingapi.py, totest-manager.py
The following warning is output:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
=> Replace deprecated (and not advised) yaml.load() with yaml.safe_load().

data/apimap.json, data/incidents.json, data/repos.json
Tested with
```
./openqa-maintenance.py --dry --debug --review=accept-onpass --group qam-openqa --openqa=https://openqa.opensuse.org review |& grep '\(15.1\|684360\)'
```
which yields
```
DEBUG: openSUSE:Leap:15.1:Update -- product in apimap
DEBUG: Pmap: {'distri': 'opensuse', 'flavor': 'DVD-Incidents', 'version': '15.1'} Posts: []
…
```
but not the test request https://build.opensuse.org/request/show/684360 I have created
=> [openqa-maintenance] Add openSUSE Leap 15.1 configuration

osclib/origin.py
In order to reduce comments, information that changes such as reviews
must be excluded to avoid having to update a comment or be left in an
inaccurate state.
Fixes #1897.
=> osclib/origin: policy_input_evaluate(): do not list disallowed reviews.

origin-manager.py
A stop-gap to aid in human review until UI exists.
Fixes #1881.
=> origin-manager: include origin annotation in comment when waiting.

dist/package/openSUSE-release-tools.spec, staging-installcheck.py
Implement a new command that takes a target project and one of its
staging projects and will run the checks against that project (including
delete requests) and if all is fine approves all reviews selected in
that staging.
This is to be used as part of the staging pipeline (and has been tested
with Factory's staging projects)
=> Repo checker: work on staging projects as a whole

pkglistgen/tool.py
the weak remover code is a little slow, but it's also a lot of data
=> Avoid gocd warning on 9 minutes without print

osc-origin.py, osclib/core.py, osclib/origin.py
- 42cca7a134e1445177df3c620f16444931ecab51:
osclib/origin: policy_input_calculate(): s/inital/initial/.
- 613227c7013a3726940fec78c7029092e2e250ab:
origin-manager: policy_result_handle(): denote annotation dump as preformatted.
- 8cdc99c1beef4865ccf63013598b322b1549de87:
osc-origin: list: sort by package name.
- b6866e6456fc54459402660576ed619074e154e6:
osclib/origin: policy_input_evaluate(): only add additional review if not already set.
This allows for more cleanly adding additional_reviews to include fallback
review where it may already be added for a more specific reason.
- 07ecf7b2504a87f6c6b9fdc78bee34a0f0296fe5:
osclib/core: package_source_hash(): handle non-existant revision.
=> origin-manager: miscellaneous improvements.

dist/package/openSUSE-release-tools.spec, obs_operator.py, osc-origin.py, userscript/README.md, userscript/origin.js
- ca687d4089bcbc2f82e8a4c50f2719eb4a4ce72f:
userscript/origin: provide initial supplementary interface.
- 0734bf756c55df56fe61e2c2c3b6544b2e217dbb:
obs_operator: expose osc-plugin-origin commands via GET.
- 2c45688f2f2a6f6f0dc829ce913b7317a6a0fc06:
obs_operator: extract osc environment setup as with object.
- 3293a24a894fdf4350d35a749fac8c79f13988d4:
osc-origin: osrt_origin_lookup(): print time since generated.
- d5dff4d15c01513b67568be31f9664c3f84bdbf3:
osc-origin: osrt_origin_lookup_file(): include project in cache file name.
No frills supplementary interface that makes use of operator server. Can expand OBS overlay JS to provide links to overall origin list and report, etc.
The "UI" as referred to will use the same basic format of querying the operator sever origin data paths, but will …
=> origin-manager: expose osc-plugin-origin commands via operator and provide initial supplementary interface.

osclib/conf.py
This leaves repo checker for incidents
=> Don't add repo-checker from factory-auto in Leap

userscript/origin.js
Otherwise, requests are denied with not running operator server in development mode. This is the same behavior used by drag-n-drop selects, just overlooked.
=> userscript/origin: use cross-domain request with credentials.

obs_operator.py
- 2a3def39fd589be32652ba63b339d378a144e753:
obs_operator: verify that origin root-domain matches host domain.
Reduces the attack surface by limiting sites that can initiate a
cross-domain request to sub-domains of the domain on which the operator
server is running.
- d3ff38cbf8edd16b1b28cd72fbffd1998a99f643:
obs_operator: raise exceptions when osc request environment cannot be aquired.
- cdb99a1f1a57c6de5d07c2be952253e2600f00a4:
obs_operator: calculate apiurl from host instead of origin header.
Debated originally, but was attempting to allow operator to run on
different domain from request origin and handle multiple origins. This
does not work in practice since openSUSE and SUSE https certs are not
present on same machine. As such, host works better since it allows for
non-cross-origin …
=> obs_operator: improve robustness

dist/kubernetes/components/obs-operator/origin_manager_report.jsonnet, dist/kubernetes/components/obs-operator/params.libsonnet, dist/kubernetes/components/obs-operator/service.jsonnet, dist/kubernetes/components/service.libsonnet, dist/kubernetes/environments/heroes/params.libsonnet
- 8f53d66594f35c7ee06d4321afec3066ba30458e:
dist/k8s: drop --debug flag from obs_operator service.
- 9fbab1b87eaeb4632ff2e1a055f058dd32720977:
dist/k8s: provide obs_operator origin-manager report sub component.
Refreshes origin information 3 days a week for quick serving from cache.
- 9d1264390c7ceba52dc3820bc0629ce9cbe9efdb:
dist/k8s: add service cache to obs_operator.
- 8912b660c5900ac1c6f750518b56d37882940cfb:
dist/k8s: provide service level cache similar to reviewbot cache.
=> obs_operator: provide cache volume and origin-manager report cron.

ttm/manager.py
If we release 000product with set_release the FTP tree is mis-named
=> Remove the special logic for 000product

osc-staging.py, osclib/stagingapi.py
- NonFree delete requests are never staged.
- NonFree submit requests are handled by adi command.
Fixes #1932.
=> osc-staging: exclude NonFree requests from staging proposals.

origin-manager.py
Delete requests were intended to be handled in more detail along with
the update crawler re-write, but in the meantime always fallback.
Fixes #1933
=> origin-manager: require fallback review for delete requests.

ReviewBot.py
Prevents a single failure from stopping all reviews.
```diff
diff --git a/origin-manager.py b/origin-manager.py
index 952da66b..c44e68b8 100755
--- a/origin-manager.py
+++ b/origin-manager.py
@@ -18,6 +18,7 @@ class OriginManager(ReviewBot.ReviewBot):
self.override_allow = False
def check_source_submission(self, src_project, src_package, src_rev, tgt_project, tgt_package):
+        raise Exception('caboom')
if not self.config_validate(tgt_project):
return False
```
```
$ ./origin-manager.py --dry --debug id 688427
[I] checking 688427
File "/home/jberry/openSUSE-release-tools/ReviewBot.py", line 183, in check_requests
good = self.check_one_request(req)
File "/home/jberry/openSUSE-release-tools/ReviewBot.py", line 375, in check_one_request
ret = func(req, …
```
=> ReviewBot: handle any exception raised by check_one_request().

osclib/freeze_command.py, osclib/select_command.py, osclib/stagingapi.py
This change is trying to provide user more information
in case that he already froze project but date of last
freeze was not updated, since there were no changes for
last MAX_FROZEN_AGE days.
* Use osclib.freeze_command.MAX_FROZEN_AGE constant
* Avoid explicit proposal of --no-freeze bug suggest alternative
=> Improve error msg that the project was not frozen

ttm/cli.py
It may be necessary to fix the TTM Status to be aligned with reality, so
provide a command line to do so easily (osc is unfortunately useless for
multiline attributes)
=> TTM: add fixup command to update attribute

ttm/publisher.py, ttm/releaser.py, ttm/totest.py
totest_images_repo defaults to product_repo if unset.
That's not exactly the same behaviour as before (following the releasetarget),
but should cover all current projects.
=> Add option to release image_products into a separate repo

container_cleaner.py, dist/package/openSUSE-release-tools.spec, gocd/container-cleaner.gocd.yaml, tests/container_cleaner_tests.py
Currently every single container released to `openSUSE:Containers:Tumbleweed` is kept forever, that needs to change.
Only those containers providing binaries to the latest five version for each
archs are kept, all others are deleted.
=> Add program for cleaning up maintenance_release projects for containers

dist/ci/miniobs/BSConfig.pm.patch, dist/ci/miniobs/Dockerfile, dist/ci/miniobs/config.yml, dist/ci/miniobs/database.yml, dist/ci/miniobs/database.yml.local, dist/ci/miniobs/docker-compose.yml
The default user is Admin:opensuse and the docker compose opens only one port at 3737 running the api/webui
This can be used for CI on sources or to build against it with osc (if you add interconnect project), but it won't build packages
Cherry picked from #1963 to avoid the chick-egg problem, I already created the OBS project
=> Add small OBS instance without data

dist/ci/flake-extra, obs_operator.py, osc-origin.py, osclib/core.py, osclib/origin.py, userscript/staging-move-drag-n-drop.user.js, web/origin-manager/index.html, web/origin-manager/main.css, web/origin-manager/main.js, web/origin-manager/util.js
Tested thoroughly for `openSUSE:Leap:15.1` and `openSUSE:Leap:15.1:NonFree`. An example can be seen below which demonstrates the usefulness of revision summary for finding problems.
The interface uses anchors, instead of URL state changes, to allow for direct linking and forward-backward navigation while avoiding needing a server setup to redirect non-static requests to `index.html`. Alternatively, this could be changed to not use anchors.
The potential origin rows are clickable to see embedded diff with the diff icon (three lines) opening diff externally in OBS UI. The submit button prompts for a message (optional) and confirmation before generating a submit request.
A list of projects managed by origin-manager is presented when no project context is available.
The current origin is used …
=> origin-manager: provide web interface to aid in maintenance and decision making

dist/package/openSUSE-release-tools.spec
- 0225a8e95537b976bbaf98d49248e6f53f96b6cb:
dist/package: handle python 2 vs python 3 dependencies.
Since osc was updated to require python 3 handle dependencies in
same fashion as osc so as to get them right.
- be729c0bd143d273c7bb4a565a9ee281f8dbaccf:
dist/package: require influxdb and telegraf for Tumbleweed.
The packages have made there way into Tumbleweed and thus can now be
required instead of suggested.
- 9214736f378e3d959ae5bcf625648e994432ccb8:
dist/package: drop %check and related build requirements.
Not feasible to run tests on OBS.
For Tumbleweed deployments, including kubernetes from container image, the pre-python 3 version of `osc` is packaged and used. If this PR is accepted that will break since it will depend on python 3 dependencies. If this state goes on for a while …
=> dist/package: handle python 2 vs python 3 dependencies.

osclib/origin.py
- e20725a482349e1f371917d9a7377543cc482bb7:
osclib/origin: handle origin_info when None.
- cbd3e446e6fcec47b6263b7e2ef198db2f349021:
osclib/origin: origin_revision_state(): do not find origin when None.
Previously, there was no way to distinguish between a None origin and no
origin_info passed in. Using False as default allows the two cases to be
distinguished.
=> origin-manager: handle no origin when determining revision state.

dist/ci/testenv-leap151/Dockerfile, dist/ci/testenv-leap151/README, dist/ci/testenv-leap151/osc-hotpatch.diff, dist/ci/testenv-leap151/run_as_tester
The container will be built on OBS and be used on travis to avoid waiting
for the container to build (or to error because of download.opensuse.org madness)
=> Add container for testing in leap 15.1

.travis.yml
Together with ChrisBr I developed a solution to test the package build of a git report directly in OBS. It's currently in phase of refactoring, so I forked it temporarly to https://github.com/coolo/pull_request_package
and setup a local cron job to run 
`docker run -v=/space/puller-config:/config -t openqapusher/osrt_pull_request_package`
every 5 minutes. The OBS builds have a much quicker turn around time as they are closer to the binaries required.
=> No longer build packages in travis but in OBS

metrics.py
Works around ingest job crashing due to lack of memory. Hard to properly
workaround due to lack of sort API option from OBS.
=> metrics: reduce request period to after 450000.

dist/package/openSUSE-release-tools.spec, systemd/osrt-obs-operator-origin-manager-report@.service, systemd/osrt-obs-operator-origin-manager-report@.timer, systemd/osrt-obs-operator.service
Same as kubernetes deployment, but for internal non-k8s use.
=> systemd: include OBS Operator origin manager report service template.

.travis.yml
All other test suites were removed which makes the condition never met.
=> travis: restore deployment functionality.

osclib/stagingapi.py, tests/api_tests.py
I tried to replace the Mocking of functions with httpretty, but unfortunately httpretty replaces all other API calls with 404s then.
What we'd need is a library sniping out single requests - possibly by mocking the http_GET function, but that's tricky as well with caching already overwriting it.
=> Remove more references to vcr

osclib/core.py, tests/fixtures/repository/openSUSE:Factory.xml, tests/fixtures/repository/openSUSE:Factory:Staging.xml, tests/fixtures/repository/openSUSE:Factory:Staging:H.xml, tests/repository_tests.py
I got the algorithm wrong - it overwrites repositories only when used in the same path, not by recursion
=> Fix repository_path_expand to also work in Factory stagings

suppkg_rebuild.py
Convert all items to String in a List to fix TypeError when executing on python3.
File "suppkg_rebuild.py", line 42, in get_support_package_list
if re.match('Preinstall', line) or re.match('VM[Ii]nstall', line) or re.match('Support', line):
File "/usr/lib64/python3.6/re.py", line 172, in match
return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
=> suppkg_rebuild: Fix TypeError on python3

obs_operator.py
The CORS pre-flight OPTIONS calls do not include the session headers,
but should validate everything else bsides the session.
=> obs_operator: do not require session for OPTIONS method.

userscript/origin.user.js
Rather it should be assumed that the project does not intend to have
origin information.
Follow-up on #1982 which introducing error message which really does not apply when no OriginConfig attribute.
=> userscript/origin: do not show failed when no OriginConfig.

ttm/releaser.py
Currently everything needs to have a maxsize defined, but for most it doesn't
make sense. So only keep those which do and don't impose a limit by default.
Next step would be to move this into the configuration.
=> Only impose a maxsize for a selected list of packages

userscript/origin.user.js
Handles multiple actions properly, although still a giant PITA.
Works live for SLE-12-SP5 as everything is deployed internally. Proper package list pending #2014 (running that job currently). openSUSE deployment pending kubernetes access to update deployment and DNS cname (#1975).
Only bother to test request interface against beta OBS theme as they differ enough that it is difficult to support both with multiple actions.
When package or projects are abbreviated by OBS it messes up the userscript. There are data values present in the page, but they are incredibly inconsistent depending on the type of request and underlying state. It may end up making sense to try and add operator call to assist, but mapping the resulting data back to the page when be similarly difficult unless the order of …
=> userscript/origin: rework to handle requests and interface link.

CNAME
Utilized for serving content of web directory.
Requires [poo#51002](https://progress.opensuse.org/issues/51002) or local entry.
=> Add CNAME for github pages serving.

check_tags_in_requests.py
- 655bac280fe44e6c01cc28ef4227415c8997068b:
check_tags_in_requests: escalate loss of issue references to a decline.
- 45e6b617e10bf627c191f56dc7edec7921ce5437:
check_tags_in_requests: make issue singular since references is plural.
- a309e1c85b680a99a968987918ed5440c8775d61:
check_tags_in_requests: issue state is deleted not removed.
See #679, where it was originally added and provides example output.
Fixes #1991.
=> check_tags_in_requests: issue state is deleted not removed.

osclib/accept_command.py, osclib/core.py, osclib/stagingapi.py
Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2022
Use `source_file_load()` to get product file. And make `source_file_load()` always return string.
=> Some TypeError fixes for python3

devel-project.py, osc-origin.py, osclib/core.py
- 9302407e33e86e516a02b78f583706e72d4dc2be:
osclib/core: rework as package_list_kind_filtered().
- 0857bdfb9aaf6ec896b49f9b098119dc3aaceea9:
osclib/core: provide package_kind().
Per [mailing list discussion](https://lists.opensuse.org/opensuse-buildservice/2019-05/msg00020.html) not going anywhere fast. As such better to have something to mostly works than mostly does not (for SLE and Leap :Update projects).
Still running a full set locally to see if anything crops up.
=> osclib/core: rework as package_list_kind_filtered().

origin-manager.py, osc-origin.py, osclib/origin.py, osclib/util.py
- 69f3fd13c8f48bbe74d635f868139e79737dbece:
origin-manager: switch to python3.
- ceb4a9cea9598659a1970d57a367c9e4fd7b7d14:
osclib/origin: cast filter() to list() to improve debug output [python3].
- 743b3a6cd63ce51b891a53ee39f6739b5d417282:
osc-origin, osclib/origin: port first dict key/value access [python3].
- 7a1ff946cd2abf5cc4ca2873dd2553eacc739ac5:
osclib/util: sha1_short(): encode data as utf-8 [python3].
=> origin-manager: port and switch to python3.

gocd/update.osrt.gocd.yaml
As we don't submit if there is a request pending, we need to check
later on if there were changes
=> Submit openSUSE-release-tools even if there are no changes

PubSubConsumer.py, gocd/rabbit-openqa.py, gocd/rabbit-repoid.py
We need to ACK the rabbitmq message for the server to erase it in the queue - otherwise they are piling up endlessly. As we quit the services every hour the queue is reset at that point, but that still makes monitoring the server quite hard as the queues tend to be full all the time
=> Acknowledge the rabbitmq message

dist/package/openSUSE-release-tools.spec, requirements.txt
As the package does not exist as python3 variant in leap 15.1, we
better remove it now
=> There is no use of urlgrabber left

dist/kubernetes/environments/heroes/params.libsonnet, osclib/util.py
- c4dccf80ab91f933a893b6faf5e0bc60abbb7210:
dist/k8s/heroes: include openSUSE:Leap:15.1:NonFree in origin_manager_report.
- 14ae392743ff8d71abd530779dc0569f8d324ab9:
osclib/util: correct python3 port by casting to list directly after filter.
8bf2602 cast to list during on the return line, but that does not work
if a project_suffix is present.
The python3 commit is needed since :NonFree project triggers the other branch which causes a crash with the prior port attempt.
=> dist/k8s/heroes: include openSUSE:Leap:15.1:NonFree in origin_manager_report.

osclib/accept_command.py
Regression from acc0ffc3852700cc996109f350f72dcb9ff1b3fe , we still need url for uploading product file change. That's why my testing on Leap works but now it's a problem on TW.
=> accept_command: fix missing the url for uploading product file change

.gitignore, README.md
While going through never merged branched and stash to get small origin-manager follow-ups I decided to add a bit for developing against git osc since it became especially relevant again with python 3 porting.
=> .gitignore: ignore osc symlink commonly used to develop against git osc.

osclib/core.py, systemd/osrt-obs-operator-origin-manager-report@.service, systemd/osrt-origin-manager-report@.service, userscript/staging-move-drag-n-drop.user.js
- 84ead945f36bb05107268aa251e8348345e3feae:
userscript/staging*: only utilize the last two domain components.
Allows for the hostname to contain multilevel subdomain and still access
the same operator server. Consistent with changes made to operator and
origin userscript.
- dde0edef40625b76f3f30dfb463d6fd9f37a741c:
osclib/core: package_version(): drop lxml element and return string version.
Resolves undesirable output when formatting a data structure that includes
the result from this function as yaml.
- fb34f6214347fc5404da290e0fde57ce5d3f89dd:
systemd: increase timeout to 24 hours for origin-manager report services.
A few follow-ups.
=> origin-manager: small follow-ups.

gocd/checkers.opensuse.gocd.yaml, gocd/checkers.suse.gocd.yaml, gocd/checkers.suse.gocd.yaml.erb
This is mainly to tag the sources that are in the projects for safer
cleanup strategies
=> Move legaldb import of projects into gocd

gocd/autosubmit.gocd.yaml
It was stuck for 2 months on packagelists without one noticing, so put it on the bot dashboard (needs to be ported to python3 though)
=> Run obs-autosubmit on gocd

build-fail-reminder.py, gocd/build-fail-reminder.yaml
The timer is stopped on packagelists and the data migrated. The service only ran for openSUSE:Factory atm (leap 15.1 was never enabled it seems)
=> Run buid fail reminder on botmaster

gocd/check-duplicated-binaries.gocd.yaml, gocd/staging.bot.gocd.yaml, gocd/staging.bot.gocd.yaml.erb
This way we don't rely on installed plugin (to avoid the deployment cycle) and we don't need to install into the real home of the go user to avoid risking that a broken plugin breaks all future jobs of the agent
=> Use a temporary directory for staging plugin

osclib/stagingapi.py
We need to keep the cicount in sync for the kernel as kernel-syms requires kernel-default of kernel-source
=> Fix inner-staging links to use cicount=copy

dist/package/openSUSE-release-tools.spec, scan_baselibs.py
Help us to deal with 32bit RPMs has not been imported to 64bit build result which was a trouble for us couple of weeks ago, and we still being affected by that, with this script we know what package need to wiped the binaries manually or by --wipebinaries.
=> Add a script scan_baselibs.py to verifying importing 32bit binaries

rebuildpacs.pl
A further workaround for https://github.com/openSUSE/openSUSE-release-tools/issues/1222
=> rebuildpacs: ignore issues of petsc:openmpi

ReviewBot.py, check_maintenance_incidents.py, origin-manager.py, osclib/core.py, osclib/origin.py
- 25d1584899852c82a67757ced4ed3640f7ae5a0c:
osclib/origin: correct import order.
- cd3c011c756c1ea7b296690e317bcecef5827276:
osclib/origin: support pending source lookup against maintenance origin.
Works for both maintenance incident (both states) and release.
- 05cc79a1f823c86ae015cc01c5eabd352b8e966e:
osclib/origin: handle nested annotation loading and support maintenance incidents.
- 086117e4ca2b05c31f152ede7a5087cec8c69126:
osclib/core: provide a series of request list generators.
Given the broken design of multi-action requests which continually wreaks
havoc on code attempting to handle them properly a series of methods for
searching for requests are provided to simplify the process. The core
principal is that both a request and action are returned since the
specific action that …
=> origin-manager: handle maintenance workflow at multiple levels

gocd/totestmanager.gocd.yaml
Those TTM runs are still actively being used and shouldn't have been removed.
(CC @jberry-suse)
=> Fix 15.1 images by introducing them again

project-installcheck.py
This way you can easily look only the commits affecting one repo
=> Have the storage commit include the details what is was for

osclib/repochecks.py, project-installcheck.py
Otherwise the output will differ on rebuilds, making the whole stunt
useless
=> Filter out release numbers from problem output

osclib/origin.py
This was debated as for SLE this would add some repetition when not
going to match a SLE origin anyway, but it is necessary to stabilize
maintenance origins.
When an :Update project is first created all sources are inherited which
means all the revisions from the top project's source container are
considered. Once an update is provided via a maintenance incident the
inherited sources are no longer presented and instead the only revision
seen is the maintenance update and future updates.
When a new version of Leap is created and all source containers are copied
from the previous version the origin will first be considered :Update of
the previous Leap version, but once a maintenance update is created it
will drop the the non-:Update prior version since the matching revision is
missing. If …
=> osclib/origin: always include project link when fetching source history.

gocd/checkers.opensuse.gocd.yaml, osc-origin.py, osclib/core.py, osclib/origin.py
- ff7bfdca711bc6f6c2e44828b09d298cb74860b8:
gocd: provide OS.Origin.Manager.Update.
- 40aa37edb98ef9b570dcf09067d6053a39ce9bca:
osc-origin: provide update command.
- 5230864d7271d2bd69ac643182ad31a57cfc55e3:
osclib/origin: provide origin_update() to process updating single package.
- 7478a428820a86e70748e2b657c0b1aee5145876:
osclib/core: provide request_create_delete().
- f441d8e41ddc2eac9d06a0daba23ca013a245c0c:
osclib/core: provide request_create_submit() and RequestFuture.
- 844a9d28a5e78da37d83d14812665e363b5e3927:
osclib/core: provide message_suffix() and utilize in source_file_save().
Already generated 214 submit requests for packages whose origins contained updates against `openSUSE:Leap:15.2` using this code or earlier revisions of it. Based on discussions have disabled submission …
=> origin-manager: provide equivalent to update_crawler as osc-origin update command

gocd/checkers.opensuse.gocd.yaml
This is very ugly, but following the pattern laid forth.
=> gocd/checkers.opensuse: wrap OS.Origin.Manager.Update with osc-origin install.

gocd/check-duplicated-binaries.gocd.yaml
See [poo#52094](https://progress.opensuse.org/issues/52094). Not sure why these services were not properly ported to gocd originally. :/
=> gocd: duplicate Duplicated.Binaries check for Leap.

osclib/request_splitter.py
- d5188b326f9b3edc3a67b811200f3ede48f16cc5:
osclib/request_splitter: quick strategy: s/leaper/origin-manager/.
- d3593cfed968d3a57859ec5f98e089d95239507b:
osclib/request_splitter: quick strategy: remove repo-checker from whitelist.
=> osclib/request_splitter: update quick strategy for origin-manager and staging checks

ReviewBot.py, obs_operator.py, osc-origin.py, osc-staging.py, osclib/sentry.py
- 776747c9b5350267f5db6ba5c6288f45fcdf381b:
osclib/sentry: expose environment configuration.
- 8b82d024f62400e9b97ccc4b66f2a91b5a41574b:
obs_operator: provide sentry_sdk integration.
- 7915299229cd780338448246dc285ed32a3024bb:
osc-origin: provide sentry_sdk integration.
- c71949f12bff044b93c53424a1a876b786799baf:
osc-staging: provide sentry_sdk integration.
- 5dd0a9906892e29c492802395e798c671602085c:
ReviewBot: provide sentry_sdk integration.
- 6003bff62a2f1e22b282aad6c0d8594e70c991f6:
osclib/sentry: provide initial sentry_sdk handling.
Allows for DSN to be configured via oscrc general.sentry_sdk.dsn.
Given the various different deployment environments and machines it is non-trivial to monitor and extract errors. With this integration some context is provided and once deployed should aid …
=> Initial sentry integration and configuration for obs_operator, osc-{origin,staging}, and ReviewBot.

userscript/origin.user.js
This reverts commit 249a35efe6be9ebbf516fc4c5969cdc33e9cb767.
Undesired hide on package pages and acceptable on request.
=> Revert "userscript/origin: hide request card when no OSRT:OriginConfig."

obs_operator.py, osclib/origin.py, web/origin-manager/main.css, web/origin-manager/main.js
- a189e946154b18d98f8685cf1942a4b0f2a3ed16:
web/origin-manager: allow a request to be diffed against a potential origin.
- e3d67622e9be7c4a51333f9cff50e8674e4d7c45:
web/origin-manager: display the reason for a diff failure.
- 114f25e004ca0cdeb6a4f5635c2149c84578766a:
web/origin-manager: properly handle potential origin de-selection.
- 0e1d9ef25a43c17587a51b480930bc282ed42bff:
web/origin-manager: properly handle package de-selection.
- 275db9b0d2aea9562621706fc60e014b5d51b4b0:
web/origin-manager: clear table data before loading new data.
Further clarifies new data is being loaded and when an error occurs the
prior data does not remain after the error messsage.
- 5ee09feb2749f927676b7b1ffa60ba02875c7d7e:
web/origin-manager: table_selection_set(): handle undefined table.
- …
=> web/origin-manager: allow a request to be diffed against a potential origin (and related fixes).

obs_operator.py
An example stack trace from production:
```
Exception happened during processing of request from ('172.16.4.0', 59122)
File "/usr/lib64/python3.7/socketserver.py", line 650, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib64/python3.7/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib64/python3.7/socketserver.py", line 720, in __init__
self.handle()
File "/usr/lib64/python3.7/http/server.py", line 426, in handle
self.handle_one_request()
File "/usr/lib64/python3.7/http/server.py", line 414, in handle_one_request
method()
File "/usr/bin/osrt-obs_operator", line 75, in do_GET
with OSCRequestEnvironment(self) as oscrc_file:
File …
```
=> obs_operator: allow illegal cookie keys.

dist/package/openSUSE-release-tools.spec, obs_operator.py, osclib/sentry.py
- 3a2aed7f333b43fbd8b00a0d2db4cd0b7ddd677e:
obs_operator: override HTTPServer.handle_error() to capture exceptions.
- d10a359c0c6bf0e12926b10fc7da43420eb6b122:
osclib/sentry: tag osc version.
- eb0a6c46594ab14b181a367b4b3a2bd4ce944c18:
osclib/sentry: provide dummy client.
- cbfbb880488a184f218a4fb84c012044e81c48f0:
osclib/sentry: sentry_client(): handle 0.11.x API change.
=> sentry: update for 0.11.x, general improvements, and operator exception handling

osclib/request_splitter.py
Python 3 makes map() a lazy call and since the result is not needed it
makes sense to just switch to explicit loop. Without this the "loop" (via
map) is never executed. As such, --try-strategies effective does nothing
and instead the staging-bot always falls back to none strategy.
=> osclib/request_splitter: replace map() calls with loop and call.

oqamaint/openqabot.py, oqamaint/update.py
The default of openQA changed - _NO_OBSOLETE no longer exists, but for
the test repo we want obsoletion
=> oqamaint: fix more python3 issues and add _OBSOLETE=1

osclib/core.py
- 016bca069d79768ce70b12fe90d0b6fd6912fc5e:
osclib/core: request_action_key(): handle add_role/set_bugowner against project.
- a6d0974e27a041edba031ae2103b6e51d01b5f00:
osclib/core: request_action_key(): include set_bugowner in top level condition.
[request 728279](https://build.opensuse.org/request/show/728279) caused:
```
TypeError: sequence item 1: expected str instance, NoneType found
File "ReviewBot.py", line 187, in check_requests
good = self.check_one_request(req)
File "ReviewBot.py", line 397, in check_one_request
key = request_action_key(a)
File "osclib/core.py", line 808, in request_action_key
return '::'.join(['/'.join(identifier), action.type])
```
=> osclib/core: request_action_key(): handle add_role/set_bugowner against project.

osclib/comments.py
Users attempt both with and without seperators so might as well support.
Occurred in [request 727959](https://build.opensuse.org/request/show/727959) most recently.
=> osclib/comments: command_find(): allow seperators after user.

osclib/request_splitter.py
```
Without this, python 3 execution will fail with:
TypeError: Unicode-objects must be encoded before hashing
The requests strategy is the only strategy to utilize kwargs besides
custom so this code is not executed often which is why this has not been
encountered. In fact it was executed mistakenly and reported.
```
Fixes #2206.
=> osclib/request_splitter: utilize osclib.util.sha1_short() for encoding.

check_source.py
- 4e4379a4d563bfc179359d4d68b3aeda55db4969:
check_source: check_action_delete_repository(): simplify decline message.
- a7cf9026dbf2ae8640829266015299233d3c395a:
check_source: check_action_delete_repository(): gate behind conf.mail-release-list.
Works for SLE and maintenance properly with this option.
Noticed while skimming to respond to maintenance inquiry related to utilizing on IBS so figured best to generalize it.
=> check_source: check_action_delete_repository(): gate behind conf.mail-release-list.

check_source.py
We need to use user supplied REs to check this and this is a potential
DoS. This also fixes false positives for entries that start with
addFilter(".*
This fixes #2193
=> check_source: move checking of bad rpmlint entries to subprocess.

config/manager_42/README.txt, config/manager_42/openSUSE:Backports:SLE-15-SP1.yml, gocd/checkers.opensuse.gocd.yaml
Leave a README file in config/manager_42 to preserve directory until ready
to remove leaper/manager_42 stack.
[openSUSE:Backports:SLE-15-SP1](https://build.opensuse.org/project/show/openSUSE:Backports:SLE-15-SP1) is locked so no point in running the job. Not yet ready to nuke the stack (which I will do when appropriate) so just leave note and preserve directory for packaging.
=> gocd: remove PackageHub15SP1.Manager42 as project is locked.

osc-origin.py, osclib/origin_listener.py
=> osclib/origin_listener: utilize apiurl as thread name for remote listener.

osclib/origin_listener.py
Not only are patchinfo packages never useful for origin updates, but they
cause an exception since the package is set to an empty string.
Made infinitely easier with detailed stack including context variables not passed through to next function.
=> osclib/origin_listener: skip patchinfo packages.

osclib/core.py
Current code causes an exception (seen by sentry) and does not properly work with non-default apiurl. Current code was a workaround for lack of proper function in osc.core so a pseduo function of what should be there is provided.
=> osclib/core: request_create_delete(): utilize pusedo osc.core function.

ReviewBot.py
This can occur when the review state is changed during the review.
Discovered via sentry.
=> ReviewBot: _set_review(): handle review being revoked or superseded.

gocd/monitors.gocd.yaml
Would seem like this should be the default on all monitors since they run with same base class that spits out the still alive message (specifically for gocd). Will at least insure that a stuck state does not last a long time.
Related to #2220
=> gocd/monitors: *.OriginManagerUpdate: set timeout to 10 minutes.

osclib/cache.py, osclib/util.py
Resolves #1326 which causes intermittent errors on Tortuga.
=> osclib/cache: utilize rmtree_nfs_safe().

osclib/stagingapi.py
Should resolve long run time of rebuild command when large logs are involved.
=> osclib/stagingapi: rebuild_check(): utilize -4096 offset for build log.

check_source.py, origin-manager.py, osclib/core.py
- 160225b5e983057381f92a973054cf67219bac37:
origin-manager: skip package of type not (None or source).
Should skip review of meta packages and such. Although same logic would
seem to apply to deletes origin-manager is used to enforce manual review
of all deletes and as such even deleting of a meta package should be
included.
- afd288b87d946df3464c4037b50eea41653ecec3:
check_source: decline package of kind not (meta or source).
- 91aeaf1f55fd58bee0e0a1454c0a114fe9297a5e:
check_source: replace meta check with package_kind() == meta.
- f63da476c21719a8634b7ab4427182ef68419f13:
osclib/core: package_kind(): include underscore as meta prefix.
Previously used by _product which is still used in SLE-12.
Fixes #2229.
An active example:
```
$ ./origin-manager.py --dry --debug id 732664
[I] checking …
```
=> origin-manager: skip package of type not (None or source) and similar for check_source.

check_source.py
The benefit of this check is unclear to me. It enforces the Name tag
inside he kiwi file to be the same as the package name in OBS while the
kiwi file name itself can be arbitrary.
So that means that kiwi package names end up encoding their distribution
and version (eg "openSUSE-Leap-15.2-Vagrant") and have to be renamed for
each release. Also means diffing between released versions isn't as
straight forward as it could be if the name was more flexibel.
If we wanted to enforce something then we should make sure the actual
kiwi file name is the same as the OBS package name. That is what the
spec file name check actually does after all (package hello needs to
have hello.spec ie srpm name hello).
=> check_source: don't enforce name for kiwi images

check_source.py
if package_kind() returned None then the submission can be a new package submission, check_source should continue the process instead of decline the request.
local run:
[I] checking 733090
[I] devel:tools:compiler/llvm9@1 -> openSUSE:Factory/llvm9
[I] checking if target package exists and has devel project
[I] target package does not exist openSUSE:Factory/llvm9
[I] POST https://api.opensuse.org/request/733090?cmd=addreview&by_group=opensuse-review-team
[I] 733090 accepted: Check script succeeded
[D] 733090 review not changed
fixes https://build.opensuse.org/request/show/733090 , it has been declined by bot without a verbose reason.
=> check_source: when kind is None then it can be a new package

gocd/checkers.opensuse.gocd.yaml, gocd/checkers.suse.gocd.yaml, gocd/checkers.suse.gocd.yaml.erb
With the lack of events from OBS for SLE updates #2239 and the troubles
with the pika base class for IBS #2220 it seems best to keep the full
run daily to ensure expedient updates.
=> gocd/checkers: revert Origin.Manager.Update frequency back to daily.

ReviewBot.py, origin-manager.py
- 4c31f7754d711fb8dfc941d307308a1be05b43ca:
origin-manager: utilize ReviewBot.request_age_wait().
Configure a default of 30 minutes to work well with staging-bot quick
strategy.
- 7033044469fc478e97c676041b455dbed85af4c2:
ReviewBot: provide request_age_wait().
Provides configurable default, config key, and config override value.
Works best as callable method rather than built-in behavior since bots may desire more complex behavior such as origin-manager only on source submissions (not deletes) and after static checks are completed.
An example with local config:
```
[openSUSE:Leap:15.2]
originmanager-request-age-min = 18000
```
```
$ ./origin-manager.py --dry --debug id 733210
[I] checking 733210
[I] skipping 733210 of age 10593.94s since it is younger than 18000s
[I] 733210 ignored
``` …
=> origin-manager: provide and utilize ReviewBot.request_age_wait().

osclib/core.py, osclib/origin.py
- 0b34e1629bc688d0fe4008239bc2ec9947af749f:
osclib/origin: origin_annotation_load(): only return dict annotation.
To improve robustness and handle invalid/corrupt data in the annotation
just return None if it is anything other than a dict after parsing. The
most likely occurrence is someone accepts the origin-manager review with
a plain-text message.
- bc0ec5c6c9247fbb42efff2913dab28d346ae4dd:
osclib/origin: origin_annotation_load(): only consider accepted reviews.
This excludes reviews that were added and never reviewed possibly because
the request was rejected before the review could be accepted. In such
cases the comment specified when adding the review will be loaded as the
annotation which is not desirable.
- cc03a3561775fcfdfc7b05f5aced0556ff2dbe0f:
osclib/core: review_find_last(): …
=> osclib/origin: origin_annotation_load(): improve robustness by tolerating invalid data.

osclib/origin_listener.py
In theory fixes the problem of not picking up SLE events as it is claimed they generate `.commit` events while not generating `.update` events (unlike all other packages). In theory no harm from this (although I remember debating between the two events and feel like there was a reason for sticking to update).
Fixes #2239.
=> osclib/origin_listener: change from package.update to package.commit event.

gocd/checkers.opensuse.gocd.yaml, gocd/checkers.suse.gocd.yaml, gocd/checkers.suse.gocd.yaml.erb, gocd/monitors.gocd.yaml, gocd/staging-bot-reminder.gocd.yaml, gocd/staging.bot.gocd.yaml, gocd/staging.bot.gocd.yaml.erb
We start most jobs with --debug to generate output, but we had the case that OBS network caused the connection to just get stuck and then it 'paused' for 18 hours
=> Kill review bots if they didn't output anything for 30 minutes

gocd/pkglistgen_staging.gocd.yaml, gocd/pkglistgen_staging.gocd.yaml.erb, gocd/sle15sp2-stagings.gocd.yaml, gocd/sle15sp2-stagings.gocd.yaml.erb
If installcheck or packagelists check fails, there is no point (normally) to build the media - so let the release manager disable the images repo (which also hides uninteresting fails) while the checks are failing and have gocd enable the images repo afterwards to start the build (and the openqa sync)
=> Enable images repo once 000product was updated

issue-diff.py, osc-staging.py
Otherwise, all write calls complain about passing a string instead of
binary data. Given the yaml dump and subsequent comments are all strings
it makes more sense to change file mode.
Resolve issue reported in IRC by @lnussel.
=> osc-staging,issue-diff: open temporary file in write without binary mode.

pkglistgen/tool.py
Since the data is from project attribute, pkglistgen should not parsing a string.
This change also renamed pkglistgen-local to pkglistgen-locale.
=> pkglistgen: fix wrong parsing way on pkglistgen-locale

build-fail-reminder.py
In 6f21ae6 we fixed an inversion of to and fullname fields - but the
recipient was not fixed up here (resulting in addressing the user
by his email address)
Also fix a typo: recepient -> recipient
=> build-fail-notification: Fix how we address the user

suppkg_rebuild.py
Compares bytes and string in Python is different, make both are strings before comparing. This fixes suppkg_rebuild mess up commit history on dashboard.
=> suppkg_rebuild: decode bytes before comparing

userscript/origin.user.js
Otherwise, conflicts with OBS jquery version and plugins.
Verified on [package that is unresolvable in the target project](https://build.suse.de/package/show/SUSE:SLE-15-SP2:GA/drbd) where valid origin lookup can be observed to still work.
Fixes #2261.
=> userscript/origin: run in no-conflict mode.

check_source.py, osclib/core.py
The check for bcntsynctag can be very misleading - just because we align the build counters between 2 packages doesn't make them invalid submission targets. Better rely on the link check which is already implemented as fallback
And set a verbose decline reason for this case
=> Fix check_source on public cloud images

ReviewBot.py, dist/ci/flake-extra, origin-manager.py, osclib/cache.py, osclib/comments.py, osclib/core.py, osclib/origin.py, osclib/origin_listener.py, tests/OBSLocal.py, tests/devel_project_tests.py, tests/origin_tests.py
- 55fe5fecf5a32ae6641840f383c4c68c93bef948:
tests/origin_tests: provide split product origin tests.
- 0e0d53f06afd35eb2e125af24f41683fbb62f18c:
tests/origin_tests: provide devel origin tests.
- 1ba38741e02eb0650ca682afadfe91e8df7ab27e:
tests/origin_tests: provide harness and basic tests.
- 816ddac3869c64d0577597c4739d095831ca4ede:
tests/OBSLocal: provide randomString() for ensuring tools not name dependent.
- 68352c72a2f8c2b34533700abb6c0584742bbcda:
tests/OBSLocal: provide assertReviewBot() for review script workflows.
- e821cee8ec87c07aa9ad5101522be9cae9d0e6ed:
tests/OBSLocal: submit_package(): provide optional project argument.
Generating submit requests beyond only against the target project is
important during testing.
- 227df6aad7efc5330187864831c48cdcac816dab:
tests/OBSLocal: …
=> origin-manager: full handling of various devel project workflows, addition of significant tests, and many underlying fixes

pkglistgen/group.py, pkglistgen/tool.py
We ignored conflicts/obsoletes during pool preparation as it got into the way of finding supplements (due to conflicting packages in the list). But this way, conflicts were invisible also during dependency
search, leading to wrong packages picked for the package lists in general.
So add a flag to prepare_pool to explain if we want conflicts or not
=> Fix conflicts/obsoletes while picking dependencies

origin-manager.py
In the case of a devel project for an origin package add the review
against the devel project.
=> origin-manager: origin_maintainer_review_ensure(): check for devel meta.

osclib/core.py, osclib/origin.py
- 8cdd505beabba174a60b756e0af93615202f7330:
osclib/origin: origin_update_pending() utilize project_remote_prefixed().
Correctly prefix the remote project with the interconnect when creating
a submit request.
- fd94254601d8336779acf64193e6a94bef390058:
osclib/core: provide project_remote_prefixed().
Fixes submission of pending updates from a remote origin. Meaning SLE can submit pending Factory updates if the switch is enabled.
=> osclib/origin: origin_update_pending() utilize project_remote_prefixed().

web/origin-manager/main.js
Otherwise, packages that are frequently updated (such as openSUSE-release-tools) overflow the page with so many request entries.
=> web/origin-manager: paginate request history.

osclib/core.py
When releasename does not differ it is essentially the same as no
releasename at all, but since OBS allows this and some source packages
contain such a value need to make check more specific.
Fixes #2294.
=> osclib/core: package_kind(): require releasename to differ from package for maintenance_update.

dist/ci/docker-compose-test.sh, dist/obs/OSRT:OriginUpdateDelay.xml, dist/obs/OSRT:OriginUpdateFrequency.xml, dist/obs/OSRT:OriginUpdateSupersede.xml, osclib/core.py, osclib/origin.py, tests/OBSLocal.py, tests/origin_tests.py
- ba103f3609f8b56583f721bd156763678f5ef1ec:
osclib/origin: provide automatic update mode controls.
- 35dab9824a1067ba6962e167968689cfda194ecb:
osclib/core: request_create_submit(): provide frequency option.
- 5087480d7bff406244e8d09a951e028d19238e72:
osclib/core: request_create_submit(): provide supersede flag.
- fbeccb34ecbeecbf68612ee2aea92c3cb19cbb88:
osclib/core: request_action_simple_list(): include full history.
Without this the requests are not nearly as useful when processing.
- 6bdd1a014d122e4eaa90e1c923f0f234b327ae8c:
osclib/core: provide package_source_{changed,age}() functions.
- 34e21ad23034416aece231d09b0f1088c7ff856f:
osclib/core: provide attribute_value_delete().
- b894ceae509461bf82c83bde39155d52aa974894:
osclib/core: support package in attribute_value_{load,save}() …
=> osclib/origin: provide automatic update mode controls.

origin-manager.py, tests/origin_tests.py
=> origin-manager: indicate the decision may be overridden via command.

osclib/origin.py
=> osclib/origin: origin_annotation_dump(): include pending information.

osclib/origin.py
Otherwise, requests that are declined quickly (likely by bot) are not
shown in history which can be confusing when viewing in web interface. A
package may show as being one revision behind and one would wonder why
not update request when in fact a request could have been made and
declined.
Fixes #2245.
=> osclib/origin: origin_history(): include non-annotated requests.

dist/obs/attribute-update
Utilized to deploy the new origin manager attributes to both OBS and IBS.
=> dist/obs/attribute-update: provide script for updating attribute definitions.

osc-staging.py, osclib/request_splitter.py, osclib/stagingapi.py
This leads to staging-bot preferring none strategy for all and this is a problem,
so this is WIP
=> Disable splitter info until we find a better place to store it

osclib/stagingapi.py
Changing to backlog API is way too complex for the gain, so just keep
calculating it in the client
=> Simplify request list calculation

osclib/stagingapi.py
If the request is from the same project then just supersedes the old ones. The request is from the different project then put it to excluded list as the right behavior for Leap.
=> stagingapi: Supersedes request is from the same project

osclib/repochecks.py
The provides/requires can contain utf8 coding errors, as installcheck
is not actually producing utf8 encoded output but simply prints literal
bytes.
=> Gracefully handle utf8 errors in installcheck

project-installcheck.py
osc's http_POST unfortunately hard codes parameters in URL, so I had
to use the underlying function
Fixes #2351
=> Pass the packages to rebuild in the POST's body

osclib/accept_command.py
This removes the 2nd line of defense, but there is no API to accept multiple
stagings at once to avoid the underlying problem.
Fixes #2364
=> Always force accept into the API after checking for acceptable ourselves

gocd/rabbit-openqa.py
openqa will keep polling the repository for ready to sync, waiting
for published event is a problem for ToTest repositories that aren't
published. openqa will start syncing when it becomes 'unpublished'
CC @andrii-suse
=> Notify the obs_rsync plugin already when the scheduler is finished

config/announcer/openSUSE:Leap:15.2.yml
* Lubos Kocman is Release Manager for Leap since 1.1.2020
=> Update Announcer for Leap 15.2

osclib/accept_command.py, tests/accept_tests.py
In the past, we had a dashboard reading the version of the current source from the .product file.
Not immediately updating this version after a checkin would have been confusing as the dashboard would
have shown incorrect/outdated information.
the new dashboard (https://factory-dashboard.opensuse.org) reads the source version directly from the
attribute, so this mis-match is eliminated.
The .product files will be updated by pkglistgen in due time.
=> Staging accept: No longer set the version in .product files on accept

dashboard/generate.py, dashboard/templates/dashboard.html
=> Dashboard:fix openQA links

gocd/sp2.target.gocd.yaml
Images added: SLES15-SP2-BYOS SLES15-SP2-HPC-BYOS SLES15-SP2-SAP
SLES15-SP2-SAP-BYOS SLES15-SP2-SAP-Azure-VLI-BYOS SLES15-SP2-Azure-HPC
=> Added new images in 15-SP2 release tool config

ttm/releaser.py
It takes a long time to sync the repos but ISOs are very quick. This lead
to the problem that openQA already started syncing the build while the
repo was synced up. As the repository is set to unpublished in between
the calls, openQA has no chance to see that more is to come.
So if we release the slow products first, openqa has a better chance to
catch up.
=> Release FTP repos before ISOs

ttm/publisher.py
Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2402
=> ttm: ignore parallel_failed jobs, but still list as failed

osclib/repochecks.py, project-installcheck.py
`openSUSE:Factory/snapshot` now points to `openSUSE:Tumbleweed/standard`, which is a download-on-demand repo. This leads to project-installcheck.py failing like this:
```
INFO:InstallChecker:mirroring openSUSE:Tumbleweed/standard/i586
400 remote error: will not get all dod packages
```
`/usr/bin/installcheck` can deal with `primary.xml.gz` files just fine though, so just download those as well.
=> Support DoD repos in project-installcheck

gocd/sp2.target.gocd.yaml
As image names have a pattern in 15-SP2 (SLE*), change the script that
release to TEST to use this image name pattern instead of list all
images.This will avoid frequently updates in script cause by new image
package submissions.
=> Make images release to TEST generic

osclib/stagingapi.py
A common workflow is:
* pkg is being marked for deletion by repo-checker [botdel]
* User comes to the rescue and fixes the package, Submits the fix
* Commonly, the delreq is being declined (by factory-maintainer)
* factory-auto declines SR, as pkg now has a delreq and subreq pending
* factory-auto does not consider the 'declined' request as replacable
and complains that it should be revoked (or superseded). Since the
del req was created by repo-checker, 'nobody' has the credentials to
revoke the request. The user, not having a role in the old SR, has
no permission to supersede
So let's just accept a delete request in statet 'declined' as something
that can be replaced by a submit request for the same package.
=> Replace declined requests

ttm/releaser.py, ttm/totest.py
Currently if set_snapshot_number is true, it uses "Snapshot" as prefix.
In some cases it's necessary to use a different one. This can now be configured
using the "snapshot_number_prefix" option.
Currently needed for 15.2 Images, which do not have a special publish script anymore, so plain `Repotype: staticlinks` has to work, which requires the `BuildX.Y` pattern.
=> Allow overriding the prefix for setrelease

gocd/rabbit-openqa.py, gocd/rabbit-repoid.py, tests/fixtures/staging-meta-for-bootstrap-copy.xml
As the rabbitmq heartbeart interval is a hard limit, we need to make sure
we're not overloading the time in between
=> Split the work done in rabbit-openqa into smaller chunks

gocd/monitors.gocd.yaml, gocd/rabbit-openqa.py
Rely on rabbit-repoid git instead - only the first step
=> No longer trigger obsrsync directly from rabbitmq messages

gocd/notify-obs_rsync.py
As long as we don't know what's configured on openqa (the API is WIP),
we rely on existing data
=> Take the interesting repos from the output for now

osclib/stagingapi.py, osclib/supersede_command.py, osclib/unselect_command.py, tests/OBSLocal.py, tests/api_tests.py, tests/select_tests.py
Instead of declining the by_project review, unselect the request and
decline the group review. This way we avoid the OBS problem
=> Work around OBS issue 8994

staging-installcheck.py
SLE service packs are just too complex to check delete requests sanely,
so better disable it. For next SLE we would enable it though
Fixes #2221 and ##2282
=> Allow to disable the check of delete requests per config

osclib/stagingapi.py
* Allow multibuild package spreads across ring
* Remove dead code
* Do not add multibuild flavor package to the ring package list(frozenlinks)
Perfectly we should verify `excludebuild` macro on each ring, I'd take it as enhancement task for the future, for the current requirement this change should works well enough.
Fix https://github.com/openSUSE/openSUSE-release-tools/issues/2428
=> allow multibuild package spreads across ring

dist/package/openSUSE-release-tools.spec
The entire codebase has moved to python3; pulling in this one python2 package makese no sense.
The guard with %if %{without python3} does not work as intended, as there is no %bcond_without statement
in the .spec file, thus assuming 'without' unless overriden by any other rules.
=> dist: drop bogus python-enum34 dependency

project-installcheck.py
Fix crash of the run added by https://github.com/openSUSE/openSUSE-release-tools/pull/2438
=> Fix crash in project-installcheck if there are no packages in the pra

legal-auto.py
this avoids lingering legal reviews of _channel like we see for kernel and livepatch submissions
(tag: business continuity 
tag: reduce marcus knowledge
)
=> ignore packages that just have _channel inside

osclib/core.py, tests/origin_tests.py
The algorithm was wrong, it didn't add non-recursively entered paths to the
list. The correct algorithm even allows for a simpler implementation.
This causes false negatives (or even positives) during installcheck, especially impacting the rebuild triggers against `openSUSE:Tumbleweed/standard`, which was omitted due to the bug and so glibc was missing.
=> Fix osc.core.repository_path_expand

osclib/stagingapi.py
When self.cstaging is the empty string the first char is cut off. Fix
this by testing for that case.
=> fix cutting off part of a stagings name

metrics/grafana/access.json, metrics/grafana/provisioning/datasources.yaml
Not sure if there are further changes necessary, e.g. internal changes
to influxdb or whatever data source should provide the data.
=> metrics/grafana/openqa: Add openSUSE Leap 15.1 and 15.2

osclib/conf.py
Packages submitted to openSUSE:*:NonFree did not end up on the queue
of the opensuse-review-team
=> factory-auto: add opensuse-review-team on submits to NonFree

legal-auto.py
isc api /source/home:osalvador:branches:Devel:Kernel:SLE12-SP2-LTSS:Submit/?view=info
shows
<sourceinfo package="SLE-SERVER_12-SP2-LTSS_x86_64" rev="3" vrev="113" srcmd5="8b9a4eef8f161a41c96b89c7163091a9" lsrcmd5="55f550c22886d610c2e386c727f30817" verifymd5="66e022e70e6e94f85f494918960fc0cb">
<error>bad build configuration, no build type defined or detected</error>
<linked project="SUSE:Channels" package="SLE-SERVER_12-SP2-LTSS_x86_64"/>
</sourceinfo>
=> skip SUSE:Channel files harder

ttm/releaser.py
`openSUSE:Factory:ARM`'s ttm config has
```
JeOS:
- armv7hl
```
and doesn't mention any of the multibuild flavors to avoid the build success check.
Adding the missing arches to the multibuild container would cause the build check to fail as plain `JeOS` only builds for `armv7hl`.
=> TTM: Ignore arch check for multibuild containers

dashboard/generate.py, dashboard/templates/repository.html
to avoid to display 'done' with few jobs remaining.
=> Dashboard: be more precise in percentage

gocd/rabbit-repoid.py
AMQP Server on practice sometimes closes connection when update_repo() is busy in gocd/rabbit-repoid.py.
Doing the same work just in still_alive() seems be sufficient and fixes the same problem in local environment.
=> Fix MQ timeouts in rabbit-repoid

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb
Leap 15.2 MicroOS is still ongoing, add pkglsitgen service for Leap 15.2 MicroOS back, this change also renamed old Leap pipeline to Jump.
=> pkglistgen: add Leap 15.2 MicroOS back to pipeline

metrics/access/aggregate.php
This change allows aggregating download statistics for Leap 15.2.
Partially fixes: https://progress.opensuse.org/issues/69376
=> metrics: Update product pattern to match Leap 15.2

gocd/sp3.target.gocd.yaml
Untested, because not easily possible...
Marking as draft because merging needs to be done at an appropriate time
=> Release and publish SUSE:SLE-15-SP3:Update:CR/sles15-image as well

metrics.py
sys.maxint has been removed in Python 3.1.
https://docs.python.org/3.1/whatsnew/3.0.html#integers
=> Migrate metrics scripts to Python 3

check_source.pl
With osc 0.171, the service execution engine was changed to explicitly
only start the services in a specific mode (i.e. runlocal only runs services
with mode="local").
On openSUSE:Factory, the _service definition though contains mode="disabled" for service download_files
This in turn leads to confusion as to how to get the files downloaded locally.
The 'service runall $FOO' variant runs the specified service no matter what mode it is declared
Helps clarify for https://github.com/openSUSE/osc/issues/874
=> check_source: Advertise the usage of 'osc service runall $FOO'

check_source.pl
It's actually fine to have a single .changes file for multiple .spec files
in the same package, OBS picks that automatically. Relax the check to only
require a single .changes file for the package name.
Many multi-spec packages currently just duplicate the changes files anyway,
which can be avoided.
=> check_source.pl: One .changes file per package is enough

staging-installcheck.py
For openSUSE:Factory:Staging:adi:*, i586 is only enabled when necessary and so
the check is not set as required. Currently x86_64 is handled first (due to
target_archs), which means that for oS:F, i586 comes last and so the ugly hack
results in x86_64 getting a fake success and the actual status is set for i586
only, which gets ignored.
=> Fix staging-installcheck.py being ignored if i586 is present

osclib/stagingapi.py
Otherwise the newly added archs don't have any required checks assigned.
Seems to work: https://build.opensuse.org/staging_workflows/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:adi:29
=> Also add required checks to adi stagings after adding architectures

pkglistgen/group.py, pkglistgen/tool.py
For Factory we want the DVD to catch all (and only require some), but the
smaller products kubic and microos should have a require all policy
=> pkglistgen: Allow to set require_all for some groups to disable ignore

osclib/accept_command.py
If a change_devel request is grouped into a staging, it shouldn't crash
on it - the API will accept it, and we have no specific action for this
type
Fixes #2381
=> Accept: Don't crash on actions that aren't submit/delete

pkglistgen/tool.py
mozjs is now i686 exclusive and GNOME and KDE depends on it
=> Calculate the i586 DVD as i686 package set

abichecker/abichecker-web.py, abichecker/abichecker_common.py, abichecker/abichecker_dbmodel.py, biarchtool.py, deptool.py, dist/ci/osc-credentials, obs_clone.py, status.py, sync-rebuild.py, unmaintained.py, update_crawler.py
With the python shebang remaining as Python 2, switch the scripts to
using Python 3. This also allows us to clean up some imports.
=> Switch to python3 shebang

pkglistgen/tool.py
repository_arch_state doesn't raise HTTPError for 404 any more, but that's what
pkglistgen uses to skip that repo/arch. Handle None as replacement instead.
=> Fix repo state error handling in pkglistgen

osclib/adi_command.py, osclib/request_splitter.py
This is now acceptable as the installcheck bot verifies that we
cannot remove binaries we still care for.
Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2440
=> adi: stage Non-Ring delete requests in adi projects

findfileconflicts
When a filesystem package with usrmerge is detected (/bin, /sbin, /lib
or /lib64 link to /usr), pretend all files in the affected dirs are
actually in /usr.
=> findfileconflicts: handle usrmerge

pkglistgen/tool.py
If the packages are already part of the modules that are excluded
(due to dependencies), output an ERROR (which is not fatal atm)
Fixes #2541
=> pkglistgen: After solving check all packages listed

osclib/conf.py, pkglistgen/tool.py
Never use the bootstrap_copy repo for package solving. Staging content
might be very different so don't confuse the solver.
=> pkglistgen: ignore bootstrap_copy repo

osclib/conf.py, pkglistgen/tool.py
#2539 broke quite a bit, including blocking all Factory Ring 1 stagings, so I think it's best we just revert it now before revisiting whati t was trying to fix
=> Revert pkglistgen: ignore bootstrap_copy repo

gocd/microos-stagings.gocd.yaml, gocd/microos-stagings.gocd.yaml.erb, gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb, gocd/pkglistgen_staging.gocd.yaml.erb, gocd/sle15sp3-stagings.gocd.yaml, gocd/sle15sp3-stagings.gocd.yaml.erb, gocd/staging.bot.gocd.yaml, gocd/staging.bot.gocd.yaml.erb, gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb
- Drop Leap:15.1:Images and Leap:15.2:MicroOS
- Some .yaml files were changed manually, adjust the .erb source
- Delete some unnecessary/duplicate whitespace
=> gocd: Drop obsolete projects, fix whitespace

gocd/sp3.target.gocd.yaml
The new path is now used by QA and ~soon~ Autobuild.
=> Drop the old path for releasing SP3:GA/sles15-image

pkglistgen/tool.py
Otherwise the osc config for checkout_no_colon will interfer where the
files end up and then we can't open them reliable.
Fixes #2559
=> pkglistgen: Force outdir for the checkouts

check_source.py
Accepts https://build.opensuse.org/request/show/895535, but declines https://build.opensuse.org/request/show/867727.
=> check_source.py: Decline if source_revision not set

gocd/totestmanager.gocd.yaml, osclib/conf.py, tests/config_tests.py
We need this to run TTM against :images and properly determine the
pseudometa package.
=> Support Leap:15.3:ARM:Images as well

ttm/manager.py, ttm/publisher.py
Make `publish --force` really publish forcibly and fix version detection of `JeOS`
=> TTM fixes for 15.3:ARM:Images

.github/workflows/ci-test.yml, README.md
What is done in this pr:
- update badge in readme to reflect change to github actions
- move linter to own job to speed up a build for hopefully around 30 seconds
Also badge for codecov needs to update, but I do not have permissions to see proper link in settings.
=> Ci small tunning

README.md, dist/ci/docker-compose.yml
* Add a section to the README explaining how to use Docker Compose to run integration tests.
* Expose OBS port in the Docker Compose `api` service so it can replace the `./dist/ci/docker-compose-obs` script.
* Replace Coveralls badge with Codecov one (see [GitHub's action workflow definition](https://github.com/openSUSE/openSUSE-release-tools/blob/9c0e048aac399557c8aa0be725adec972629e670/.github/workflows/ci-test.yml#L26-L27)).
=> Document CI

.dockerignore, .flake8, .gitignore
As far as I can see, there is no longer any reason to exclude `openqa-maintenance.py` and `openqa` is not longer there.
=> Update exclude section in .flake8

osclib/conf.py
Otherwise they both try to write into the same pseudometa.
=> osclib/conf.py: Don't use same config for openSUSE:Leap:15.3:ARM and :Images

dist/ci/testenv-tumbleweed/Dockerfile
Add some missing packages that are needed to run `check_source.pl` as part of the tests introduced in #2591.
=> Add missing libraries to testenv image to run check_source.pl

data/apimap.json, data/incidents.json, data/repos.json
Progress ticket : https://progress.opensuse.org/issues/94810#change-423835
=> Rename DVD-Backports to DVD-Backports-Incidents

osclib/core.py, tests/check_source_tests.py, tests/fixtures/packages/blowfish/blowfish.changes, tests/fixtures/packages/blowfish/blowfish.spec
This PR includes:
- Some refactoring to reduce the redundancy with functionality already provided by the osc API (the functionality was covered with tests and they still pass).
- Initial tests for the check_source review bot (we wanted to have something before modifying that bot in the context of #2429)
=> Improvements and new test

README.md
The OBS instance alias is not created anymore. So let's explain how to do it.
=> Document how to create the osc alias for the local CI instance

dist/ci/testenv-tumbleweed/Dockerfile
The preparation is needed so no workaround is needed when validating
that all tests passed when switched from nosetests to pytest. Nosetests
will be removed as part of final switch change.
final pr: https://github.com/openSUSE/openSUSE-release-tools/pull/2595
=> Preparation for switch from nosetests to pytest

check_source.py, osclib/conf.py, osclib/core.py, tests/check_source_tests.py
* It introduces a new configuration parameter `required-source-maintainer`.
* If defined, it is expected to be a maintainer of the devel project.
* If that's not the case, the request is declined and an `add_role` request is created.
Fixes #2429
=> Check for maintainers in the source project

CONTENTS.md, README.md
Extends the information [in the original inventory](https://github.com/openSUSE/openSUSE-release-tools/wiki/Inventory) and creates a document explaining the contents of the repository.
Beware that it is still a draft a quite some information is missing (and most probably wrong). So, please, feel free to correct or add the missing bits.
Thanks!
=> Add an inventory

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb
Since Leap's ftp-tree takes more time to build, increase the timer for fire Leap updates repos every 3 days, otherwise a new change might trigger mediums rebuild then a rebuild counter sync following later.
=> gocd: increase the timer for fire Leap updaterepos every 3 days

docs/processes.md, tests/OBSLocal.py, tests/factory_submit_request_test.py, tests/fixtures/packages/wine/wine.changes, tests/fixtures/packages/wine/wine.spec
Every submission to Factory implies quite a journey through several reviews, staging projects, bots... That makes harder for newcomers to this repository to know what's the exact role of each tool.
The YaST Team is starting to help with the development and maintenance of these tools. In our experience, having a couple of descriptive test cases that serve as a reference for the common scenarios is a great way for newcomers to get a general overview and get up to speed quickly. Test cases as (living) documentation.
This pull request implements such an introductory test for the scenario in which a submit request is sent to a Factory package that is in the ring1. It also serves as a basic smoke test, to check if the different pieces keep working together.
See: …
=> Test to showcase a submit request to Factory

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb
Currently everything is broken due to this error.
```
INVALID MERGED CONFIGURATION
Number of errors: 1+
1. Invalid cron syntax: Support for specifying both a day-of-week AND a day-of-month parameter is not implemented.;; 
- For Config Repo: https://github.com/openSUSE/openSUSE-release-tools.git at 0316d3b0d30e8a6df4b9652a1004e2ce4ed37fc5
```
=> gocd: Fix timer specification for Update.Repos.Leap

dist/package/openSUSE-release-tools.spec, gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb, skippkg-finder.py
`NON_FTP_PACKAGES.group` maintaining a list of package(RPM) to be skipped in ftp-tree build, after CtLG, any binary built from SLE15 scope product including incidents from update has appeared in *pool* repository, there are many outdated and obsoleted binary still presented in case ftp-tree's build method is `wildcard(*)` - selecting anything does exist, therefore `skippkg-fidner` helps to find those *obsoleted* package from SLE, and since it will overwrite the skip-list entirely, `skippkg-finder` is handling *unneeded* SLE/openSUSE specific package also. This script should runs before `pkglistgen` since `pkglistgen` would parse `NON_FTP_PACKAGES.group` while creating ftp kiwi.
Related: https://github.com/openSUSE/openSUSE-release-process/issues/75 and …
=> skippkg-finder: overwrites NON_FTP_PACKAGES.group for obsoleted/unneeded package from SLE or openSUSE

tests/OBSLocal.py, tests/factory_submit_request_test.py
The *factory_submit_request_test* requires the attribute *ProducVersion* to exist. This is because accepting a submit request requires a *ProductVersion* to properly work. But the *factory_submit_request_test* does not fail even though it does not set a *ProductVersion* at all. This is because there are dependencies between tests.
The attributes like the *ProductVersion* are not deleted when a test finishes. So, *factory_submit_request_test* will work if a previous test creates a *ProductVersion* attribute. For example, if *accept_test* is executed before, then *factory_submit_tests* passes. Otherwise, it would fail.   
Always ensure that a *ProductVersion* attribute is created in order to make possible other actions like accepting a submit request. And clean up all the attributes when a …
=> Remove attributes in tests

dist/ci/miniobs/Dockerfile
https://build.opensuse.org/package/show/home:coolo:branches:openSUSE:Tools:Images/osrt-miniobs-for-ci - as of writing this is still waiting for obs to finish in OSU
=> miniobs: Use 15.3 repos - 15.1 is EOL

docs/processes.md
The document `processes.md` contained a quite big section (almost half of the document) explaining what the staging projects are and how they are used in Factory.
That information should not belong to that document. In fact, a big part of it was copied from [the page of the openSUSE wiki](https://en.opensuse.org/openSUSE:Factory_development_model) that was linked just some paragraphs before.
The information that was really original (the one regarding ADI projects) was added to the wiki page (see [this wiki edit](https://en.opensuse.org/index.php?title=openSUSE%3AFactory_development_model&type=revision&diff=159612&oldid=137272) and the original content of the section (although redundant) was copied as-is to [the osrt onboarding card](https://trello.com/c/UOYpyaNv/) used by the YaST Team. …
=> Remove redundant information from processes.md

pkglistgen/tool.py
In some cases we'd like to chose from all available repositories
for selecting the right package. in appliance builds and there
is an OBS-UseUnorderedRepos flag for enabling this behavior. Similarly
product-builds have a flag "use_newest_version" that can be set
to true. pkglistgen needs to know about these variant as well
to properly resolve package dependencies.
=> add option to use newest package for resolving dependencies

ToolBase.py
On botmaster we get reproducible connection timeouts with OBS. This can
be reproduced with plain curl loops and it's unclear where the packages
are dropped, so I see no other way than just keep GETing
=> Retry GETs if they catch a TimeoutError

devel-project.py
Workaround for https://bugs.python.org/issue16308
kocman@localhost:~/Workspace/opensuse/openSUSE-release-tools> python3 devel-project.py 
File "devel-project.py", line 300, in <module>
main()
File "devel-project.py", line 297, in main
sys.exit(args.func(args))
AttributeError: 'Namespace' object has no attribute 'func'
=> devel-project: "list" is the default command, Python 3.3 fix

metrics/access/aggregate.php, metrics/access/ingest.php
The logs before 2021-09-05 are not available anymore.
The change takes account of it and skips parsing older logs.
Additionally, the database is not dropped on every run.
=> Fix handling missing log files

metrics/telegraf/openqa.conf
Related progress issue: https://progress.opensuse.org/issues/102975
=> metrics: telegraf: Fix URL for openqa.opensuse.org after machines were moved to openSUSE internal network

gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb
Someone need to create the `ttmconfig` for `openSUSE:Leap:15.4:ARM` before merging.
=> Run TTM for openSUSE:Leap:15.4:ARM (armv7)

dashboard/templates/dashboard.html
=> Dashboard: do not display containerfile values for Leap

dist/package/openSUSE-release-tools.spec
otherwise /usr/bin/osrt-project-installcheck is a stale softlink
=> dist: include project-installcheck.py again

skippkg-finder.py
For the purpose of adding some package(RPM) to the skiplist, there are two option has introduced, skiplist_supplement_regex for adding package if it has matched with the regex, skiplist_supplement_ignores in order to free package from the regex rule.
A major purpose of this change is about drops off python2 base stuff from the ftp-tree, the first verification run has been done, the attribute has been updated for that, see OSRT:Config at https://build.opensuse.org/attribs/openSUSE:Leap:15.4
=> skippkg-finder: add a supplement list for adding package to the skiplist

factory-package-news/factory-package-news.py
Use an inequality check instead. That way if there's no full match (like
caused by https://github.com/openSUSE/obs-build/issues/768), it doesn't fall
back to printing the whole changelog.
=> factory-package-news.py: Don't rely on changelogtime equality

ttm/manager.py, ttm/releaser.py
Otherwise it might release a build which uses the wrong version.
=> Check whether the FTP trees contain OSRT:ProductVersion before releasing

osclib/stagingapi.py
Those repos have to build against :Staging as well to get the prjconf.
Tested with https://build.opensuse.org/package/show/openSUSE:Factory:Staging:adi:62/opensuse-memcached-image
=> Include :Staging in :adi images and containerfile repo paths

gocd/checkers.suse.gocd.yaml, gocd/checkers.suse.gocd.yaml.erb, gocd/staging.bot.gocd.yaml, gocd/staging.bot.gocd.yaml.erb, osc-staging.py, osclib/adi_command.py
It's pointless by now as we have no project that uses devel projects
and would accept submissions not coming from there
Fixes #1366 (kindof)
=> Remove --by-develproject for adi command

osclib/stagingapi.py
The staging status doesn't provide the by_project and it's not
really important here, so simplify
Before:
adi:39 review: None/ekiga for ekiga[955924]
After:
adi:39 review: package:ekiga for ekiga[955924]
=> Fix output of staging reviews

skippkg-finder.py
In case regex list has not been defined any value, the first element will be space only, this causes unconditional matched any binary name. Exit the for loop if the first element is space only.
=> skippkg_finder: fix unconditional matches if the first regex element is space

skippkg-finder.py
Since update project has different set up than GA project, it should check content from update project prior to GA when run this
script for Leap Respin.
verification run: https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.3:Update:Respin/000package-groups?opackage=000package-groups&oproject=openSUSE:Leap:15.3:Update:Respin&orev=33&rev=35&full_diff=true
=> skippkg-finder: use SLE update prior to GA for Respin

dist/obs/OSRT:FreezeTime.xml, osclib/core.py, osclib/freeze_command.py, osclib/stagingapi.py, tests/OBSLocal.py, tests/api_tests.py
The mtime of a file in OBS is the time this content was created for the first time. As such if the target project isn't moving for a week, staging select will keep asking you to freeze - even if you just froze.
So instead of relying on OBS to tell the true mtime, set an attribute in the staging project and read from it. This also gives a way to check in the webui for the last freeze time
Fixes #2462
=> Make frozenage less reliant on changing _frozenlinks

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb, osclib/conf.py, pkglistgen/cli.py
Within gocd we run each job on its own worker and don't rely on builtin loop. So no need to care for a remote config
=> pkglistgen: Deprecate scope 'all'

staging-installcheck.py
The installcheck did it's job, so exit 1 is just a wrong red flag on the
botmaster dashboard
=> staging-installcheck: Don't exit 1 if there is a problem found

gocd/notify-obs_rsync.py
These failures are healed automatically, so it's purely to avoid
extra mails for breaking pipelines
=> gocd: Fix rare failure to push to notifications repo

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb, pkglistgen/cli.py
As we deprecated 'all' we can just as well rely on only one project
given (which is also what we do in gocd) to ease error reporting.
The old method of running all projects in a loop stemed from the
old pkglistgen not having a scheduler so we relied on serial execution.
=> pkglistgen: Only solve one project at a time

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb
There is no reason to wait for the rest to build to generate release
packages, they don't depend on other packages
=> gocd: Create release packages as early as possible

osclib/conf.py
It's a little suprising fallout from 1870e989a4d7a1f846dc06895402dc1395b34c11,
but we don't have package lists in "rings" anymore, but only in one
ring.
=> Rename the pkglistgen config for ring1 as well

pkglistgen/tool.py
The regexps were supposed to match package names, but re.match does not what I thought it does - it only matches the start of the line not the end
=> Fix filtering of unneeded.yml

gocd/verify-repo-built-successful.py
This avoids pkglistgen running on empty stagings
=> gocd: Don't evaluate a repo as succeeded if all are disabled

gocd/pkglistgen_staging.gocd.yaml, gocd/pkglistgen_staging.gocd.yaml.erb, gocd/sle15sp4-stagings.gocd.yaml, gocd/sle15sp4-stagings.gocd.yaml.erb, osclib/accept_command.py
Following up from @DimStar77's https://github.com/openSUSE/openSUSE-release-tools/pull/2382
Building and testing staging products that aren't ready yet is wasteful and confusing.
=> Disable images repo on accepting stagings

check_source.py, osclib/core.py, staging-installcheck.py
It only works in a fraction of cases:
- it checks only %{name}-rpmlintrc while rpmlint supports more such file names
- it looks into the devel project's build log where we could see earlier or later builds
- it searches for repositories that build against openSUSE:Factory while most devel projects build against openSUSE:Tumbleweed, in which case the whole check is skipped
And on top of that: it duplicates what rpmlint-config-Factory-strict does in stagings - block security relevant rpmlint warnings.
=> Remove rpmlint.log parsing feature from factory-auto

check_source.py, tests/check_source_tests.py
The URLs might suffer from flaky networks, so just block the request
from accepted for now (and extend the review comment to make it
discoverable why factory-auto didn't approve)
Fixes #2666
=> Do not decline requests with download_files errors

project-installcheck.py, staging-installcheck.py
@DimStar77 wants to have unresolvable packages be part of the build fail reminder, but for that we need to store the first time we saw the unresolvable.
(I guess we could do the same also for failures and work around issues in the project status route)
=> project-installcheck: Store when we first saw unresolvable and failed results

osclib/stagingapi.py
This replaces #1304 with a more brute force approach to fix not only 32bit libs but all failures we see on i586. We waste so much energy retrying failed builds, it's really not worth it not trying i586 on adi.
=> Force i586 in adi projects

build-fail-reminder.py
@dirkmueller rightfully complained that "fix the build" is misleading if the package is uninstallable. This is the best I can come up with
=> Make the build fail reminder email text more generic

project-installcheck.py
=> project-installcheck: Take 'excluded' as gone package

metrics/access/aggregate.php
The purpose is to drop the last measurement on uncompleted aggregation
period.
=> Recreate the database on each run

dist/ci/testenv-tumbleweed/Dockerfile, dist/package/openSUSE-release-tools.spec
The bridge is required for git-managed sources being submitted
to Factory in order to check out the code
Fixes issue #2820
=> package: require git-scm-bridge by osrt-check-source

gocd/rabbit-openqa.py
https://botmaster.suse.de/go/pipeline/activity/SUSE.openQA is crashing for about 2 months now :(
=> rabbit-openqa: If OSRT:OpenQAMapping contains garbage, just continue

osclib/cache.py
osc master no longer wraps urlopen, so use the underlying function
=> Fix cache handling with osc from git master

project-installcheck.py
While the project is building, the unresolvables may be temporarily but
more important packages that failed before, can become blocked and then
fail again. But we don't want to remove it from 'failed' because it had
an interim state of blocked
Fixes #2838
=> project-installcheck: Don't record unresolvables/fails during building

Makefile, dist/package/openSUSE-release-tools.spec
Otherwise all other PRs fail with a build error on the spec.
=> install and link publish_dist

dist/package/openSUSE-release-tools.spec
Fixing packaging the source for the link was missed in the last commit.
Blocks https://progress.opensuse.org/issues/115667
=> publish_distro: Provide missing link target in %files

data/incidents.json
Motivation: [[qe-core] Increase the coverage of test scenarios in Leap Maintainance - Proposal for tests from SLES to be added to leap](https://progress.opensuse.org/issues/113297)
=> Trigger aarch64 updates jobs

legal-auto.py
This API endpoint is currently accepting the GET and POST methods, but the POST method will be deprecated soon. After looking at the logs from build.opensuse.org, I noticed that the `licensedigger` user is heavily relying on this endpoint with the POST method. Using the GET method is also fine as noted by the W3C in [URIs, Addressability, and the use of HTTP GET and POST](https://www.w3.org/2001/tag/doc/whenToUseGet-20030922#ephemeral), under the section _5.2 Ephemeral Limitations_:
> **URIs cannot be longer than 256 characters**
> This was a limitation in some server implementations, and while
servers continue to have limitations to prevent denial-of-service
attacks, they are generally at least 4000 characters, and they evolve as
the legitimate uses of application developers evolve. …
=> Use HTTP GET for /search/request/id API endpoint

gocd/checkers.suse.gocd.yaml, gocd/checkers.suse.gocd.yaml.erb
This prevents the short-living checkers from not making any progress
due to an endless hanging job
=> Set timeout on the suse checkers

dist/package/openSUSE-release-tools.spec
* non of the mirrorbrain is used any more
* sections using mb are already disabled
=> Remove publish_distro dependency on python-mb

git-importer.py
This affects 62 packages (example vte accepting request 81553)
The conflict is real as O:F revision 52 ran "autobuild autoformatter", which wasn't merged in devel project and then vte2.spec was removed on submitting 81553, which lead to a conflict. But the code passed "CONFLICT" as merge commit if the 2nd call to .merge didn't resolve
=> Handle Conflicts removing files

git-importer.py
In unitest-cpp is a revision where the devel project got broken, so the MERGE conflict has no input for .changes - so the conflicts[1] is empty
("The first is the common ancestor, the second is the “ours” side of the conflict,
and the third is the “theirs” side. These elements may be None depending on which
sides exist for the particular conflict.)
See https://build.opensuse.org/request/show/999689 for the commit that restores the devel project and being puzzled
=> Fix CONFLICT logging

data/repos.json
'kde' test isnt defined on Leap 15.4 pipeline
=> Check 'textmode' test on 15.4

osclib/accept_command.py, osclib/stagingapi.py
Otherwise we don't notice test suites failing that were split out
=> Fix the syncing of rebuild failures for multibuild flavors

docs/pkglistgen.md, osclib/core.py, osclib/pkglistgen_comments.py, osclib/stagingapi.py, pkglistgen/cli.py, pkglistgen/tool.py
This PR does two things:
- Add typing hints and docstrings to some of the functionality of this repository
- Fix typos in the documentation
=> Add typing hints

.gitignore, osclib/core.py, osclib/pkglistgen_comments.py
This PR has the aim to achieve to submit the changelog to a devel project of the 000package-groups package.
The reasoning behind this effort is that with [SLSA](https://slsa.dev/) the release manager has no write access to the GA image anymore. During a osc staging accept the changes should be saved though. To preserve the functionality that was lost with complying to SLSA this PR was created.
=> Submit summary to devel

gocd/rabbit-openqa.py
* gocd/rabbit-openqa.py: Remove unused parameters
* gocd/rabbit-openqa.py: Add --dry option
* gocd/rabbit-openqa.py: Ignore jobs in "Development" groups
The latter fixes the current crash caused by name conflicts between production and dev jobs (for images).
=> gocd/rabbit-openqa.py improvements, including fix for current crash

gocd/rabbit-openqa.py
In addition to looking for tests using *.iso files also consider .qcow2
and .raw.xz files for matching HDD_1.
To avoid accidentally looking for tests using files for which the openQA mapping doesn't work, those are ignored now.
=> gocd/rabbit-openqa.py: Also try to match disk images (#2888)

gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb
Leap 15.4 for arm 32bit is never frozen, so we do need to continuously be able to release new snapshots.
=> readd ToTest 15.4_ARM manager

gocd/rabbit-openqa.py
When including images in staging checks we get conflicting names as we have e.g. `microos@uefi-staging` for both `Staging-DVD` and `MicroOS-Image-ContainerHost`.
=> gocd/rabbit-openqa.py: Always include flavor, name and machine in the check

metrics/access/ingest.php
The format of access log messages has changed on 2022-12-23.
Fixes https://progress.opensuse.org/issues/123133
=> Fix regex for access logs parsing

check_maintenance_incidents.py, check_tags_in_requests.py, devel-project.py, dist/ci/docker-compose.yml, metrics.py, osclib/core.py, tests/OBSLocal.py
Starting with the minimal changes from #2879 again
=> Fixes for osc-1.x

osc-staging.py
we should only expand with openSUSE in front if it is starting with "Factory". Also add ALP handling and hide the warning if a full project has been specified.
=> Allow specifying a devel project that has "Factory" in its name

gocd/sp.target.gocd.yaml
This PR should add two things:
- The new tool IBS to Jira should be executed optionally
- The new release automation from the autobuild team should be utilized for self-service product releases
This is my first bigger PR with gocd, so I would appreciate a thorough review.
=> Add new SLE automations

dist/ci/testenv-tumbleweed/Dockerfile, requirements.txt, tests/accept_tests.py, tests/check_tests.py, tests/factory_submit_request_tests.py, tests/select_tests.py, tests/sle_submit_request_tests.py
python3-mock no longer exists, use unittest.mock instead.
I just search-replaced, let's see.
=> Port from mock to unittest.mock

check_source.py
These have special name handling in `_preinstallimage`. The package name has to be "preinstallimage-$name" where $name is what is given in the _preinstallimage description
=> Fix handling of preinstall images

osclib/cleanup_rings.py, osclib/core.py
Previously it went through each package's provides->required_by chain.
This does not deal with cycles correctly and there was only a hack to deal
with single-package cycles.
Instead, recursively walk through all required packages, starting from the
build enabled images and take note of all needed source packages.
This also handles _multibuild flavors as separate packages.
Depends on #2944.
=> Rewrite cleanup_rings.py

osclib/cleanup_rings.py
Work around OBS not listing file deps in fileinfo_ext: https://github.com/openSUSE/open-build-service/issues/14129
=> cleanup_rings.py: Add snobol4 to whitelist

.obs/workflows.yml
The package needs to have the obs_scm service enabled to fetch the right sources. For submissions to oS:F this is not possible so the devel pkg can't be used. Use a package meant for this instead. This way a branch can be used as well, so the project setup can be taken from the prj on OBS.
=> Fix the OBS CI workflow (#2950)

metrics/access/aggregate.php, metrics/access/ingest.php
The change parses information about the `flavor` and `host IP` from the access logs and ingests them to the temporary cache files. The structure of the cache JSON object has been extended.
The aggregation script has been updated to to tag the number of downloads from unique systems (based on Zypper UUID) with `flavor` tag.
=> Add flavor information to access metrics

dist/package/openSUSE-release-tools.spec
Do not run it in packages that do not ship systemd services and properly
call it with the service name as parameter for the packages that do ship services.
=> dist: fix rpm scriptlets call to systemd_postun

factory-package-news/factory-package-news-web.py, factory-package-news/factory-package-news-web.service
This script is used eg. for the /snapshot-changes/opensuse/Tumbleweed
route and was using the WSGIScriptAlias apache command.
With the switch to nginx we need this more modern approach.
Ticket: https://progress.opensuse.org/issues/130312
=> Move factory-package-news-web.py script to gunicorn

gocd/monitors.gocd.yaml
reported by openQA, which is not monitoring ALP repos
=> also monitor the SUSE:ALP repositories

dist/ci/testenv-tumbleweed/Dockerfile
Currently it picks osc built against openSUSE:Factory/standard, causing a mismatch in Python versions.
I manually switched https://build.opensuse.org/package/show/openSUSE:Tools:Images/osrt-testenv-tumbleweed over to this branch to unbreak it.
=> dist: Pick osc from repo built against published Tumbleweed

check_source.py
* Ignore .gitattributes in checkout
* Skip Name: check when it is a scm-staging bot submission (relies on build service API that is broken for git packages)
* Skip devel-group-maintainer check
=> Cleanups for accepting scm-staging bot submissions

osclib/stagingapi.py
osc 1.0 changed the behavior of delete_project. Older versions considered
'force' to imply recursive, new versions want this explicitly.
Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2928
=> stagingapi: fix execution with OSC 1.x

gocd/bci.gocd.yaml, gocd/bci.gocd.yaml.erb, gocd/bci_repo_publish.py
Unfortunately TTM itself doesn't quite fit here due to the reasons outlined in the code and the additional checks are not a good fit for adding it into the go pipeline description, so write yet another OBS publishing bot!
For the initial test runs this is not triggered by timer runs yet.
CC @fcrozat
=> Add BCI repo publishing bot

metrics/access/aggregate.php
The logs are regularly rotated so we have to pick up older ones from the backup.
The change also modifies the starting day for the script to 01.01.2023.
=> Add backup server URL and update source map

project-installcheck.py
This file is used as input for the reminder bot, so avoid reminding and sending del reqs for ignored packages.
=> project-installcheck.py: Don't include ignored errors in rebuildpacs.yaml

factory-package-news/factory-package-news.py
rpm's python bindings changed in version 4.15 [0] so that they actually return utf-8 strings. Handle this case while keeping support for the older bindings such as the ones shipped with Leap 15.
[0] https://github.com/rpm-software-management/rpm/commit/84920f898315d09a57a3f1067433eaeb7de5e830
=> factory-package-news: support newer python3 rpm bindings

factory-package-news/factory-package-news.py
Which is `utf8str`, thanks to @dirkmueller :)
=> factory-package-news: use a nicer name for the forcestr function

factory-package-news/factory-package-news.py
(branched off #3002)
Some installation media ship packages in some non-guessable directories,
such as "Module-Python3" or "Module-Containers".
This Pull Request walks through every directory (except /boot) in the iso
image and searches for .rpms there.
=> factory-package-news: walk through every directory in the iso image

osclib/common.py
`version_calculate()` calls describe in the current working dir, but that fails in git repositories without any commits in them. Actually we should be calling this in the osc-release-tools repository instead, hence fixing this issue.
=> version_calculate: chdir to the osclib dir

gocd/bci.gocd.yaml, gocd/bci.gocd.yaml.erb, gocd/bci_repo_publish.py
The goal is to publish the repo at most daily. Previously this was ensured by simply running the bot only once a day. However, due to OBS and openQA timing this was frequently attempted when either of those wasn't done yet, which happened several times in a row. To not miss times when they align, attempt publishing more often but skip a build if the previous publish was recent enough.
=> Attempt to publish BCI repos more often

check_source.py
There was an early exit for packages which don't have a .spec file, but that is too early and skipped important parts like running the source_validator and download_files services and adding the review-team review.
=> check_source.py: Don't skip various checks and reviews for non-spec packages

metrics/access/aggregate.php
Holding all the UID statistics over the whole year consumes too much memory.
=> Disable aggregating over financial year

project-installcheck.py
Sometimes installcheck failures should be ignored for a specific architecture only.
=> project-installcheck.py: Support arch-specific ignore-conflicts config

gocd/alp-stagings.gocd.yaml, gocd/alp-stagings.gocd.yaml.erb
installcheck and packagelist checks were temporaly disabled for ALP Staging pipelines to allow openQA workflow test, while the issues reported by them are not fixed (they will be tracked on Staging H only)
=> Temporary disable checks for ALP

gocd/rabbit-openqa.py
Jobs without a group are not production jobs either. This also avoids a KeyError later.
=> gocd/rabbit-openqa.py: Ignore jobs without group

gocd/bci_repo_publish.py
There is no real good reason to wait for all the architectures to pass testing, so if there is one architecture finished, release it.
=> Release bci repositories per architecture independently

gocd/dashboard.generator.gocd.yaml
Machine moved to a new location, use DNS name of the new proxy server.
See https://progress.opensuse.org/issues/139118.
=> Update factory dashboard rsync target

CONTENTS.md, osclib/repochecks.py, pkglistgen/update_repo_handler.py, repo2fileprovides.py
~Should work but I only got around to test repo2fileprovides.py yet.~
Fixes #3032
=> Handle ZSTD compressed primary.xml.zst

ttm/releaser.py
since no CD will be used, but usb sticks
=> ttm: Allow bigger images for livecd-x11 on aarch64

dist/package/openSUSE-release-tools.spec, factory-package-news/factory-package-news.py
Reverts openSUSE/openSUSE-release-tools#3039
`TypeError: 'closefd' is an invalid keyword argument for this function` argh. There's no good way to use zstd from python on Leap apparently.
=> Revert "factory-package-news.py: Compress data files with zstd"

gocd/bci_repo_publish.py
When there was a source commit on the bci repo, then the set of packages changed, which likely means we need those changes to pass the tests on the container release pipelines. So don't wait for 24h but publish right away.
Also trigger on the oldest published state rather than the newest one so that we do not need to wait another 24h per openQA failure to resume publishing.
=> publish bci repo right away on package set changes

ReviewBot.py, check_source.py
"maintainers_get" is a bit weird and uses /search/owner and not the given prj.
Noticed in https://build.opensuse.org/request/show/1132698.
=> check_source.py: Use correct function for getting maintainer of the devel pkg

gocd/leapmicro.target.gocd.yaml, gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb, publish_distro_conf/publish_leap-micro60.config, publish_distro_conf/publish_leap-micro60_appliances.config
Regarding publish_distro Seems like initial configuration suggests that we'll use two digit versioning (6.0) for images rather than three digit (5.5.0) if we mimic SLEM 6.0) but that can be tweaked on the way, once there is something to be published.
Right now pkglistgen is what I care about.
=> Initial pipeline setup for Leap Micro 6.0

gocd/rebuild-trigger-alp.gocd.yaml
This is needed when we switch ALP Standard to rebuild=direct
=> gocd: add rebuild pipeline for ALP

ttm/releaser.py
live-kiwi-hook and openQA already do that, let's not triplicate the check.
=> ttm: Remove livecd size checks

findfileconflicts, osclib/repochecks.py
Don't rely just on findfileconflicts to check whether packages have
conflicting dependencies, but use libsolv to do a full check.
Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/1885
=> osclib/repochecks.py: Use libsolv for checking conflicts between packages

gocd/microos.target.gocd.yaml, gocd/sp.target.gocd.yaml
This was already implemented in ddd2304022e313eca9b391a043b12ecb9afe3bf7 for SLE GA to TEST, but missing in Micro and on the TEST -> PUBLISH leg in SLE.
Releasing from TEST to PUBLISH might still fail for various reasons. If it happens, ensure the pipeline exits early with non-zero exit code.
=> gocd: sp/micro-targets: ensure the pipeline exits on failures

gocd/microos.target.gocd.yaml
gocd: microos: Release both 000product and 000productcompose . This is needed to start gradually switching everything to the new product composer. In this way we allow for aligning the infrastructure before making the full switch.
=> gocd: microos: Release both 000product and 000productcompose

gocd/microos.target.gocd.yaml
This reverts commit 1e9554f94fdb4d34bd7847b0bbe04a9e9b8b2f1a. Releasing the product composer output makes the GoCD hang seemingly forever.
=> Revert "gocd: microos: Release both 000product and 000productcompose ."

pkglistgen/tool.py
Previously pkglistgen.py assumed that a project either used product-builder or the new product-composer, by exiting unrecoverably when a *.productcompose.in file was found but the relative 000productcompose directory was absent.
This is not the case for SL Micro as the shared SLFO codebase is still an hybrid OBS/git project and hence its stagings are not git based and can't use product composer.
This patch was tested for the SUSE:ALP:Source:Standard:1.0:Staging:A and SUSE:ALP:Products:Marble:6.0 projects (together with https://github.com/openSUSE/openSUSE-release-tools/pull/3078). Instead of raising an exception when the 000productcompose directory is not found it makes a log stating that product-composer will be skipped.
=> pkglistgen.py: Run product-composer iif there's a *.productcompose.in file and a 000productcompose directory.

build-fail-reminder.py
osc uses the string literally, make the generated log entry more readable by using the correct characters instead of a character reference.
Previous behavior were  commit messages showing character references which are not useful for humans:
```
$ osc log -D openSUSE:Factory kopete |head -4
----------------------------------------------------------------------------
r134 | anag+factory | 2024-02-08 18:02:03 | 8b84f116348051059ea6ac6b364667a7 | 23.08.4 | rq1144747
[botdel] Package has had build problems for &gt;= 6 weeks
```
Change tested using:
```
r = osc.core.Request()
r.add_action('delete', tgt_project='home:crameleon:ignore', tgt_package='dummy2')
r.description = 'foo >= 1'
r.create('https://api.opensuse.org')
$ osc request list home:crameleon:ignore dummy2
1147567  State:new …
```
=> build-fail-reminder: don't escape characters

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb
It's time to disable skippkg-finder for 15.6, NON_FTP_PACKAGES.group should not changed anymore, for not to be affected by any new updates then skippkg-finder should run anymore.
=> Leap 15: disable skippkg-finder for 15.6

pkglistgen/tool.py
Following scmsync syntax where a branch can be specified behind the URL fragment hash
=> pkglistgen: Support working on git branches

gocd/slfo-stagings.gocd.yaml, gocd/slfo-stagings.gocd.yaml.erb
add --git-url to pkglistgen.py calls to not use the old system
This needs https://github.com/openSUSE/openSUSE-release-tools/pull/3089 to work correctly
=> fix slfo stagings pipelines

gocd/alp-stagings.gocd.yaml, gocd/alp-stagings.gocd.yaml.erb
This basically remove things only needed during product development:
* Updating of release packages
* re-generation of 000product content
* Selectively enabling the images repository
=> Adjust the staging configuration of ALP to maintenance needs

gocd/slfo-stagings.gocd.yaml, gocd/slfo-stagings.gocd.yaml.erb
During image testing, the artifacts built inside the 'product' repository are used. Let's ensure that the repository is fully built before attempting to enable images.
=> gocd: slfo-stagings: wait for product to be built before enabling images

pkglistgen/cli.py, pkglistgen/engine.py, pkglistgen/tool.py
This PR is based on https://github.com/openSUSE/openSUSE-release-tools/pull/3089
=> pkglistgen: cli: Explicitly enable product-composer instead of detecting directories.

gocd/slfo-stagings.gocd.yaml, gocd/slfo-stagings.gocd.yaml.erb
Since https://github.com/openSUSE/openSUSE-release-tools/pull/3091 has been merged we can switch SLFO pipelines back to master
=> gocd: Restore SLFO pipelines.

check_source.py
An old typo, that was introduced in an attempt to support scm synced PRs
=> check_source: fix crash AttributeError: 'CheckSource' object has no attribute 'review_message'

osclib/cleanup_rings.py
devscripts has a sub-flavor for checknashisms that is required in Ring1 (for rpmlint)
The flavor "" is technically not required, but removing the package would make the
sub-flavor vanish as well.
=> cleanup_rings: whitelist 'devscripts'

gocd/slfo-stagings.gocd.yaml, gocd/slfo-stagings.gocd.yaml.erb, gocd/verify-repo-built-successful.py
Ensure that the 'product' repo is configured in the project meta.
Unfortunately, since we're checking in the configuration of the staging
itself, rather than the parent project's, there are increased chances of
some human/tooling error that might drop the repository from the
configuration. This will make the job run an endless loop.
Also, add a timeout for 180 minutes for the job. It is enough for
the product build process, and if it isn't, it's better to cancel
and have human eyes looking at it.
This PR also changes `verify-repo-build-successful.py` so that it detects if the
repository is missing (and will exit with retcode `2`), and it also marks
the `--project` and `--repository` arguments required as the script expect those
to be set.
=> slfo-stagings: add a timeout for Build.product, and do not run if repo is missing

gocd/leapmicro.target.gocd.yaml
I'd like to agree on how often gets the project republished.
The idea is that we have basically an unlocked project, where we keep on republishing repository and ensure that it contains all released updates for SLEM 6.0. This would be happening for 12 months and then would be disabled.
If there is a way to detect a change in underlying repository, that woud be perfect. Otherwise I think set it up for once a day would be sufficient.
Since we no longer have a regular install DVD, there is no corresponding test suite, we only have one for the :Images subproject/appliances. https://openqa.opensuse.org/group_overview/101
=> Automatic publishing of repos for LEAPM 6.0

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb
Leap 16 uses product-compose instead of product-builder
=> Leap 16 use pkglistgen with product-composer

dist/ci/testenv-tumbleweed/Dockerfile
zypper has the nasty habit of picking the alphabetically first package variant, which is not what we want
=> Install tools explicitly to avoid busybox variants being picked

osclib/core.py
In the staging areas used by maintenance, the patchinfo packages are staged together with the source packages, and because of the way they work, they collect binaries from the source packages around.
This causes binaries to be reported as duplicated, so ignore patchinfos.
=> Ignore patchinfo packages when checking for duplicated binaries

gocd/sp.target.gocd.yaml
This allows to always publish from :TEST to :PUBLISH even without the :GA -> :TEST step.
Useful for when gocd cleans up old pipeline runs.
Pretty much the same thing as #3102.
=> gocd: sle15: Split publish pipelines

osclib/freeze_command.py, osclib/stagingapi.py
Some projects (such as SLFO) are using product-composer, and
they build and publish in the 'product' repository.
If the 'product' repository is configured in the project meta,
ensure it gets configured when freezing the staging.
=> osclib: freeze_command: handle 'product' repositories if used 

.github/workflows/ci-test.yml
some time recently github actions runners seem to have changed to no longer provide docker-compose by default. install it.
=> Install docker-compose before running it

pkglistgen/group.py
Reasonings are really useful to understand why a package has been
pulled in. This commit adds those back in product_composer mode
and it matches the legacy behaviour.
Note: this PR also moves `Group.tocompose()` to f-strings to match the rest of the file.
=> pkglistgen: add sort reasonings in product_composer mode

metrics/telegraf/openqa.conf
As per discussion in https://progress.opensuse.org/issues/159669
=> metrics: Use https for openQA influxdb endpoint

ReviewBot.py
If a devel pkg maintainer submits, don't add a review on the devel pkg. Without this change it only looked at the /search/owner result which doesn't always work.
Example: https://build.opensuse.org/request/show/1193836
Previously:
```sh
> ./check_source.py --dry --debug --osc-debug --verbose id 1193836
DEBUG: makeurl: /request/1193836?withfullhistory=1
[D] Starting new HTTPS connection (1): api.opensuse.org:443
[D] https://api.opensuse.org:None "GET /request/1193836?withfullhistory=1 HTTP/1.1" 401 503
[D] Starting new HTTPS connection (2): api.opensuse.org:443
[D] https://api.opensuse.org:None "GET /request/1193836?withfullhistory=1 HTTP/1.1" 200 None
[I] checking 1193836
DEBUG: makeurl: /search/project?match=starts-with%28remoteurl%2C+%22http%22%29
[D] https://api.opensuse.org:None "GET …
```
=> Check devel pkg maintainers in devel_project_review_needed

legal-auto.py
It's rather hard for packagers to find the matching legal review for their OBS/IBS request. A comment with link should help make legal information more widely accessible.
I'm not the maintainer of legal-auto, but this has been a rather frequent request i've been getting from LegalDB users.
=> legal-auto: Link to legal review via comment

legal-auto.py
Reverts openSUSE/openSUSE-release-tools#3143
The rework/rewording was canceled to 'not open a can of worms' - and no further changes to the legal-auto bot are to be done.
To adhere to that statement, let's go back to the state we had before (and not spam package maintainers with messages including links they cannot use)
=> Revert "legal-auto: Link to legal review via comment"

legal-auto.py
Related to Issue #3149
States are documented here https://github.com/openSUSE/cavil/blob/master/docs/Architecture.md#states
"accetpable" is reviewed by an expert, "acceptable_by_lawyer" reviewed by an actual lawyer
This new state gives us opportnity to handle situation differently in case that review is done by lawyer, vs best effort.
=> Add state acceptable_by_lawyer

gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb, ttm/manager.py, ttm/releaser.py, ttm/totest.py
The description of the Leap 16.0 setup
* **000productcompose** is the main product but it builds ftp only. Build on `product` repo.
* **agama-installer** need to have identical build number as 000productcompose had. Build on `images` repo.
* **000productcompose** would not set release number while releasing to `ToTest`, but **agama-installer** does.
Tested this change with **Build36.40**
=> ttm: support Leap 16.0 development structure

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb, pkglistgen/cli.py, pkglistgen/tool.py
Add an --only-update-weakremovers option to be able to update weakremovers.inc only. With this option, pkglistgen will checkout release package and update weakremovers.inc, nothing else, no needed to have other product package involved.
Since Leap 16.0 don't use pkglistgen anymore but productcomposer, we still need a tool to recalculate weakremovers.inc according to the binary pool from the current and the previous version, therefore lets reuse pkglistgen's code for weakremovers handling.
=> pkglistgen: add an ability to update weakremovers.inc only

gocd/checkers.opensuse.gocd.yaml
Leap 16.0 should stay with main branch for now until perhaps 1.3 branch created.
=> slfo-packagelist-uploader: Leap 16.0 should stay with main branch

gocd/slfo.target.gocd.yaml
- Rename SLFO.Standard to SLFO.Snapshot
- Fix SLFO_BUILD_PROJECT, must be SUSE:SFLO:Main:Build where the binaries to be released to SUSE:SLFO:Main:Build:Snapshot are stored
=> Fix SLFO Snapshot pipeline

gocd/sles.target.gocd.yaml
Only release SLES16 packages from :TEST to :PUBLISH, skiping containerfile repository content that breaks the pipeline
=> Fix broken relase to :PUBLISH pipeline for SLES16

docker_publisher.py
Only :latest and :15 may provide that.
https://bugzilla.opensuse.org/show_bug.cgi?id=1231789
=> docker_publisher.py: Avoid using the 15.5 armv7hl image for the opensuse/leap:15.6 tag

gocd/bci.gocd.yaml, gocd/bci.gocd.yaml.erb
We have a role for BCI meanwhile, use it.
=> gocd: Let the BCI role trigger BCI repo publishing

osclib/cleanup_rings.py, osclib/memoize.py
And provide a major speedup for debugging with `@memoize(session=False)`.
Current result:
```
```
=> cleanup_rings: Also keep the main package if a multibuild flavor is needed

osc-pcheck.py
Use the proper API calls `<request><action type="submit">…` instead of
the no longer working `<request type="submit">…`
=> pcheck: fix creation of submit requests

gocd/monitors.gocd.yaml
We have added the prefix to the sync script. This will perform Agama SLES 16 synchronization in OSD.
=> Added SUSE:SLFO prefix for Agama SLES 16

osc-staging.py, osclib/list_command.py
This PR implements the ability to show for packages that do not belong to any ring the same details that are shown for packages that do live in rings.  Due to concerns about compatibility and volume of the output the feature is hidden behind a new --no-ring-detailed command line flag.
The following is an example of the change with the flag enabled:
and this is with the flag disabled
=> osclib/list_command.py: Allow showing details for packages not in rings.

gocd/slfo-stagings.gocd.yaml, gocd/slfo-stagings.gocd.yaml.erb
Rather than using verify-repo-built-successful.py, check with the API directly whether the product is blocked, scheduled or building.
Since it might happen for a product being broken/failed (even after a successful pkglistgen run), just fail in that case.
=> gocd: slfo-stagings: fail on broken/failed products

gocd/slfo-stagings.gocd.yaml, gocd/slfo-stagings.gocd.yaml.erb
Rather than using verify-repo-built-successful.py, check with the API directly whether the product is blocked, scheduled or building.
Since it might happen for a product being broken/failed (even after a successful pkglistgen run), just fail in that case.
This is #3191, but for SUSE:SLFO:Main rather than 1.1.
=> gocd: slfo-stagings: slfo-stagings: fail on broken/failed products (SLFO:Main)

gocd/leapmicro.target.gocd.yaml
* keep it aside from 6.0 which is still being actively published to cover for all maintenance updates
=> Add Leap Micro 6.1 ttm and pkglist workflows

gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb
* Add missing TTM setup for Leap Micro 6.1
* Micro 6.1 doesn't have :Images subproject
=> Add TTM config for Leap Micro 6.1

osc-staging.py, osclib/list_command.py, osclib/stagingapi.py
This patch implements overriding of the filter on reviews set up by the staging plugin. It is now possible to filter requests that have been reviewed by more than one group, for example; or to filter requests that have lack a request by a specific group or bot.
It allows queries like the following:
```
iosc staging -p SUSE:SLFO:Main list --match-filter "state/@name='review' and review[@by_group='factory-auto' and @state='new']"
```
or also
```
iosc staging -p SUSE:SLFO:Main list --match-filter "state/@name='review' and review[(@by_group='factory-auto' or @by_group='licensedigger') and @state='accepted']"
```
=> osclib/list_command.py: Allow overriding reviews filter from the command line.

check_source.py
Maintenance now uses patchinfo requests that were being declined by the factory-auto bot.
=> Make check_source ignore patchinfo using same rules as meta

gocd/leapmicro.target.gocd.yaml, publish_distro_conf/publish_leap-micro62.config, publish_distro_conf/publish_leap-micro62_appliances.config
* Pipeline for Leap Micro 6.2
* We'll have to update ~mirror/publish_* wrapper on pontifex wih publish_distro for Micro 6.2
=> Add Leap Micro 6.2 pipeline and publish_distro part

gocd/checkers.suse.gocd.yaml, gocd/checkers.suse.gocd.yaml.erb
Since the switch to Git backed sources for SL-Micro 6.0, staging
workflow does not work anymore for SUSE:ALP:Products:Marble:6.0. This
patch drops all related pipelines. Additional it adds the same checkers
for the SUSE:SLFO:Main project.
=> gocd: checkers.suse: Drop Marble pipelines and add SLFO checkers.

check_source.py, osclib/core.py
We are missing check for devel projects for new packages where the source project is in git and it's no longer searchable via API
=> check_source.py: Devel project check for new packages

verify-build-and-generatelists
For SL-Micro is currently failing with:
```
[CHECKING] Checking standard repository from SUSE:SLFO:Products:SL-Micro:6.1
2025-03-27T00:15:00+01:00
usage: verify-repo-built-successful.py [-h] [--apiurl APIURL] -p PROJECT -r
REPOSITORY
verify-repo-built-successful.py: error: unrecognized arguments: --engine product_composer --git-url https://src.suse.de/products/SL-Micro#6.1
```
=> verify-build-and-generatelists: Fix pkglistgen command line arguments for SLFO based products.

gocd/rebuild-trigger.gocd.yaml
Now Leap 16.0 is consist of package in openSUSE:Leap:16.0 and package in openSUSE:Backports:SLE-16.0, the most of package are built in openSUSE:Backports:SLE-16.0
=> gocd: add trigger-rebuild for openSUSE:Backports:SLE-16.0

verify-build-and-generatelists
Depends on https://github.com/openSUSE/openSUSE-release-tools/pull/3219
=> verify-build-and-generate: For SLFO based products, wait for SUSE:SLFO:Main:Build to be done building.

ttm/releaser.py
pkglistgen with productcompose engine uses underscore `_` in most places rather than a dash symbol, like the flavor name is consist of {group name}_{arch}, along with that, flavor and packageset group has underscore symbol in general.
=> ttm: add a new match pattern for the package naming in Leap 16

check_maintenance_incidents.py, osclib/core.py, tests/maintenance_tests.py
fixes maintenance requests like 1268814 where devel project information is only in git and the `/search/owner` API call is not very useful anymore.
https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/6ILLOYQ3W4IWTA47WTXBANZZGLHTFYBB/
=> maintenance bot: add support for git-based devel projects

devel-project.py
Some projects have restricted permissions and so staging bot fails to get maintainers. Handle that gracefully by posting the generic reminder instead of failing completely.
=> devel-project.py: Handle hidden projects gracefully

ttm/releaser.py
Leap 16 now have offline installer, lets set release number on offline installer to have the same number as the ftp build. Removing the special handling of productcompose product.
=> ttm: set offline installer the same release number

devel_update.sh
Sometimes osc return submit requests in format
project/package@hash -> openSUSE:Factory
and one time it did,
network/bird3@hash ->  openSUSE:Factory
And 2 spaces are not 1
=> devel_update.sh: be flexible with space

check_maintenance_incidents.py, tests/maintenance_tests.py
Similar to #3041
https://build.opensuse.org/requests/1294764
> Submission for etcd by someone who is not maintainer in the devel project (devel:kubic). Please review
It uses `/search/owner` to determine the maintainers, but that does not expand roles recursively. If the submitter is not one of the owners, it adds a prj/pkg review which is recursive.
=> check_maintenance_incidents.py: Expand devel pkg roles for maintainer check

ttm/publisher.py, ttm/totest.py
ftp product might released to the default product_repo in ToTest, add an config bit to be able to enable the default product_repo or the override repos.
=> TTM: only publish override repos if publish_multiple_product_repo config is enabled

osclib/core.py
When getting the devel project via the build service API, and the source project is accessed via interconnect, the returned devel project contains the instance prefix.
However, when checking directly in the Factory git mapping, the interconnected prefix is not being added to the result.
As such, ensure we handle this case too - and just replace the instance name if found.
=> osclib: core: explicitly replace OBS instance prefix in devel_project_fallback

staging-installcheck.py
TypeError: InstallChecker.upload_failure() takes 3 positional arguments but 4 were given
(devel was used in a prototype, but later reworked)
=> staging-installcheck: fix syntax failure introduced with 597d48be

check_source.py
Treat them like kiwi and Dockerfile, where there's currently no check for name consistency.
=> check_source.py: Skip name validation for mkosi builds

gocd/pkglistgen.opensuse.gocd.yaml, gocd/pkglistgen.opensuse.gocd.yaml.erb, gocd/totestmanager.gocd.yaml, gocd/totestmanager.gocd.yaml.erb, skippkg-finder.py
product package are now moved to `Products` subproject of `openSUSE:Leap:16.0` project after sources has switched to git.
=> adjust the various pipeline for the changed Leap 16.0 product build setup

ttm/totest.py
A usecase is like Leap 16.0 has product images built in openSUSE:Leap:16.0:Products project, the buildresult will release to openSUSE:Leap:16.0:ToTest project, we should be able to override test_project attribute via ToTestManagerConfig.
=> TTM: allow to override test_project attribute from config

container_cleaner.py, tests/container_cleaner_tests.py
`_result?view=binarylist` is sufficient to replace > 50k (!) calls to get the list of binaries individually.
Reduces runtime from ~39min (last run on botmaster took 44min even) to 0min7s!
=> container_cleaner.py: Use more efficient API calls
