osclib/accept_command.py
osclib/freeze_command.py
osclib/stagingapi.py

Please give a review and let me know if I do something completely silly - or if I miss something

Progress5958

---

osclib/accept_command.py
osclib/stagingapi.py

I miss some good way to test that! so this is all very theoretical here...

staging accept: create new links for packages when a new .spec file appears

---

osc-staging.py
osclib/accept_command.py
osclib/stagingapi.py

Merged the resync into staging accept as last command

Merge sync-rebuild into staging accept command

---

ReviewBot.py

if a review for the maintbot user is added for a second time the old
function would only see the  'accepted' state of the first review and
the bot would not change the review state.

handle multiple reviews by same user

---

osclib/stagingapi.py

looks like self.crings is indicating the correct path of rings dvd prj, self.project is "openSUSE:Factory" I think

given the correct ring_dvd path

---

osclib/accept_command.py

Reverts openSUSE/osc-plugin-factory#304

Revert "accept_command: import urllib2"

---

create_test_Factory_dvd-1.testcase
create_test_dvds.sh

Create Test-DVD for PowerPC

---

create_test_dvds.sh

create test dvd for stagings on power

---

totest-manager.py

Add PowerPC:ToTest

---

osclib/cleanup_rings.py

cleanup ppc64le aswell

---

create_test_dvds.sh

Enable Ring 2 for PowerPC

---

create_test_dvds.sh

fix string concatenation

---

create_test_Factory_dvd-2.testcase

Adjust Ring2 dvd for PowerPC

---

osclib/stagingapi.py
totest-manager.py

Query openQA results by Job group

Add group to the openQA query

---

create_test_dvds.sh

once rpms2solv fails to find rpms it will reiggered exiting the script, check it had rpms there before do rpms2solv, otherwise return back and go next project.

Do not exit the script if can not find rpms

---

osclib/stagingapi.py
totest-manager.py

needs deploying openqa.oo though

only pass the group to the API

---

create_test_dvds.sh

the solv file also will be $dir-$arch.solv

sync binaries to seperate directory per architecture

---

openqa-comments.py

fix openQA status handling

---

create_test_dvds.sh

for integrate with project 42, must have changes in loop.sh like
create_test_dvds.sh Factory x86_64 has_ring_all has_staging
create_test_dvds.sh Factory ppc64le has_ring_all has_staging
create_test_dvds.sh 42 x86_64 has_ring_1
comment?

use args to handle the actions against rings and staging

---

totest-manager.py

Use known_failures for machines we have tests for.

filter out unneeded machines from known_failures

---

update_crawler.py

This scripts can analyze two repositories, one that contains
updates, and the other a linked distribution.  Check the last
updated packages and send (if there is not any) a submit request
with the updated package.

Add update_crawler.py script

---

totest-manager.py

Hopefully we started to build multiple products from
single dvd flavor. This will couse to have same flavor
for ppc64 and ppc64le architectures

Adapt main product to products change

---

update_crawler.py

Also adds a new dependency to `python-semantic_version`

Check the version of the package.

---

check_tags_in_requests.py
tests/checktags_tests.py

Don't require an entry in the changelog if
1. The package is already submitted to Factory and has a changelog
2. The package is a new submission, not an update

Add exception from changes tag requirement

---

check_source_in_factory.py
check_tags_in_requests.py
tests/checktags_tests.py

I think this should fix the problem. It grabs the first diff of a file ending in .changes in the submit diff.
I haven't fixed the tests, so the tests are failing since it now tries to get the server diff.
Fixes: #358

Rely on server-side issue tag check

---

osclib/request_finder.py

prject=openSUSE:Factory package=yast2 finds also packages going into 42,
which is not what we want

check for target project too in request finder

---

fcc_submitter.py

Fcc submitter

---

fcc_submitter.py

Add a except pkgs list and convert skip/except pkgs lists to regex
style, and update the lists.

Add a except pkgs list and convert skip/except pkgs list to regex style

---

update_crawler.py

Just checking verifymd5 for everything in sle12-picks - if sle12 sp1
comes with a version downgrade, we should see it

simplify update_crawler

---

fcc_submitter.py

being submit new package only and update the skip list.

Bbeing submit new package only and update the skip list

---

manager_42.py

it's less reliable (with multiple spec files) than just querying the
history of the possible source projects

stop querying requests

---

manager_42.py

- avoid iterating over an array that is changed
- detach branches before removing the target

two critical bug fixes

---

source-checker.pl

Fix https://github.com/openSUSE/osc-plugin-factory/issues/415

Accept Copyright headers with a different format.

---

manager_42.py

strip out all logic required for the subproject split

rework manager the 9th:

---

rebuildpacs.pl

https://bugzilla.opensuse.org/show_bug.cgi?id=947846

rebuildpacs: also trigger rebuilds for openSUSE-images

---

osclib/request_finder.py

the error wants strings, but the cast is happening to early

fix request casting

---

rebuildpacs.pl

OBS guys refactoring user handling...

use the public route for the api

---

create_test_dvds.sh
osc-check_repo.py

More places need to use public route

---

osclib/stagingapi.py

don't use recursion and don't hammer server
I couldn't test that one as the servers are back..

don't use recursive retry

---

totest-manager.py

Drop ppc32

---

osc-check_repo.py
osclib/checkrepo.py

Fix https://progress.opensuse.org/issues/10888

Do not count excluded repository as good repo

---

totest-manager.py

Skip obsoleted jobs

---

osclib/checkrepo.py

Add the possible repo candidates to repos_to_check, those candidates
need to have binaries for check.

Add the possible repo candidates

---

osc-staging.py

Add misses part for force accept

---

totest-manager.py

Try to be smart enough to only publish :ToTest if the version we passed
to openQA matches what is found in :ToTest.
This avoids releasing untested snapshots in case the release process
had trouble syncing from openSUSE:Factory/standard to :ToTest (e.g.
partial releases).

ttm: Safeguard publishing of :ToTest

---

osclib/adi_command.py

it is look like
openSUSE:Factory:Staging:adi:60 is ready
cedilla [381552]

Show package also in adi command

---

osc-staging.py
osclib/repair_command.py

Mainly fix the request review if the request got reopened.

New staging repair command

---

osclib/checkrepo.py

More sensible output in check_disturl(). And changed the output flag to WARNING than DECLINED as it did not really decline the request.

More sensible output in check_disturl()

---

openqa-maintenance.py

https://github.com/openSUSE/open-build-service/issues/1529

Make sure to not post unicode strings to OBS

---

osclib/adi_command.py

eg. https://build.opensuse.org/project/staging_projects/openSUSE:Factory/adi:5

Use number instead of id for id->number switch issue

---

osc-check_source.py

Try again - seems better this time at least

Add Virtualization:Appliances:Builder as devel prj to the whitelist

---

abichecker/systemd/opensuse-abi-checker.service

screen on SLE doesn't like too long user names

Run abichecker in tmux

---

osclib/check_command.py

display the proper request number

Fix for id->number change in check_command

---

osclib/list_command.py
osclib/stagingapi.py
tests/api_tests.py
tests/fixtures/source/openSUSE:Factory:Rings:0-Bootstrap
tests/fixtures/source/openSUSE:Factory:Rings:1-MinimalX
tests/fixtures/source/openSUSE:Factory:Rings:2-TestDVD

Just lazy to fix that complicate conflicts in https://github.com/openSUSE/osc-plugin-factory/pull/520

Rework generate pkgs

---

osc-check_source.py

Devel projects: whitelist system:snappy

---

ReviewBot.py
openqa-maintenance.py

(for this check the checksum of the repo checksums)

Schedule Test Repository tests if not yet done

---

totest-manager.py

Signed-off-by: Dinar Valeev <k0da@opensuse.org>

Treat softfailed as ok to pass

---

fcc_submitter.py

Introduced a new class: FccFreeze
New usage:
* fcc_submitter --freeze : freeze FCC project
* fcc_submitter --list : list build succeeded packages in FCC
Also clean up old skip list and so on, and update sle base projects
list.

Update fcc_submitter for Leap 42.2

---

fcc_submitter.py

Make check_multiple_specfiles return the linked package name rather than
True or False, and if it has not linkinfo node then continue to process
this package.

Make check_multiple_specfiles return the linked package name instead

---

fcc_submitter.py

Also disable add_review part, rely on leaper now.

Update skip list 20160808

---

manager_42.py

Linked packages are supposed to have their devel package set to the
main package. We need to check that before so packages are marked as
subpackages instead of coming from a devel project.

Handle links before devel projects

---

osc-check_source.py

dochazka is the upcoming application that we are going to use in the Prague
SUSE office as our attendance / payroll system. It comes with a CLI client,
thus it would be really beneficial to add it to factory and upcoming leap

add Application:Dochazka as devel project

---

osc-check_source.py

The maintainers are active in this project and maintain various versions of stunnel there for a while already

Whitelist security:Stunnel as a devel project (boo#999923)

---

manager_42.py

that way update crawler will still submit updates from SLE

Don't switch origin to SLE-workarounds

---

osclib/request_finder.py

If found the staging project for the request then it should quit the loop, continue the loop makes no sense.

Quit the loop if found the staging project for the request

---

osc-check_source.py

In preparation for submission of HPC related packages, add this
project to the whitelist.
Signed-off-by: Egbert Eich <eich@suse.com>

osc-check_source.py: whitelist network/cluster as devel project

---

osclib/accept_command.py

Make sure Test-DVD won't in green state when new round just started, wipe Test-DVD binary and intended to break kiwi build when accepting the staging.
Next step is let create_test_dvds skips the staging what the build is disabled to avoid create_test_dvds correction the kiwi file.

Let Test-DVD is invalid in the beginning of the new round

---

openqa-maintenance.py

Instead of linking to the first step in a failed test, link to the first
failing. openQA uses this route internally to delay parsing details

Fix link to the failed step

---

openqa-maintenance.py

Include all groups counting the passing jobs too (we need a link
to the passing groups to see if SP1 and SP2 were tested)

Change incident summary

---

manager_42.py

Catch non-existing project

---

update_crawler.py

Requests may either contain the srcmd5 or the decimal revision. So we
may need to convert the revision to srcmd5.

Expand decimal revisions in requests

---

osclib/adi_command.py

Tabs vs spaces is even scarier in python.

adi_command: whitespace cleanup.

---

compare_pkglist.py

Comparing package source between two project. https://progress.opensuse.org/issues/14938

Add compare_pkglist.py

---

openqa-maintenance.py

And remove some of the noisy debug output

Fix comments default for openqa-maintenance bot

---

compare_pkglist.py

Using expand:1 otherwise might lost the package information of inherited packages. Also ignores second specfile package.

Force using expand in the api call and ignores the linking package

---

manager_42-leap423.yml
manager_42.py

For example for Leap 42.3 it could look like this

Implement config for manager42

---

ReviewBot.py
leaper.py

In the spirit of the existing code I made the minimal number of changes to `leaper.py` to make it function for the SLE workflow described in email. The primary tenant being as follows.
Origin does not matter to SLE, instead check if same source exists in:
- factory
- if fails, 42.2
- if fails, devel project
Refactoring, for instance the name of script and further cleanup would certainly help, but this should get the ball rolling.
The following is output from running locally.
```bash
./leaper.py --osc-debug -A ibs --dry --debug id 120636
```
```
GET https://api.suse.de/request/120636?withhistory=1
INFO:leaper.py:checking 120636
INFO:leaper.py:openSUSE.org:openSUSE:Factory/bcm43xx-firmware@1 -> SUSE:SLE-12-SP2:GA/bcm43xx-firmware
GET …
```

Leaper modification for SLE workflow

---

check_source.whitelist

In anticipation of a fate client submission

Add FATE devel project to white list

---

ReviewBot.py
check_source_in_factory.py
leaper.py

Easily clickable links are a convenient feature.

Put links to source diffs

---

osclib/repair_command.py

Improve repair cmd, when the opened review project is not exist we've to create a empty project for it, this situation should only happens on adi staging.
https://progress.opensuse.org/issues/16238

Re-create adi staging if the opened review project is not exist

---

osclib/request_splitter.py

Return None if has not action/source

---

fcc_submitter.py

Small change in FCC Submitter against 42.3

Adjust FCC_Submitter for 42.3

---

osclib/unselect_command.py

Especially handy when using select command to automatically pick set of requests rather than by hand.

unselect: suggest marking a request ignored if eligible to restage.

---

openqa-maintenance.py

* Add kGraft24
* Add kGraft0j
* Remove kgraft-guests which served kernels that are now out of live-
patching support

Add kGraft24 and kGraft0j, remove now unsupported SUTs

---

leaper.py

It is a regular occurrence for submitters to send simultaneous requests to Leap and Factory. Many times the requests may also have followup work before making it into Factory which then results in another set of requests sent to Leap as well. Given that the requests will not be accepted to Leap until they are accepted into Factory all of this seems rather unnecessary and burdensome to all involved. I mentioned to a couple submitters that leaper would automatically create requests for packages sourced from Factory once accepted, but it generally does not seem well known.
Seems like it would be a good idea to highlight this handy feature to reduce workload on everyone involved.
This branch includes #692 so please wait until that is accepted and I will rebase.

leaper: notify submit request authors of automatic submission.

---

ReviewBot.py
tests/factory_source_tests.py
tests/maintenance_tests.py

Supersedes #687 as this includes test fixes.

Reviewbot encoded URL fix (previously #687)

---

osc-staging.py

See #709, but also something I typically patch `obslock.py` to achieve.

osc-staging: provide unlock to resolve stuck staging locks.

---

check_source.whitelist

See https://lists.opensuse.org/opensuse-factory/2017-03/msg00337.html

Add hardware:sdr to whitelist

---

fcc_submitter.py

If the sub-package fails to build in FCC, don't submit the main package then,

Make sure sub-package is build successful in FCC too

---

osc-staging.py
osclib/ignore_command.py

- extend --message to unselect which will ignore first. (requested in #716)
- utilize RequestFinder in ignore command. (requested in #715)

ignore: integrate with unselect and use requestfinder

---

devel-project.py

- drop user list if no maintainers
- fallback to project if package has no maintainers

devel-project: remind fallback

---

osc-staging.py
osclib/rebuild_command.py
osclib/stagingapi.py

osc-staging: provide rebuild_check() to conditionally rebuild failures.

---

osc-staging.py

- adi and unignore commands request list is optional
- s/PROJECT/STAGING/ for consistency
- include --add option in select command

osc-staging: correct and cleanup summary documentation.

---

osclib/checkrepo.py
repo-checker.pl

Incomplete stil, arch selection needs to be smarter

Prepare repochecker for Leap

---

osc-staging.py
osclib/prio_command.py

raise priority for requests in review

Add setprio command

---

osc-staging.py
osclib/accept_command.py
suppkg_rebuild.py

related to https://progress.opensuse.org/issues/15448

Rebuild staging project if it has support package was staged

---

openqa-maintenance.py

Add kGraft1d, kGraft1e and kGraft25

Add new kGraft systems

---

openqa-maintenance.py

Seperate the incidents and the repos - not all progress is problematic

QAM: Do not treat all repos the same

---

totest-manager.py

Instead of having the known failures in a global file, have it local to the TTM
but allow users to interact with it through openqa comments.
Work flow:
- openQA tests and finds failures
- reviewers tag them with (support from automatic carry over)
- if they are in the ignore list, TTM will not do anything but ignore them
- if not, TTM will add label:unkown_failure to mark the issue blocking
a release
- the release manager adds @ttm ignore as comment for the TTM to
add the issue to its white list.
Only if all failures are labeled and marked as ignored, a snapshot is released

Have TTM work through openqa comments

---

osclib/obslock.py

Handy to know if likely stuck or someone working.

obslock: include delta in message.

---

openqa-maintenance.py

* Add kGraft0k, kGraft1f, and kGraft26.
* Remove kGraft0c, kGraft14 and kGraft15.

Update list of kgraft test-systems.

---

update_crawler.py

It's just too much and needs to be submitted manually

Hack to skip haskell submissions

---

tests/checktags_tests.py
tests/factory_source_tests.py
tests/fixtures/request/template_request.xml
tests/maintenance_tests.py

Fixes #807 which means travisci should pass again.

tests: add missing creator attribute to requests to satisfy osc.

---

manager_42.py

Don't unset the project, instead avoid the return statement to exit
early

Different implementation for --force

---

leaper.py

Fixes #836. Needs confirmation of desired logic.

leaper: do not add review team for SLE requests for FORK'd packages.

---

osc-staging.py
osclib/adi_command.py
osclib/list_command.py
requirements.txt

Something I was playing around with as it drastically improves the ability to scan/read the output which is relatively busy. Can try and make colorama not required by mocking it and falling back to simple mock when not available.
Try it out and see if it is helpful.

osc-staging: implement colorization using colorama for adi and list, along with some formatting cleanups.

---

osclib/adi_command.py
osclib/stagingapi.py
osclib/supersede_command.py

I may work on a test for the supersede functionality at this cases are less often to come by in order to confirm. Likely be a couple cases in the next day and I simulated the rest. Opening to allow for review and remind myself to followup.
Fixes #842.

supersede: include ignore and decline in output.

---

osc-staging.py
osclib/adi_command.py
osclib/list_command.py
osclib/rebuild_command.py
osclib/stagingapi.py
osclib/supersede_command.py

Adding color to a few more commands.

color extended: rebuild, supersede, frozenage, freeze.

---

osclib/conf.py

conf: provide remote-config option and default to false for SLE.

---

osclib/request_splitter.py

request_splitter: only allow devel/super followup for non-bootstrapped.

---

legal-auto.py

For security we currently rely on legal-auto running on the same server as the legaldb API. In the futue we will switch to using token based authentication though. In preparation this pull request adds a `--token` command line flag.

legal-auto: allow for an authentication token to be sent

---

osclib/list_command.py

Otherwise can cause the source information to be spaced incorrectly due to the color characters counting towards the size.

list: correct ring-0 spacing by separating the color from value.

---

osclib/stagingapi.py
suppkg_rebuild.py

- 7561c01cd806e9b1e359b0b6db086ff8650315b6:
suppkg_rebuild: drop unused self.debug.
- 602f3a31b7890c91dc305c920ee2992dcbef03b0:
suppkg_rebuild: drop unused get_buildinfo_version().
- 1a3e57291529eddecd27544419a8b4e24f866a16:
suppkg_rebuild: drop unused get_package_buildinfo().
- 00dfd235fa0b4e7e1ac4ef9409e4ec27c2184dcb:
suppkg_rebuild: drop unused get_source_packages().
- 0f73e5b9a458c255fccf587ddbb64a9ef48cc99e:
suppkg_rebuild: utilize osc.core.rebuild().
- d50c5cbca77e86e43915317e4ab9ccc351dbb831:
suppkg_rebuild: only save rebuild data if it changed.
- 461fffde7b4d99ccef19b1d22572e120033f62b7:
suppkg_rebuild: utilize stagingapi.{load,save}_file_content().
- 8996c4c2ab8eaeaf64ae4d125dd0be3a0554b130:
stagingapi: save_file_content() provide comment optional parameter.

suppkg_rebuild: only save support_pkg_rebuild file to dashboard if changed (and cleanups)

---

check_source.py

check_source: accept delete repository requests.

---

issue-diff.py

- eb0d96d7a26a61dae08ca828184fc90ca8eb33c0:
issue-diff: provide --print-stats option.
- 3e2469c5cc52d537983187eb6b6d1f9c39970ff2:
issue-diff: bug_meta_get(): handle invalid bug numbers.
Package ibus-pinyin contains bnc#000000 which fails to load.
- d586c8748ae24c53cd14ed52264d167f8b7b1060:
issue-diff: truncate messages longer than bugzilla limit.
- 4f6b8cc1e5cf6b15535435af19760fb87ba59739:
issue-diff: handle multiple faults and new fault invalid username.
- ed4b652ae20f7726f9b6c67653232321494bf092:
issue-diff: print progress message every 50 packages.

issue-diff: handle multiple faults and new fault invalid username (plus other fixes)

---

openqa-maintenance.py

please don't deploy before 1.6.2017

SLE-12-SP1 switch to LTSS mode

---

osclib/request_splitter.py

Fixes #947.
See issue for details.

request_splitter: fallback to source project when devel is not present.

---

osclib/list_command.py

Logical followup to #950 for SLE.

list: hide source project for SLE now that devel falls back to source.

---

create_test_Factory_dvd-1.testcase
create_test_Factory_dvd-2.testcase

Mainly to added new requirement for testing textmode and docker, and adjust the
template per patterns change.

Update testdvd template

---

openqa-maintenance.py

All kernels have initial kgraft-patch, so current code try to start
uselees kgraft tests job

openqa-maintenance: disable kgraft jobs for kernel update

---

osclib/adi_command.py
osclib/stagingapi.py

Create frozenlinks in case had matched source project in expand-allpkgs-from-same-srcprj config, the frozenlinks contains all packages from the specific source project.
Tested it in real: https://build.opensuse.org/project/show/openSUSE:Factory:Staging:adi:181
https://progress.opensuse.org/issues/19830

Use frozenlinks for submission from the specific project

---

openqa-maintenance.py

openqa-maintenance: dont start KGRAFT jobs in Server-DVD-Incidents

---

osclib/accept_command.py

in opeSUSE:Factory, for example, there is also openSUS-Kubic.product and the
versions are supposed to stay in sync.
We newly find all product definitions inside a project and update all of them,
with the same limiation as before: only if version was a 8 digit version it will
be updated to the current date stamp
Additionally, this is a preparation for the new product builder, as _product is no
longer hardcoded, but found.

AcceptCommand: update version of all products found in the project

---

osclib/adi_command.py

If someone branched the ADI we are not able to delete it. Just ignore that.

Ignore failures to delete adi's

---

leaper.py

This shows just how much something like #944 (cleanup) is needed.
In order to maintain existing logic, but disable until relevant again I placed a `False and` in front of disabled conditions along with a comment about when it should be re-enabled.
Fixes #1036.

leaper: transition from SLE-12-SP3 and Leap:42.3 to SLE-15 and Leap:15.0.

---

update_crawler.py

allow filtering by devel project too

update-crawler: handle devel projects

---

fcc_submitter.py

Noticed while working on #1051.

FccSubmitter: drop add_review() since never used and handled by other bots.

---

ReviewBot.py
check_maintenance_incidents.py
leaper.py

Also update calls based on default behavior change.
Fixes #1050 unless changes to diff algorithm are also desired.

ReviewBot: add_review(): raise exception on failure and avoid duplicate reviews

---

create_test_Factory_dvd-2.testcase

:D is always so happy so needs to be green :-)

Adjust for staging :D

---

osc-staging.py
osclib/freeze_command.py
osclib/stagingapi.py

Since we have introduced the source project expand function in adi staging project, a new function to freeze a adi staging project is needed as well.

Freeze Cmd: Implement freezing adi staging project

---

repo_checker.py

To be consistent with other behavior.

repo_checker: delete: do not decline instead ignore.

---

repo_checker.py

repo_checker: delete: explicitly indicate build requirement.

---

osc-staging.py

accept: call accept_other_new() for all projects instead of just openSUSE.

---

osclib/conf.py

osclib/conf: do not disable remote config for SLE-15.

---

openqa-maintenance.py

Also fixes problem with unnecessary spaces in list of packages

Generate minimals with set compression

---

.travis.yml
dist/ci/deploy.obs.sh

dist/ci/deploy: create submit request if none currently exists.

---

Makefile
dist/package/openSUSE-release-tools.spec
systemd/osrt-staging-bot-daily@.service
systemd/osrt-staging-bot-daily@.timer
systemd/osrt-staging-bot-devel-list.service
systemd/osrt-staging-bot-devel-list.timer
systemd/osrt-staging-bot-regular@.service
systemd/osrt-staging-bot-regular@.timer
systemd/osrt-staging-bot-reminder.service
systemd/osrt-staging-bot-reminder.timer
systemd/osrt-staging-bot-supersede@.service
systemd/osrt-staging-bot-supersede@.timer
systemd/osrt-staging-bot-support-rebuild@.service
systemd/osrt-staging-bot-support-rebuild@.timer

dist: provide staging-bot subpackage for related services.

---

Makefile
dist/package/openSUSE-release-tools.spec
systemd/osrt-maintenance-incidents.service
systemd/osrt-maintenance-incidents.timer

dist: provide maintenance subpackage.

---

pkglistgen.py

- allow to specify architecures
- need to specify default support status
- use correct api (still dirty)

pkglistgen: initial work for openSUSE

---

ReviewBot.py
ToolBase.py
abichecker/abichecker.py
abichecker/abichecker_common.py
biarchtool.py
check_source.py
check_source_in_factory.py
devel-project.py
fcc_submitter.py
issue-diff.py
leaper.py
manager_42.py
osclib/accept_command.py
osclib/adi_command.py
osclib/cycle.py
osclib/prio_command.py
osclib/repair_command.py
osclib/stagingapi.py
suppkg_rebuild.py
totest-manager.py
update_crawler.py

This newer style except statement allows for compatibility with
Python 3.x and does not harm on python 2.6+.

Python 2.6+ / 3.x style except clauses

---

README.asciidoc
checknewer.py
tests/__init__.py

This is a python script so as the majority of scripts in here
it should end in a .py suffix

Rename checknewer to checknewer.py and fix Flake8 fallout

---

pkglistgen.sh
script/osrt-pkglistgen-openSUSE:Leap:15.0:Staging.sh

would spoil next iteration in loop

pkglistgen: don't export skip_releases

---

devel-project.py

#1206 was a bit to optimistic as the deficiency was only half resolved.

devel-project: override osc.core.search() to include withfullhistory for get_review_list().

---

osclib/accept_command.py

may fixes https://github.com/openSUSE/osc-plugin-factory/issues/1232

accept_command: remove the ring package if it is 2nd specfile is removed

---

repo_checker.py

Build failures may cause false negatives in repo_checker results, but openQA failures are not relevant and should be ignored.
Fixes #1069.

repo_checker: review failed stagings with only openQA failures.

---

compare_pkglist.py

* Ignore '000' family package
* Add a `--newonly` parameter
* A better output format
* Always `linkinfo` even the package is new
* Can display deleted package but exists in target now
* Also a `--removedonly` parameter has introduced

compare_pkglist: misc improvements

---

leaper.py

Skip maintainer review for certain Leap 15 submissions

---

totest-manager.py

Example log output of call
`totest-manager.py --project-base SLE --dry --debug --verbose run SUSE:SLE-15:GA`:
```
2017-11-14 23:37:55,711 - totest-manager:267 INFO job sle-15-Installer-DVD-x86_64-Build-foo@bar failed, see https://openqa.suse.de/tests/12345
2017-11-14 23:38:00,308 - totest-manager:478 INFO current_snapshot 123.4: failed
2017-11-14 23:38:00,308 - totest-manager:479 DEBUG new_snapshot 128.1
2017-11-14 23:38:00,308 - totest-manager:480 DEBUG current_qa_version None
2017-11-14 23:38:05,878 - totest-manager:483 DEBUG snapshotable: True
2017-11-14 23:38:06,135 - totest-manager:500 DEBUG totest already publishing
2017-11-14 23:38:06,136 - totest-manager:436 INFO Updating snapshot None
2017-11-14 23:38:06,136 - totest-manager:546 INFO release SUSE:SLE-15:GA/000product (None)
```

ttm: Add support for SLE 15

---

check_source.pl
check_source.py

Fixes https://github.com/openSUSE/osc-plugin-factory/issues/1264

check_source: Ignore download_files failure in some cases

---

compare_pkglist.py

* Add --existin param, verify the package exists in --existin project.
* Add --submitfrom and --submitto params, that are configurable the submit source and target.
Usage:
* python compare_pkglist.py --old 'openSUSE:Factory' --new 'openSUSE:Leap:15.0' --existin 'openSUSE:Leap:42.3' --newonly
* python compare_pkglist.py --old 'openSUSE:Factory' --new 'openSUSE:Leap:15.0' --existin 'openSUSE:Leap:42.3' --newonly --submit
* python compare_pkglist.py --old 'openSUSE:Factory' --new 'openSUSE:Leap:15.0' --existin 'openSUSE:Leap:42.3' --newonly --submit --submitfrom 'openSUSE:Leap:42.3' --submitto 'openSUSE:Leap:15.0'

compare_pkglist: add more features

---

totest-manager.py

Example output from dry run:
```
2017-11-24 06:42:57,927 - totest-manager:490 DEBUG snapshotable: True
2017-11-24 06:42:57,927 - totest-manager:495 DEBUG no change in snapshot version
2017-11-24 06:42:58,415 - totest-manager:207 DEBUG Writing openQA status message: {'text': 'pinned-description: Ignored issues\r\n\r\n\r\n\r\ntag:20171123:testing:testing'}
```

Add more details to openQA job group description about current status

---

compare_pkglist.py

small fixes for pre-check part.

compare_pkglist: fallback to old route if submitfrom and submitto has not defined

---

repo_checker.py

useful for debugging to limit reviews to a specific group

repochecker: add --force and --limit-group options

---

systemd/osrt-leaper-review.service
systemd/osrt-metrics@.service
systemd/osrt-repo-checker-project_only@.service
systemd/osrt-repo-checker.service
systemd/osrt-staging-bot-daily@.service
systemd/osrt-staging-bot-regular@.service
systemd/osrt-staging-bot-reminder.service
systemd/osrt-staging-bot-support-rebuild@.service

Those services are of type 'simple'

systemd units: remove oneshot type

---

totest-manager.py

accept @ttm: ignore also as valid input

Be more forgiving with ttm ignore comments

---

osclib/conf.py

Depends on #1328, intial config for SLE [#1329]. Not sure exactly the archs setup and other bits, but this should make it run as closely to desired with the existing code.

osclib/conf: intial SLE configuration for pkglistgen.

---

requestfinder.py

helps to mass approve, decline reopen reviews and requests

new requestfinder tool

---

osclib/request_splitter.py

The addition of factory-auto and repo-checker reviews need to be allowed
since they are always present and do not constitute a non-quick review.
In an attempt to future proof the strategy the allowed review groups are
taken from the project configuration and repo-checker from config.
Fixes #1340.

osclib/request_splitter: rework quick strategy to handle Leap 15.0 workflow

---

factory-package-news/factory-package-news-web.py

news/web: allow dot in version.

---

docs/pkglistgen.md

docs/pkglistgen: update in the wake of wrapper script rewrite.

---

repo_checker.py

Incorrectly changed in 456a7c8.

repo_checker: project_only(): correct not published check.

---

check_source.py

Modified version of #1317 taking into account my feedback.

check_source: add hint about how to whitelist a devel projects.

---

devel-project.py
osclib/core.py
osclib/request_splitter.py
status.py

In #1370 devel-project.py was broken since it need delta.days and uses `Request` class.

osclib/core: request_age() return delta and handle Request object.

---

osc-staging.py

Example based on my response to email from Alexander regarding CaaSP staging workflow.

osc-staging: select: add filter-by example using hashtag in description.

---

leaper.py

leaper: switch off maintainer review for updates from Factory

---

leaper.py

in IBS there are no maintainers
eg ibs sr#154532

leaper: don't check maintainer for other requests in ibs

---

pkglistgen.py

Finally makes inclusion of locale specifc packages possible
https://github.com/openSUSE/libsolv/issues/231

pkglistgen: use set_namespaceproviders function

---

repo_checker.py

repo_checker: format what_depends_on as markdown bulleted list.

---

pkglistgen.py

This is specific to SLE stagings, but won't hurt in openSUSE stagings
as the products there are hand made anyway

pkglistgen: Treat stagings differently

---

CreatePackageDescr.pm

SLE uses them for some module recommending hacks

Avoid boolean dependencies for repo checker

---

pkglistgen.py

It's similiar but not the same as the droplist for openSUSE, so I created
a fork of the openSUSE command
To be called with the target project as first argument and then a
list of old projects
e.g. create_sle_weakremovers SUSE:SLE-15:GA SUSE:SLE-12-SP3:GA \
SUSE:SLE-12-SP3:Update SUSE:SLE-12-SP2:GA SUSE:SLE-12-SP2:Update ...

Add create_sle_weakremovers command

---

check_source.pl

check_source: skip checks for packages without spec file

---

create_test_Factory_dvd-2.testcase
create_test_dvds.sh

Minor adjustments in creating test DVDs for Factory Stagings

Minor changes for Factory Staging DVD generation

---

pkglistgen.py

Per @lnussel email which makes sense:
> Would be good if it could continue with the next project even if one is broken.
Will still exit with failure code and thus show as failed by systemd which seems desired.

pkglistgen: do_update_and_solve(): print exception and continue for all scope.

---

osclib/core.py
osclib/stagingapi.py
unmaintained.py

- 96f46dab5bb903af86418037ecb38c811b97aa9e:
unmaintained: tool to find umaintained binaries sourced from SLE.
- 920478b62eec80c42d8074b90f3da28470dd6a94:
osclib/core: provide source_file_load() from StagingAPI.
Fixes [poo#28815](https://progress.opensuse.org/issues/28815)

unmaintained: tool to find umaintained binaries sourced from SLE.

---

metrics/grafana/dashboard.json

- 568249b0d127a396d90f6eb6e5710dfa5d0b9fc8:
metrics/grafana/dashboard: add release schedule annotation.
- 52693a620422803f5b3834bca9cd46a29ddfbd06:
metrics/grafana/dashboard: include dashboard description.
- ed927994b2e6c27bbbe3c2696b73dbb5b2b27ace:
metrics/grafana/dashboard: change all selectors to last

metrics/grafana/dashboard: change all selectors to last (plus cleanups)

---

metrics/grafana/dashboard.json

metrics/grafana/dashboard: remove y-axis max from "Weekly Revisions".

---

config/manager_42/openSUSE:Leap:15.0.yml

- a0f7c2205089ff4913642d0d0c712ca9be8ebea3:
config/manager_42/Leap:15.0: update for Leap:15.0 source project reality.
- 28198080780918c278128d3562c9710f42bf865e:
config/manager_42/Leap:15.0: include from_proj in order to work properly.                                                              
- f233458749bdb102bab8599c3bd344fbae387d7c:                                                                                                
config/manager_42/Leap:15.0: remove duplicate SLE-workarounds entry.

config/manager_42/Leap:15.0: import packagelists changes to provide valid config.

---

manager_42.py

Created to resolve [poo#36012](https://progress.opensuse.org/issues/36012).
Should be fine to include as part of regular run and since:
```python
if project.endswith(':SLE-workarounds'):
self.sle_workarounds = project
```
should never be true for SLE itself this code will never execute there.

manager_42: check if SLE-workarounds are no longer utilized and request removal.

---

dist/package/openSUSE-release-tools.spec
systemd/osrt-staging-bot-check_duplicate_binaries@.service
systemd/osrt-staging-bot-check_duplicate_binaries@.timer

dist: provide osrt-staging-bot-check_duplicate_binaries@.service.

---

oqamaint/cli.py
osclib/accept_command.py
osclib/adi_command.py
osclib/check_command.py
osclib/check_duplicate_binaries_command.py
osclib/cleanup_rings.py
osclib/core.py
osclib/cpio.py
osclib/request_finder.py
requestfinder.py

This is just the start to experiment with the osc3 branch

Begin porting to python3 (osc branch)

---

totest-manager.py

This is supposed to be used for temporary failures that do not deserve
a carry over as they are sporadic but should not stop a snapshot release
nor are they worth it to wait a job duplicate

ttm: Allow to ignore job failures without bug reference

---

osclib/stagingapi.py
totest-manager.py

Use OBS Attribute for ignored issues

---

totest-manager.py

See https://progress.opensuse.org/issues/27735
Example Message:
```json
'opensuse.ttm.build.failed': '{
"project": "openSUSE:Factory",
"build": "20180516",
"failed_jobs": {
"relevant": [677715, 677717, 677721, 677734, 677744, 677746, 677749, 677750, 677776, 677797, 677895, 677896, 677925, 677976, 677977, 678017],
"ignored": [677719, 677722, 677725, 677742, 677770, 677772, 677773, 677873, 677889, 677900, 677972, 677978, 677979, 677985]
}
}'
```

Add AMQP support to TTM

---

oqamaint/openqabot.py

openqa-maintenance: Make sure we don't go through requests twice

---

totest-manager.py

See https://progress.opensuse.org/issues/27735

TTM: Add norelease option for use with OSD

---

pkglistgen.py

We need this to have the remains of SLE15 in OBS to build against

Generate an unsorted.group if configured

---

metrics/access/aggregate.php

Since the aggregation is not done by influxdb a fill option is not
available and instead needs to be performed manually. As such the order of
writing must be from oldest to newest so that the list of product seen
before can be kept and missing products for a given interval can be filled.

metrics/access/aggregate: write zeros for empty product data.

---

repo_checker.py

repo_checker: Fix config read/load in whitelist_clean

---

osclib/stagingapi.py
repo_checker.py

ref. https://github.com/openSUSE/open-build-service/pull/5254/commits/e80915d0c3d68c2f3988344aa282475f216e3f26

stagingapi: subprojects method has been removed from dashboard

---

openqa-comments.py
osc-staging.py
osclib/freeze_command.py
osclib/stagingapi.py
tests/obs.py

I was actually looking at openqa-comments.py

Remove more of :DVD subproject handling

---

totest-manager.py

https://progress.opensuse.org/issues/27735

Add support for SLE12SP4 and SLE15SP1

---

pkglistgen.py

Apparently accidentally did a commit --amend --all on last commit,
revert.

Remove debug code accidentally part of #1615

---

create_test_Factory_dvd-1.testcase

Another sync up with packagelists local change.

Add salt packages to DVD for Staging tests

---

pkglistgen.py

For SLE I need -s target -s staging, but it only did the later - as
I didn't figure the concept of commandline :)
please review @lnussel @jberry-suse

pkglistgen: Support multiple scopes

---

osclib/stagingapi.py

So we can use the StagingAPI also for projects below the target
project
Fixes #1626

Lazy evaluation the ring projects

---

repo_checker.py

- a61ebeef608d3cc0e01761d2537007d1d3c281f1:
repo_checker: drop whitelist_clean sub-command.
No longer needed since the whitelist is no longer managed manually.
- 3f043e968dd8445604546f5408deb61eb8517a6c:
repo_checker: determine existing problems based on project_only output.
The project level whitelist stored in config is no longer utilized, but
staging level overrides are still available.
Fixes #1630.
Note that this effectively runs with no `whitelist` for SLE != 15:GA since the `project_only` run is no longer invoked and there is no dashboard container. The following is printed in log:
```
[W] no project_only run from which to extract existing problems
```
As the dashboard container is a requirement, liked or not, it should be provided and the service enabled until it is no longer …

repo_checker: determine existing problems based on project_only output.

---

README.asciidoc

README: update coveralls badge for new repository name.

---

metrics/access/aggregate.php

Set everything up, but never filled in keys.

metrics/access/aggregate: correct empty seen key handling.

---

pkglistgen.py

Since both pkglistgen and repo_checker share the same rpm metadata cache
either may update it first and thus bs_mirrorfull will only contain output
for one of the tools. As such the check in pkglistgen could cause the solv
file to remain stale. Instead write a secondary file containing the
repository state hash and check to see if the file already exists.
Fixes #1377.

pkglistgen: compare repository state to determine when to update solv.

---

pkglistgen.py

It's not the state of the binaries, but about the build status - which
is irrelevant for package list generation. So just keep mirroring as
we used to, but instead of trusting the download we check the generated
solv file before and after. This is actually rather fast (on a VM in NBG)
and we can still skip the expensive package list generation

Move creation of the Solver object out of loop

---

osclib/core.py
pkglistgen.py

Otherwise we collect quickly a million revisions with no gain

pkglistgen: only PUT new data if it changed

---

.travis.yml
PubSubConsumer.py
consumer.py
dist/package/openSUSE-release-tools.spec
rabbit-openqa.py
systemd/osrt-rabbit-openqa.service

There is an API gap on OBS side atm, so this won't complete:
https://github.com/openSUSE/open-build-service/issues/6035

Add helper bot to listen to rabbit bus and feed OBS with openQA Status

---

check_source.py

SLE likes to be different for the sake of it.
Fixes #1483.

check_source: check if member of staging group before attempting to skip

---

osclib/adi_command.py

adi: Fix format for untracked requests

---

osclib/cache.py

Especially caching the lockedby attribute makes it basically
impossible to work with multiple persons

Reduce cache time of attributes

---

pkglistgen.md
pkglistgen.py

@DimStar77 I'll add some documentation about it, but for you to play with it:
```
OUTPUT:
- leanos:
default-support: l3
recommends: false
includes:
- sle_minimal

pkglistgen: Support a recommends flag in the OUTPUT

---

ReviewBot.py
ToolBase.py
abichecker/abichecker.py
biarchtool.py
check_maintenance_incidents.py
check_source.py
check_source_in_factory.py
compare_pkglist.py
fcc_submitter.py
leaper.py
legal-auto.py
manager_42.py
obs_clone.py
osclib/cache.py
osclib/conf.py
osclib/core.py
osclib/cycle.py
osclib/list_command.py
osclib/obslock.py
osclib/prio_command.py
osclib/repair_command.py
osclib/stagingapi.py
rabbit-openqa.py
suppkg_rebuild.py
tests/obs.py
totest-manager.py
update_crawler.py

Port more code to run under python3

---

userscript/README.md

Provide more detailed usage instructions so this can be shared and more easily understood.
Dropping mention of Greasemonkey since it does not work properly for me and thus I cannot test and @lnussel indicated minor issues. Can still use it, but for general recommend Tampermonkey since I can verify it in both Chromium and Firefox.

userscript/README: include more details about usage and troubleshooting.

---

totest-manager.py

- This should fix https://github.com/openSUSE/openSUSE-release-tools/pull/1751#issuecomment-440578557

Disable publishing for the product_repo in the test_project directly

---

osclib/cache.py

osclib/cache: remove double comment introduced in #1802.

---

metrics.py
requirements.txt
tests/metrics_tests.py

Since this has occurred a couple times I added a trivial test to ensure it will cause a [test failure](https://travis-ci.org/openSUSE/openSUSE-release-tools/jobs/461060789) in future.

tests/metrics: add basic test to ensure code is executable.

---

totest-manager.py

Add JeOS and containers to TW

---

osclib/accept_command.py

see https://github.com/openSUSE/openSUSE-release-tools/issues/1800

accept_command: add additional version number to OSRT:ProductVersion

---

rebuildpacs.pl

Reported by @antlarr and it took me a while to reverse engineer on what checkout it actually runs :(

Fix rebuildpacs to trigger rpmlint-mini on polkit changes

---

rebuildpacs.pl

installation-images was switched to multibuild quite some time ago,
adopt the rebuildpacs.

Fix rebuildpacs for installation-images

---

compare_pkglist.py

* Ignore 00* package too
* Preventing potential counts maintenance package

compare_pkglist: minor improvements

---

PubSubConsumer.py

To make sure we know if the service hangs or is still kicking

Output something every 5 minutes to show activity on the console

---

totest-manager.py

- Also fix kubic-*-image not having a maxsize, not sure how that worked
previously

Add openSUSE-Tumbleweed-Kubic images

---

ReviewBot.py
origin-manager.py
osclib/origin.py

- 21f3fcd1d57f7d3883b8923084df93018af6bb43:
origin-manager: support ReviewBot override comment using origin workaround.
- e930ea37c317e8fa648cb2d5f9d8d3ca3a67a4bd:
ReviewBot: request_override_check(): default to accept.
- d32b0c65bb6c8ecc693b02ef685c235b78f65cee:
ReviewBot: request_override_check(): provide force option.

origin-manager: support ReviewBot override comment using origin workaround.

---

totest-manager.py

- Contains JeOS and opensuse-leap-images

ttm: Add openSUSE:Leap:15.1:ARM:Images

---

totest-manager.py

Remove 15.1:ARM:Live

---

osclib/stagingapi.py

the changed the output style default from None to False
Fixes #1908

Fix compat with pyYaml 5.1

---

origin-manager.py

Per @lnussel request the annotation is duplicated and will show up twice in request interface.

origin-manager: include annotation in fallback review comment.

---

check_source.pl

Add some missing end-of-sentence periods here and there, remove
broken comma placement, fixup plural forms and "cannot" spello.

check_source: update grammar

---

gocd/staging.bot.gocd.yaml
gocd/staging.bot.gocd.yaml.erb

This really requires sharp eyes in review :(

Fix indenting - this is really hard

---

ttm/manager.py

- Crash fix
- Simplification
- Workaround for a nasty issue

Some more ttm improvements/refactoring

---

ReviewBot.py
ToolBase.py
compare_pkglist.py
deptool.py
factory-package-news/announcer.py
factory-package-news/factory-package-news.py
fcc_submitter.py
issue-diff.py
k8s-secret.py
legal-auto.py
osc-cycle.py
osc-staging.py
suppkg_rebuild.py
tests/api_tests.py
tests/comment_tests.py
tests/pkgcache_tests.py
update_crawler.py

Travis changed default python to 3.6, which has impact on the way flake8 checks. So make sure we run fine under flake8 of python 3

More porting to python3

---

ttm/publisher.py

[ttm] do not wait publishing if dryrun

[ttm] do not wait publishing if dryrun

---

userscript/origin.user.js

userscript/origin.user.js: nice icons

---

obs_operator.py

obs_operator: handle multi-level origin domains.

---

osclib/core.py
tests/OBSLocal.py
tests/fixtures/repository/SUSE:SLE-12-SP1:GA.xml
tests/fixtures/repository/SUSE:SLE-12-SP1:Update.xml
tests/fixtures/repository/SUSE:SLE-12-SP2:GA.xml
tests/fixtures/repository/SUSE:SLE-12-SP2:Update.xml
tests/fixtures/repository/SUSE:SLE-12-SP3:GA.xml
tests/fixtures/repository/SUSE:SLE-12-SP3:Update.xml
tests/fixtures/repository/SUSE:SLE-12-SP4:GA.xml
tests/fixtures/repository/SUSE:SLE-12-SP4:Update.xml
tests/fixtures/repository/SUSE:SLE-12-SP5:GA.xml
tests/fixtures/repository/SUSE:SLE-12-SP5:GA:Staging:A.xml
tests/fixtures/repository/SUSE:SLE-12:GA.xml
tests/fixtures/repository/SUSE:SLE-12:Update.xml
tests/home/.oscrc
tests/repository_tests.py
tests/select_tests.py

The way OBS collapses repositories is different to what we did

Fix and test repository_path_expand on SLE12-SP5

---

PubSubConsumer.py

Close the rabbit connection more carefully

---

web/origin-manager/main.js

Useful in main lookup table when loading from external link.

web/origin-manager: scroll to value after selecting.

---

factory-package-news/factory-package-news.py

https://github.com/openSUSE/openSUSE-release-tools/pull/1962
ported factory-package-news in a way to Python 3.x that made
it completely crash immediately with Python 2.x. So I guess
it is time to flip the switch and change the shebang. Also
fix the remaining fallout so that at least save and diff
are working again.

Fix factory-package-news to work with Python 3

---

gocd/checkers.opensuse.gocd.yaml
gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb
legal-auto.py

Run legal-auto on botmaster as well

---

gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb
gocd/staging.bot.gocd.yaml
gocd/staging.bot.gocd.yaml.erb

Run staging bot now in python3 as well

---

osclib/accept_command.py

Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2055

virtually accept: fix string type handling in Python3

---

gocd/checkers.opensuse.gocd.yaml

Run check_source_in_factory on gocd

---

legal-auto.py

The pickle hash was not reliable - so it took way too long to reimport

Fix projects import into legaldb

---

osclib/stagingapi.py

Right after commit of a package into a staging project, it can happen that OBS replies to GET with 'service in progress' and then we don't get a file list. As we ignored that exception, we did not create the
other spec files.
Now enhance retried_GET to look for this condition and retry this as well, so we get reliable package list.

Fix support for multiple spec files

---

gocd/checkers.opensuse.gocd.yaml

Switch reviewer factory-auto from group to user

---

gocd/checkers.opensuse.gocd.yaml
gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb

We want to switch away from pointless groups

Support licensedigger as reviewer for SUSE and openSUSE

---

osc-staging.py
osclib/stagingapi.py

Remove --add from select command

---

gocd/rebuild-trigger.gocd.yaml

We wanted to get rid of factory-repo-checker
Fixes #2103

Switch rebuildpac user to factory-maintainer

---

ttm/publisher.py

ttm: remove code to update pinned openQA comment

---

osclib/repochecks.py

Readd whitelist for installcheck

---

gocd/sp2.target.gocd.yaml

Change pipeline target from SLE15-SP1 to SLE15-SP2.

Change target from SLE15-SP1 to SLE15-SP2

---

gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb
gocd/sle15sp2-stagings.gocd.yaml
gocd/sle15sp2-stagings.gocd.yaml.erb

- staging plugin needs to be linked
- staging reports need to be written as staging-bot

Fix SP2 config

---

config/manager_42/openSUSE:Leap:15.2.yml

Follow-up to #2130 since it was merged before @nilxam feedback.

config/manager_42: add previous Leap :Update and :NonFree 15.2.

---

gocd/checkers.opensuse.gocd.yaml
gocd/pkglistgen.opensuse.gocd.yaml
gocd/pkglistgen.opensuse.gocd.yaml.erb
gocd/pkglistgen_staging.gocd.yaml
gocd/pkglistgen_staging.gocd.yaml.erb
gocd/rebuild-trigger.gocd.yaml
gocd/staging.bot.gocd.yaml
gocd/staging.bot.gocd.yaml.erb
gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

More related to [poo#52094](https://progress.opensuse.org/issues/52094).

gocd: update 15.1 jobs to 15.2.

---

gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb
gocd/rebuild-trigger.gocd.yaml
project-installcheck.py

For SLE we run it --no-rebuild, for openSUSE check also rebuilds

Combine project_only and rebuild into check

---

gocd/rebuild-trigger.gocd.yaml

Add rebuild trigger for openSUSE:Factory:ARM

---

userscript/origin.user.js

- 45d065b027867b9c67097e3e1458b005b3bd83cf:
userscript/origin: update release request handling.
- 249a35efe6be9ebbf516fc4c5969cdc33e9cb767:
userscript/origin: hide request card when no OSRT:OriginConfig.
- 941859bc3c245ce5c88780a3caed226f98abe0ff:
userscript/origin: update request card column xpath.
OBS changed their page layout and broke this.

userscript/origin: restore request origin lookup.

---

gocd/checkers.opensuse.gocd.yaml

gocd: include :NonFree in OS.Origin.Manager.Update.

---

check_source.py

We want to turn some rpmlint errors into warnings and make them only mandatory in official project. We'll handle this via a review. Add logic to add reviews if warnings for missing whitelist entries are present in submits

check_source: add a review for the security team if there are warnings about missing

---

osc-origin.py

osc-origin: update: indicate which package is being checked.

---

gocd/openqa.gocd.yaml
openqa-maintenance.py
oqamaint/cli.py
oqamaint/openqabot.py
oqamaint/opensuse.py
oqamaint/suse.py

Run openqa-maintenance on botmaster as well

---

factory-package-news/factory-package-news.py

This will fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2216

factory-package-news: fixes for Tumbleweed

---

osclib/core.py

- c93d2d2ffabb860af03ae31aaee5bdff7ac7c7fe:
osclib/core: rename request_action_single_list() to request_action_simple_list().
- 542268af34a1c9f554d311b2e4dbb04eb0dd1f0c:
osclib/core: switch request_action_single_list() users to request_action_list().
- 0bc8a52aca625f161f778d4159fa868b9728c9b6:
osclib/core: request_action_single_list(): handle miltiple actions.
- 341bae564d461369639f6ef9d157230b0a6913fa:
osclib/core: request_action_single_list(): exclude sourced requests.
Works for [request 70524 for rpmlint](https://build.opensuse.org/request/show/70524) which used to cause exception.
Originally:
```
$ osc origin -p openSUSE:Factory history rpmlint
File "/usr/bin/osc", line 41, in <module>
r = babysitter.run(osccli)
File …
```

osclib/core: request_action_single_list(): exclude sourced requests and handle miltiple actions.

---

gocd/sp2.target.gocd.yaml

Package was renamed in SLE-15-SP2.

Replace kiwi-templates-SLES15-JeOS with kiwi-templates-JeOS

---

gocd/sp2.target.gocd.yaml

Added new SLED-15-SP2-Vagrant and SLES-15-SP2-Vagrant in release to TEST
setup for SLE-15-SP2

Added Vagrant box in 15-SP2 release tool

---

build-fail-reminder.py

build-fail-reminder: Fix indentation of emails

---

dist/ci/docker-compose.yml
tests/OBSLocal.py
tests/fixtures/oscrc
tests/test.oscrc

Make the CI green again

---

osc-origin.py
osclib/origin_listener.py

Avoids special cases where package_kind() differs by project.
Fixes #2293.

osc-origin,osclib/origin_listener: sync package kind logic.

---

userscript/origin.user.js

userscript/origin: handle HTTP failure.

---

dist/obs/OSRT:OriginUpdateInitialBlacklist.xml
osc-origin.py
osclib/origin.py
tests/origin_tests.py

- 1d1df94cdb7e8d6e19bf071148435e2d12b01d41:
osclib/origin: origin_update(): support blacklist patterns for initial updates.
- dd31e02bcc1a68abd6acdb6977d82c178e6c2bd3:
osc-origin: extract osrt_origin_update_packages().
Follow-up based on submissions from #2287.
Derived initial blacklist patterns from recent declined requests.
```
.*SLE.*
.*SLED.*
.*SLES.*
.*suse-manager.*
.*spacewalk.*
kernel-livepatch-.*
system-role-.*
sca-.*
patterns-server-enterprise
unified-installer-release
```
Which will remove the following packages from consideration.
```
.*SLE.*
remvoing skelcd-control-SLES matching .*SLE.*
remvoing kernel-livepatch-SLE15-SP1_Update_0.13010 matching .*SLE.*
remvoing SLES15-SP1-SAP-Azure-BYOS matching .*SLE.*
remvoing kernel-livepatch-SLE15_Update_3 matching .*SLE.*
remvoing …
```

osclib/origin: origin_update(): support blacklist patterns for initial updates.

---

docs/origin-manager.md

docs/origin-manager: provide comprehensive documentation.

---

osclib/conf.py
osclib/unselect_command.py

anything else needs to be defined in attribute

unselect: only set origin-manager for whitelist cleanup

---

osc-staging.py
osclib/unselect_command.py

You can't have requests excluded and staged at the same time

Fix for unselect with message: need to ignore afterwards

---

osclib/stagingapi.py

we decided to drop the `number` as it's `id` everywhere else

Adopt to latest API changes

---

metrics.py
osc-staging.py
osclib/accept_command.py
osclib/adi_command.py
osclib/conf.py
osclib/request_splitter.py
osclib/stagingapi.py
tests/config_tests.py

Prepare NonFree as onlyadi project, so it can have its own staging workflow

Remove nonfree handling

---

osclib/repair_command.py

I hope to ditch it soonish, but OBS needs to change its behaviour on unselect first

Repair repair command

---

check_source.py

check_source: query all repos if source info yields error

---

osclib/accept_command.py

Only check for the rebuild project if cbuild has been set

---

osc-staging.py
osclib/accept_command.py

There is no error reported yet, just output

Reuse function of accept to check local links

---

gocd/announcer.gocd.yaml
gocd/announcer.gocd.yaml.erb

Align the announcer config with the template

---

osc-staging.py
osclib/prio_command.py

Fix setprio command to use current API

---

osclib/accept_command.py
osclib/adi_command.py

This is merely an experiment to shorten the time that packages end up in ready lane

No longer close acceptable adi stagings

---

gocd/rabbit-openqa.py

Fixing microos and kubic both having a 'container-host' test. We only differ them because they run on different machines. If that changes one day, we have to rename one
CC @DimStar77

Unify openqa checks over multiple ISOs

---

osclib/accept_command.py

Do not return after adi project is accepted

---

osclib/stagingapi.py

Fixes: https://github.com/openSUSE/openSUSE-release-tools/issues/2370

stagingapi: StagingAPI doen't initial api itself

---

project-installcheck.py

tested manually via a copy of the original project

More rebuild script fixes for ARM

---

gocd/sp2.target.gocd.yaml

Added SLES15-SP2-CHOST-BYOS and SLES15-SP2-on-demand in release to TEST
setup for SLE-15-SP2

Added new packages in 15-SP2 release tool

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

Drop openSUSE:Leap:15.0:Images from ttm list

---

dashboard/generate.py
dashboard/output/.gitignore
dashboard/templates/dashboard.html
gocd/dashboard.generator.gocd.yaml

https://factory-dashboard.opensuse.org/ - updated every 5 minutes from botmaster

Rapid prototype of a Factory dashboard

---

dist/package/openSUSE-release-tools.spec
metrics.py

influxdb is no longer provided for python2

Switch metrics to use python3

---

gocd/monitors.gocd.yaml
gocd/notify-obs_rsync.py

This will be triggered on gocd if there are changes in the finished
repositories, checks the important repositories and notifies openQA

Sync script for obs_rsync

---

pkglistgen.md
pkglistgen/group.py

Support 'required' field for packages

---

check_source.py

If the package name as reported by OBS does not match the one
we're expecting, then loop through all repositories and check
if we find one there.
This is weakening the policy a little as this will open the
door for false negatives - e.g. that got the right package name
only for another repository. But as we do submission between
code streams all the time, I can't limit the package parsing
to repositories building against the target. So the opened
hole is to be closed by sanity check on review-team - as a
matter of fact the policy is not to catch people playing
macro games around Name, but for people that use completely
different names in source and target.
Fixes #2274

Fix check_source for repository specific package names

---

osclib/stagingapi.py
tests/OBSLocal.py
tests/origin_tests.py
tests/select_tests.py

Wipe all multibuild flavors for delete requests

---

tests/factory_source_tests.py

Looks like OSC in Tumbleweed changed behaviour of internal functions

Fix httpretty using tests

---

pkglistgen/tool.py

Signed-off-by: Egbert Eich <eich@suse.com>

Check for 'weakremovers.inc' in in group_dir before attempting to move it

---

gocd/rebuild-trigger.gocd.yaml

I don't have access there to recover the build, which is in a pretty
bad state atm. lets see if the bot would have enough privileges to be
able to do so.

Trigger rebuilds on zSystem as needed

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

* Needed for wsl publishing to :ToTest

Add openSUSE:Leap:15.2:WSL under gocd control

---

gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb
gocd/microos-stagings.gocd.yaml
gocd/microos-stagings.gocd.yaml.erb
gocd/microos.target.gocd.yaml

Add MicroOS setup

---

dashboard/generate.py

Dashboard: Handle 'locked' state for OBS

---

gocd/microos.target.gocd.yaml

Add release to TEST and PUBLIC for MicroOS

Add release to TEST and PUBLIC for MicroOS

---

dashboard/generate.py
dashboard/templates/repository.html

It will fix `ARM Ring 0` stats.
Tested locally.

Dashboard: Handle 'broken' state for OBS

---

ttm/releaser.py

This is to avoid that added container images or appliance flavors are never
released due to the missing config addition.
This actually fails for `openSUSE:Factory` currently:
```
ERROR:ttm.manager:ceph-grafana-image is built for x86_64, but not mentioned as product
ERROR:ttm.manager:kubic-velero-image is built for x86_64, but not mentioned as product
ERROR:ttm.manager:openSUSE-MicroOS:ContainerHost-SelfInstall is built for x86_64, but not mentioned as product
ERROR:ttm.manager:openSUSE-Tumbleweed-Yomi:livecd is built for x86_64, but not mentioned as product
ERROR:ttm.manager:openSUSE-Tumbleweed-Yomi:pxeboot is built for x86_64, but not mentioned as product
ERROR:ttm.manager:opensuse-openldap-image is built for x86_64, but not mentioned as product
```
Same for `openSUSE:Jump:15.2`:
``` …
```

TTM: Verify that all successfully built products are mentioned in the config

---

ttm/README.md

Not exhaustive documentation, but covers the most relevant parts.

Add a readme about TTM

---

gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb

Maintenance asked to add back 15SP1 quarterly updates because they have a request to update it

Add back setup for 15SP1 quarterly updates

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

And drop Jump. Also fix the erb file, which wasn't used to enable Leap 15.3.

Enable TTM for openSUSE:Leap:15.3:Images

---

pkglistgen/tool.py

Not updating the product in case of failure is preferred over creating bogus products
Fixes #2517

pkglistgen: Check the return code of Popen calls

---

gocd/sp3.target.gocd.yaml

Stage will finish when all images were published

Monitor release process

---

metrics/access/ingest.php
metrics/access/sample_download_o_o.conf

couldn't test this live, just using a faked setup (#2526)

metrics: accept more flavors

---

check_source.py
osclib/stagingapi.py
ttm/README.md
ttm/publisher.py
ttm/releaser.py
ttm/totest.py

Support for Dockerfile builds

---

data/apimap.json
data/incidents.json
data/repos.json

Following: https://progress.opensuse.org/issues/72202
For now I don't know how to test it, so directions would be great :)

Add Leap 15.3 Maintenance configuration

---

legal-auto.py

The churn rate of openSUSE:Factory is too high for legal to catch up
these days, so we turn the default. Legal reviews for Factory are no longer
blocking, but if we need the same package for another project or
product, the lawyers had some time to look at it.
And if we find a package not acceptable, we'll delete it from Factory
later on. This may get painful, but the current legal situation is
painful too.

legal: Only wait 2 hours for legal reviews for openSUSE:Factory

---

gocd/sp3.target.gocd.yaml

Introduce a different route for publishing sles15-image.

Release SUSE:SLE-15-SP3:GA sles-image into :TEST and :PUBLISH

---

gocd/sp3.target.gocd.yaml

All images are now available in images repository

Remove release from images-ndb repository

---

docs/check_source.asciidoc
docs/factory-source.asciidoc
docs/maintbot.asciidoc
docs/metrics.md
docs/staging.asciidoc
docs/testing.asciidoc

gendered terms, and some minor grammar edits, mostly along with them, but a few others nearby as well

grammar-and-gender

---

data/apimap.json
data/incidents.json
data/repos.json
oqamaint/update.py

This commit contains the necessary configuration and code changes. The products
referenced by them have also been created on openqa.opensuse.org

Add Backports to the updates being tested

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

- Leap:15.3 is frozen, drop it
- Add 15.3:WSL and :ARM:Images

gocd/totestmanager.gocd.yaml: Update list of projects

---

check_source.py

whitelist warning was suppressed)

check_source.py: Add the reason why a review was added (e.g. which

---

docs/staging.asciidoc
osc-staging.py

Staging: add 'rebase' as an alias to the 'freeze' command

---

check_source.pl
dist/ci/docker-compose-flaker.sh
dist/ci/perl-check.sh

Is that check_source.pl used at all? Some bugs in it looks bad enough, especially that regexp.

Perl linter

---

dist/ci/docker-compose-test.sh
dist/ci/testenv-tumbleweed/Dockerfile
tests/checktags_tests.py

experimental switch to run tests with pytest

use pytest instead of nosetests

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

gocd: Drop openSUSE:Factory:WSL

---

docs/processes.md

Fix header level in processes.md

---

tests/OBSLocal.py
tests/check_source_tests.py

- Documentation of OBSLocal extended and adapted to Python's standard format (reStructured Text).
- Added new methods to `OBSLocal.Project` to extend the current management of meta information
- Bonus: small fixes in `check_source_test.py`

Document and extend OBSLocal

---

skippkg-finder.py

The extra packages are packages should be skipped in ftp-tree but we won't for some reasons, packagelist is not fixed depend on package status in SLE side, move the list to OSRT attribute avoiding modify this list so often.

skippkg-finder: move extra packages to the OSRT attribute

---

gocd/rabbit-openqa.py

Those tests shouldn't influence staging results.

rabbit-openqa.py: Ignore PR verification runs with / in BUILD

---

gocd/pkglistgen.opensuse.gocd.yaml
gocd/pkglistgen.opensuse.gocd.yaml.erb
gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb
skippkg-finder.py

* Added an alternative_project option to skippkg-finder
* Added openSUSE:Leap:15.3:Update:Respin to ttm, pkglistgen and updaterepos

Enabling for openSUSE:Leap:15.3:Update:Respin

---

legal-auto.py

The query_sources function is only used for product scan, which is not
relevant for request review. Fixing it to improve performance on live
patch reviews.

 legal-auto: Move the "ignore channels" feature in the proper function

---

dashboard/templates/dashboard.html

[Screenshot](https://paste.opensuse.org/view/raw/99072451)

Dashboard: Add containerfile

---

osclib/core.py

For some setups that have recursive paths we run into an endless
loop. Adding a visited project tracking to break the loop of expansion.

pkglistgen: Handle loops in project path expansion

---

dashboard/generate.py
dashboard/templates/dashboard.html
gocd/dashboard.generator.gocd.yaml

Screenshot: https://paste.opensuse.org/view/raw/8383a272

Add a dashboard for Leap

---

gocd/monitors.gocd.yaml

For https://github.com/os-autoinst/openqa-trigger-from-obs/pull/151

gocd: Monitor KDE:Medias as well

---

gocd/vagrant-publisher.gocd.yaml
gocd/vagrant-publisher.gocd.yaml.erb

gocd: Add Leap 15.4 vagrant boxes

---

osc-staging.py
osclib/select_command.py
osclib/stagingapi.py
tests/select_tests.py

The API errors with that option if a request is ignored, so we have to
support it.
Fixes #2374

Introduce --remove-exclusion for staging select

---

staging-report.py

Include request submitters in staging report

---

factory-package-news/factory-package-news.py

This fixes the multi-megabyte "New Tumbleweed snapshot" mails if the changelog comparison can't find a common changelog entry to stop at, or if a package simply has a really big changelog since the last submit request.
WARNING: I don't have test data to test my changes, therefore I wrote the truncation code more or less blindfold. In theory it should work, but in practise I'd seriously recommend to test it before merging this pull request.

truncate overlong changelogs to 100 lines + last line

---

docs/staging.asciidoc
osc-staging.py
osclib/request_finder.py
osclib/select_command.py

osc staging select --move adi:26 adi:14
If move is given, all staging projects given after the first will be seen as source
Fixes #1105

Support to move one staging into another

---

osc-staging.py

staging: consider first staging a target even without --move

---

osclib/freeze_command.py

freeze: Copy weakremovers.inc from target project to avoid bitrot

---

docs/origin-manager.md

I decided not to reduce it's code because no one knows what the future
will bring exactly (and only then we should decide), but I'll close the
tickets mostly.

docs: Add note that the origin manager is unmaintained

---

pkglistgen/tool.py

Since 30daff5613803667be7422056431116e84c07d59 we check if the repos are
still what we expected them to be when we started and stop calculating
weakremovers.inc if the build didn't stay still for the full runtime of
the pkglistgen. But the exception makes it impossible to spot real
failures - so make this a regular exit

pkglistgen: Don't exit 1 if we skip weakremovers due to restarted builds

---

staging-installcheck.py

Installcheck: Ignore requires to packages with delete requests

---

staging-installcheck.py

It's just very annoying otherwise

installcheck: Report all delete requests

---

.github/workflows/ci-test.yml
dist/ci/docker-compose-test.sh
dist/ci/docker-compose.yml
tests/accept_tests.py
tests/api_tests.py
tests/check_source_tests.py
tests/origin_tests.py
tests/select_tests.py

A test run of 40 minutes is just too much to wait for

CI: Split the tests in multiple runs

---

tests/check_source_tests.py

Check_source supports multiple different target projects only
different by their remote config. So put this config into a fixture,
so we can mark every test with what config it should run

tests: Make use of fixtures to be able to test different workflows

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

We have a publishing set up from :ToTest, now let's add the ttm workflow for it.

Add TTM workflow for Leap Micro 5.2

---

pkglistgen/tool.py

This is the next step towards having multiple submissions to SLE stagings

pkglisten: Generate a comment for staging diffs

---

gocd/rebuild-trigger.gocd.yaml

The updates are merged in the main repository already, no need
to trigger them separately

remove rebuild trigger for openSUSE:Step:*Update

---

staging-installcheck.py

It looks a little confusing to the untrained eye

installcheck: Annotate the duplicated binaries yaml

---

pkglistgen/tool.py

To allow passing multiple staging projects without force accepting
(https://github.com/openSUSE/openSUSE-release-tools/issues/1833)

pkglistgen: pass the test if the comment was replied to with 'ignore'

---

osclib/stagingapi.py
tests/OBSLocal.py

Stay with minversion 3.6 (and require module we already use elsewhere)

---

build-fail-reminder.py
osclib/util.py

Repo checker escalation 

---

staging-installcheck.py

Untyped languages really deserve to die

staging-installcheck: Fix syntax error

---

build-fail-reminder.py

- Load the fails from rebuildpac data, which is more reliable than the
broken project status route of OBS.
- Correctly report multispec failures
- Correctly report i586 failures
- Include unresolvable packages in the report

build-fail-reminder: Several enhancements

---

metrics/access/aggregate.php

New aggregation intervals have been introduced calculating statistics over fiscal quarter and year.
Implements: https://progress.opensuse.org/issues/109118

Add aggregates for fiscal quarter and year

---

osclib/freeze_command.py
tests/freeze_tests.py

Keep images repository disabled on freeze command

---

gocd/monitors.gocd.yaml

openQA/OBS sync related PR: https://github.com/os-autoinst/openqa-trigger-from-obs/pull/160/files

Add automatic notifications for D-Installer

---

osclib/accept_command.py
osclib/core.py
tests/accept_tests.py

CC @suntorytimed (untested in real life, but the test case should cover us)

Accept_command: create set_bugowner requests

---

osclib/accept_command.py

accept: Catch requests without description

---

metrics/access/aggregate.php

Aggregations are comparable to each other only at the end of the interval. The point will be written to database only if the new aggregation period has just started.

Write points to the DB only at the end of interval

---

dashboard/generate.py

And fix openqa ID for openSUSE:Leap:Micro:5.2

dashboard: Add openSUSE:Leap:Micro:5.2:Images

---

gocd/sp4.target.gocd.yaml

Limited to only container packages to be released to :TEST. Previously
all packages were being released.

Fix packages released to containers repo

---

.noserc
dist/package/openSUSE-release-tools.spec
docker_publisher.py
docker_registry.py
gocd/dockerhub-publisher.yaml
systemd/osrt-docker-publisher.service
systemd/osrt-docker-publisher.timer

This bot runs every 15 minutes and compares the version of Leap 42.3, 15.0 and TW containers with the ones on the registry and pushes, if necessary.

Introduce a new docker-publisher bot

---

osclib/freeze_command.py

freeze: fix crash when rebasing staging that was earlier enabled by stagingbot

---

dashboard/generate.py
gocd/leapmicro.target.gocd.yaml
gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

Continuation of https://progress.opensuse.org/issues/113024

Add LeapMicro 5.3 bot configuration

---

CONTENTS.md
dist/package/openSUSE-release-tools.spec
publish_distro
publish_distro_conf/README.md
publish_distro_conf/publish_leap-micro52.config
publish_distro_conf/publish_leap-micro52_appliances.config
publish_distro_conf/publish_leap-micro53.config
publish_distro_conf/publish_leap-micro53_appliances.config
publish_distro_conf/publish_leap150_jeos.config
publish_distro_conf/publish_leap150_live.config
publish_distro_conf/publish_leap151.config
publish_distro_conf/publish_leap151_jeos.config
publish_distro_conf/publish_leap151_live.config
publish_distro_conf/publish_leap152.config
publish_distro_conf/publish_leap152_jeos.config
publish_distro_conf/publish_leap152_live.config
publish_distro_conf/publish_leap153.config
publish_distro_conf/publish_leap153_appliances.config
publish_distro_conf/publish_leap153_live.config
publish_distro_conf/publish_leap154.config
publish_distro_conf/publish_leap154_appliances.config
publish_distro_conf/publish_leap154_live.config
publish_distro_conf/publish_leap155.config
publish_distro_conf/publish_leap155_appliances.config
publish_distro_conf/publish_leap155_live.config
publish_distro_conf/publish_tumbleweed.config

Suggested in https://github.com/openSUSE/publish_distro/issues/13 to separate tool and configuration.

Move publish_distro 817e024 into openSUSE-release-tools

---

check_source.py

New features
* If package does exist in SLE, decline the submission
Note: release manager can override it by commenting on reviewbot and reopen the request
* Decline the submission if package does not exist in `devel-baseproject` and the
source project does not exist in `check-source-valid-source-origins` attribute
* check_source adding a review-team group review if source project does not exist in `check-source-valid-source-origins attribute`
* If submitter is not maintainer adding an additional devel project review
New added attributes
* check-source-ensure-source-exist-in-baseproject: bool
* check-source-devel-baseproject: str
* check-source-allow-source-in-sle: bool
* check-source-sle-project: str
* check-source-allow-valid-source-origin: bool
* check-source-valid-source-origins: …

check_source: expand check_source be able to handle Leap/Backports submission

---

check_bugowner.py
tests/check_bugowner_tests.py

workaround for https://github.com/openSUSE/open-build-service/issues/13010

Ignore starting white space in bugowner lines

---

git-importer.py

Don't track files as LFS if they are known to the database as text mimetype
Mainly targetted at https://gitea.opensuse.org/rpm/llvm/src/branch/factory/README.packaging, but very likely other large text files are affected as well (and probably we could reduce the exception list, but I don't see a reason why now)

Make text files always !LFS

---

git-importer.py

Ignore delete requests (that got restored)

---

git-importer.py

We also need to ignore devel->devel submissions, they are not really branch merges.
Test case: bindfs' 1st revision

Refactor the evaluation of merge requests

---

git-importer.py

Don't treat any random network glitch as broken revision (which leads to ignoring it, changing the whole tree). The VM the importer runs on has some network outage bursts unfortunately, so we need to be defensive

Fix import determinism

---

git-importer.py

Test case: texlive-specs-* - they point to a different package that we don't import, so the merges are random

Re-download the accepted revisions to be on the safe side

---

git-importer.py

These are project specific "meta packages"

Import packages without devel project

---

gocd/alp-stagings.gocd.yaml

add configuration for ALP staging

---

gocd/pkglistgen.opensuse.gocd.yaml
gocd/pkglistgen.opensuse.gocd.yaml.erb
gocd/rebuild-trigger.gocd.yaml
gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/4OIMNHRDMSRLUNZRA5OPHMVSPXRRQVSB/

gocd: Add configuration for openSUSE:Factory:LegacyX86

---

publish_distro

* we have to set it to 0 avery single time when we're doing some debuging on pontifex and such approach leaves dirty checkout
* let's add users option to override it

publish_distro add  --now to set PUBLISH_DELAY=0

---

gocd/rabbit-openqa.py

See the added comment in update_staging_status.

Handle special DVD+Image BUILD values in SLE Micro Staging jobs

---

dashboard/generate.py
gocd/leapmicro.target.gocd.yaml
gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb
publish_distro_conf/publish_leap-micro54.config
publish_distro_conf/publish_leap-micro54_appliances.config

* disable any previous pipenlines, we only produce images for the currently developed ones

Add LeapMicro 5.4 pipelines

---

gocd/pkglistgen.opensuse.gocd.yaml
gocd/pkglistgen.opensuse.gocd.yaml.erb

* For now let's just make sure we can generate ftp-trees
* It's based on the existing LeapMicro pipeline

Initial pkglistgen bot for Leap16

---

skippkg-finder.py

In some cases we would not like to add package to ftp-tree on an specific arch, this can be done by multiple 'group' to be defined in NON_FTP_PACKAGES.group, however NON_FTP_PACKAGES.group is auto-generated by skippkg-finder according the buildresults and the project attributes, this commit will add conditionals support to skippkg-finder, in other words, to be able to define arch dependent package in NON_FTP_PACKAGES.group via the project attribute.
To enable it, 'use group' is also needed to be existsed in the product file, the available condition/platform can be found in meta pacakge.

skippkg-finder: add conditionals support for the product ftp-tree

---

pkglistgen/update_repo_handler.py

Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/2938

pkglistgen: handle published repos using sha512 nistead of sha256

---

staging-installcheck.py

Also consider its multibuild flavors for deletion.

Handle deletion of packages with _multibuild (#2943)

---

CONTENTS.md
repo2fileprovides.py

Script to generate necessary FileProvides lines needed by OBS from repo data.
OBS doesn't want to do it itself, so we'll have to take care of it...

Add repo2fileprovides.py

---

dist/package/openSUSE-release-tools.spec

And remove a duplicate mention while at it.

dist: Package osrt-repo2fileprovides

---

docker_publisher.py

Let's see whether #2951 worked.

docker_publisher.py: Add 15.5, remove 15.3

---

metrics/access/ingest.php

These log entries should not be counted.

Filter out access logs with error code

---

staging-installcheck.py

It's possible that OBS says that A provides cap required by B, but for B it does not show that cap is required or that cap is even provided by A. Detect and handle that explicitly.

staging-installcheck.py: Detect some edge cases in check_required_by

---

dist/package/openSUSE-release-tools.spec
gocd/alpmicro.target.gocd.yaml
gocd/generate.sh

Initial PR for handling the release of ALP Micro images / repos

Add ALP Micro image release

---

gocd/monitors.gocd.yaml

https://progress.opensuse.org/issues/130709
https://github.com/os-autoinst/openqa-trigger-from-obs/pull/217

Add prefix for agama so botmaster notifies openQA about builds

---

dist/ci/testenv-tumbleweed/Dockerfile

Needed by some scripts and tests.

dist: Add python3-requests

---

gocd/bci.gocd.yaml
gocd/bci.gocd.yaml.erb

Right in between the 9:15 and 9:30 triggers.

gocd: Run BCI RepoPublisher at 9:23 daily

---

gocd/checkers.suse.gocd.yaml
gocd/checkers.suse.gocd.yaml.erb

add install checker for 15 SP5

added QU 15 SP5

---

publish_distro_conf/publish_leap-micro55.config
publish_distro_conf/publish_leap-micro55_appliances.config

Provide publish_distro configs for Leap Micro 5.5, these were already deployment but I forgot to commit them.

publish_distro config for Leap Micro 5.5

---

check_source.py

All submissions must be reviewed before they can be accepted.

check_source.py: Add review-team review on meta packages

---

gocd/alp-stagings.gocd.yaml
gocd/alp-stagings.gocd.yaml.erb

This reverts commit 19153a2b67c8386399b4d9fd2ef2f86207837998.

Revert "Temporary disable checks for ALP"

---

dist/package/openSUSE-release-tools.spec
factory-package-news/factory-package-news.py

It's less than 1/3rd of the uncompressed size.

factory-package-news.py: Compress data files with zstd

---

data/apimap.json
data/incidents.json
data/repos.json

https://progress.opensuse.org/issues/133220

Maintenance setup for Leap 15.6

---

metrics/access/aggregate.php
metrics/access/ingest.php

Access logs for both protocls are now stored in a single file. The change refactors the code to handle it properly. 
InfluxDB client has been upgraded.

Add IPv4 and IPv6 handling in one file

---

pkglistgen/tool.py

The summary dictionary used to create summary-{scope}.txt was
previously returned by solve_project() via write_all_groups().
After c46dd3e304d8e66e5f8f6a51bfa3ebda8cba8936, solve_project()
doesn't return anything anymore, as write_all_groups() is being
invoked just after solve_project().
Thus, the "summary" dictionary would always be None.
Since the summary dict creation is generic enough, move it
to its own function, and call it afterwards after project
solving.
This commit also drops the return statement both on write_all_groups()
and write_productcompose() (where it would always return an empty
dictionary), and moves the write_productcompose() call after
solve_project() as well to match the change with write_all_groups().

pkglistgen: tool: decouple summary dict creation

---

gocd/microos.target.gocd.yaml

Add release target for SLCS 6.0

add SLCS 6.0

---

gocd/microos.target.gocd.yaml

don't try to publish SLCS images, there are none

SLCS has no images

---

gocd/slfo-stagings.gocd.yaml
gocd/slfo-stagings.gocd.yaml.erb

This is a temporary change required to generate SLFO pkglists.

gocd: Allow SLFO to have pkglists generated.

---

ttm/releaser.py

See commits for details.
From 1min15s to 0min10s!

Make ttm release faster and errors more useful

---

.github/workflows/ci-test.yml

Noone looks at the data, we don't need to upload it

Remove codecoverage reporting

---

gocd/leapmicro.target.gocd.yaml
publish_distro_conf/publish_leap-micro60.config

I'd like to use 000productcompose for Leap Micro 6.0 after talking to maintenance team. Let's make sure pkglistgen works for it.

LeapMicro 6.0 pkglistgen for 000productcompose

---

gocd/rabbit-openqa.py

The SL Micro Maintenance effort has removed isos from staging, which means there was nothing to trigger openqa on anymore. trigger on the spdx description instead.

Also consider spdx.json an iso for the purpose of openQA

---

pkglistgen/group.py
pkglistgen/tool.py

Makes the code slightly more condense and easier to read

Use f-strings where possible

---

osclib/stagingapi.py

Fixes https://github.com/openSUSE/openSUSE-release-tools/issues/3132

Fix makeurl() usage in is_repo_dirty()

---

gocd/slfo-stagings.gocd.yaml
gocd/slfo-stagings.gocd.yaml.erb

Follow up to 4c1d7be5d10457fa4a1545cebef79275d09345cf
Sorry about that... :facepalm:

gocd: slfo-stagings: properly escape comments

---

publish_distro_conf/publish_leap-micro61.config
publish_distro_conf/publish_leap-micro61_appliances.config

Add Leap Micro 6.1 publish_distro configs.

Add Leap Micro 6.1 publish_distro configs

---

gocd/rabbit-openqa.py

After the latest changes of product-composer (allowing to build isos with different names than ftp trees), the sbom assets are no longer saved in the root of the repo (as they are for SLFO 1.0) and now live in the iso folder as well.
So look for those assets in both places.

Look for images and sbom assets also in the iso/ folder

---

gocd/slfo-stagings.gocd.yaml
gocd/slfo-stagings.gocd.yaml.erb

This remove pipeline steps needed during product development:
* Updating of release packages
* re-generation of 000product content Re-add other staging letters.

Adjust the staging configuration of ALP to maintenance needs

---

devel-project.py

If the target project of a submit request is part of 'reminder-once-only-target-projects', devel-project should skip to update reminder comment if there is a one already.

devel-project: skip to update reminder repeatedly for particular projects

---

gocd/slfo-stagings.gocd.yaml
gocd/slfo-stagings.gocd.yaml.erb

- We don't change the list of packages in stagings during maintenance

Remove unecessary packagelist status report from SLFO 1.1

---

check_bugowner.py
tests/OBSLocal.py
tests/home/.oscrc
tests/test.oscrc

See individual commits for details.

Various fixes for CI

---

osclib/core.py

This is used as a backstop for packages that have had their pkg meta removed in OBS.

devel project info for Factory moved to prjgit

---

devel_update.sh
dist/package/openSUSE-release-tools.spec

script to manage src.opensuse.org/openSUSE/Factory devel_packages

add devel_update.sh for git-based Factory

---

gocd/totestmanager.gocd.yaml
gocd/totestmanager.gocd.yaml.erb

Same as 6.1 without dedicated :Images

Add Leap Micro 6.2 TTM pipeline

---

staging-installcheck.py

By calling the install checker as
> ./staging-installcheck.py -p home:dimstar:Factory --devel home:dimstar:Factory -r openSUSE_Factory
We can allow developers to use installcheck against devel projects

staging-installcheck: allow checking random devel projects

---

check_maintenance_incidents.py

Attempting to add a package in an scmsync project as reviewer fails with error 400 Bad Request. Fall back to use the project as reviewer.

check_maintenance_incidents.py: Fall back to review by the devel prj only
