source-checker.pl
If a spec file gets another "SourceN: some-change.patch" it will be
rejected.  New Sources do not need to be listed in .changes, so drop
such file from internal list of patches.
Fixes #292
Signed-off-by: Olaf Hering <ohering@suse.de>
=> Patches listed in Source are not patches

osclib/accept_command.py
We need urllib2 for this code piece:
'''
def create_new_links(self, project, pkgname, oldspeclist):
filelist = self.api.get_filelist_for_package(pkgname=pkgname, project=project, extension='spec')
removedspecs = set(oldspeclist) - set(filelist)
for spec in removedspecs:
url = self.api.makeurl(['source', project, spec[:-5]])
print "Deleting package %s from project %s" % (spec[:-5], project)
try:
http_DELETE(url)
except urllib2.HTTPError, err:
if err.code == 404:
pass
else:
raise
'''
otherwise, we can't handle the exception if the delete request failed (we have one .spec file less after checkin - actually, none left... but the package can't be removed anymore, as accept already did that for us)
=> accept_command: import urllib2

create_test_Factory_dvd-2.testcase, create_test_dvds.sh
important! had hot-patched on packagelists.
=> use suffix instead of hardcoded number, it is wrong for 2-DVD

factory-package-news/announcer.py
makes good MUAs send replies to the target list rather than the sender.
http://cr.yp.to/proto/replyto.html
=> set Mail-Followup-To field

tests/fixtures/source/openSUSE:Factory:Staging:A/_meta, tests/fixtures/staging-meta-for-bootstrap-copy.xml
With extention osc_freeze command to the new architecture, we've forgot
to add tests. Lets fix it
=> Fix expected architectures

osc-check_source.py
opensuse attribute was removed from stagingapi, use project attribute
instead.
=> Use project attribute instead of opensuse attribute

totest-manager.py
In case of 'regular' openSUSE Tumbleweed, there is no 'group' suffix added, resulting in a name 'openSUSE Tumbleweed ' to be match, which in turn won't be found in the database.
=> ToTestManager: strip constructed group name

create_test_dvds.sh
If nullglub sets, seems it will affect the following osc api call for finding matched projects as like as the error below,
osc api: takes exactly 1 argument (0 given)
thus unset nullglob after counting RPMs.
=> Unset nullglob after counting RPMs

totest-manager.py
90 is too high number of expected jobs for PowerPC.
=> Make number of expected jobs architecture specific

create_test_Factory_dvd-1.testcase
Due to pattern_base's change, add the appropriate kernel to testcase. kernel-desktop for x86_64 and kernel-default for ppc64le.
If I understand https://github.com/yast/yast-yast2/blob/master/library/system/src/modules/Kernel.rb correct, the kernel flavor should be right here.
=> Add the appropriate kernel to testcase

osclib/accept_command.py
Without this, we have code like this:
project = self.api.project
for ports in ports_prjs:
project = project + ':' + ports
Which results in
1) openSUSE:Factory:PowerPC
2) openSUSE:Factory:PowerPC:ARM
the 2nd obviously wrong.
=> ports: make sure to not add ports over ports

ReviewBot.py, check_source_in_factory.py, check_tags_in_requests.py, tests/checktags_tests.py
Maybe I'm wrong, but this logic should be the properly one I assume
use ''if not is_new: '' once the package is not a new package it will return False and quit the function, then I guess the following factorySourceChecker will not execute.
=> Fixes the logic error in checkTagNotRequired()

osclib/memoize.py, osclib/stagingapi.py, tests/api_tests.py
To avoid hit multiple times the OBS server asking for the _meta content in the staging project, I use a memoization version of `get_prj_pseudometa`.
This will cause problems with the `select` command, that will update the description field with some YAML metadata, causing `get_prj_pseudometa` returning outdated information.
To resolve this issue I also provide a mechanism to externally invalidate the memoization content from one specific set of parameter, adding a new dynamic method to the class.  So for every memoized method, a new `_invalidate_XXXX` method is created.
=> Memoize get_prj_pseudometa results

osclib/adi_command.py, osclib/stagingapi.py, tests/fixtures/group/factory-staging, tests/obs.py
I for one can start 'osc staging adi', it gives me an overview of "what's missing" and it accepts the 'ready stagings"; but as I'm not member of factory-staging, the creation of new staging projects, and moving requests to them, fails with a permission denied.
This change set performs a check if the user starting the command is member of factory-staging and only conditionally executes the 2nd part.
=> Execute based on permission

manager_42.py
Still need it to handle the request accepted from the corresponded
place, ie. from self.project_preference_order. But now detach the linked
entry and add requestid following with copy cmd, therefore, the
following get_latest_request() in crawl will not fail.
=> Re-enable detach linked entry code

manager_42.py
Otherwise, we run into:
File "./manager_42.py", line 434, in <module>
sys.exit(main(args))
File "./manager_42.py", line 388, in main
uc = UpdateCrawler(args.from_prj, caching = args.no_cache )
File "./manager_42.py", line 76, in __init__
self.packages[project] = self.get_source_packages(project)
File "./manager_42.py", line 93, in get_source_packages
query=query)))
File "./manager_42.py", line 84, in cached_GET
return _cached_GET(url)
NameError: global name '_cached_GET' is not defined
=> manager_42: fix scope usage of _cached_GET

osc-staging.py, osclib/adi_command.py
If with --by-develproject, adi command will check devel project of source package before selecting requests to adi staging.
=> Add --by-develproject argument to adi command

create_test_dvds.sh
Staging project under openSUSE:Leap:42.1:Staging can not match the
original condition as it is not at the forth place in case separate by
colon. Use sed replacing the string from the first word till :Staging
to 'Staging' and pick the second place after separated by colon.
=> Fixing wrong parsing $l from $prj

osc-staging.py, osclib/list_command.py, osclib/stagingapi.py
Do not superseding requests with list command, but if had the permission
of staging, can executing with --supersede argument, or even against
specific requests.
=> Do not superseding requests with list command

totest-manager.py
This should produce the files
* version_totest
* version_snapshot
in the Staging/dashboard, which represents the versions that we expect to be part of the repo.
together with the new cron script, we should thus get FTP Tree and openSUSE:Factory/snapshot rather close together
This is 100% untested so far (but seems to make sense to me.. so please carefully review)
=> ttm: publish expected versions to better sync /snapshot with ftp tree

osclib/stagingapi.py
It's workaound for https://progress.opensuse.org/issues/9646, suppose it is adi staging in case current project doesn't have ":DVD" subproject and the package is exist in current project.
=> Check subproject is exist before delete package

totest-manager.py
Only adding machine types to the list if the test fails means we do not
list 'Now passing' messages for any Machine Type that has all issues solved.
=> ttm: collect all machine types

osc-staging.py
Allow to skip full validation of /totest being fully synced.
This can be helpful (and is only meant to be used) when you run two
consequtive staging accept LETTER commands in a row.
* The first one would see /totest fully sync, not dirty
* the second call sees /totest as dirty, as the scheduler would first have
to process all data
In order to not have to wait for this to happen, the factory-maintainer CAN
override this with osc staging accept --force
=> staging accept: introduce --force

osc-staging.py
With multiple people working on staging projects, it's not always clear to everybody
when things happened and it's helpful to easily  be able to gather the information
=> frozenage: show how long a project was last frozen

ReviewBot.py
The new parameter --review-mode allows to specify how the review bot should handle obs reviews
normal: accept review if check is good, decline if bad
no: don't accept or decline requests
accept: always accept review, even if check fails
fallback-onfail: accept review and set other user or group as review if check fails
fallback-always: always accept review and set other user or group as reviewer afterwards
=> Implement configurable review mode

totest-manager.py
openSUSE:Factory:Live has no 'images' repository to release, but a standard
This reverts commit 8f4e97598fc255b1283661c80444307f80e6ae4f.
=> Revert "make sure to only release the 'images' repo"

osc-staging.py, osclib/stagingapi.py
If release-notes-sles is existed then it is not openSUSE Factory but
SLE, hence do not check totest and openSUSE-release.rpm on it.
And add try/except protection in get_binary_version otherwise it will
crashes in case the package is not existed.
=> Do not check totest on SLE

openqa-maintenance.py
This bot reviews maintenance_release requests by pushing the incident
information to openQA an monitoring the openQA results.
=> Add bot for openQA maintenance

abichecker/apache/opensuse-abi-checker.conf.in
The apache config file for abichecker needs to include access control
rules, otherwise apache will deny access.
=> Add access control to abichecker apache config

osclib/checkrepo.py
Some users are confused as the old message "package never built" does
not have to be true in many cases, especially on longer-lasting
stagings. In this case, the binaries might have been built but have
since been replaced by newer ones - the effect is the same: repo-checker
can't receive them in order to perform the full checks.
=> repochecker: Adjust the decline message for missing binaries

osclib/adi_command.py
Update by_dp function in adi command, the old way is incompatible to
newer Leap development model, now we should try to check target package
in Factory as well, otherwise the submission from any other place than
Factory did not have 'devel' entry in _meta.
=> Update by_dp function in adi command

openqa-maintenance.py
As long as all actions come from the same incident, having a submit
to somewhere else is fine - see https://build.suse.de/request/show/114532
=> Remove paranoid checkk

osc-staging.py, osclib/adi_command.py
With --split argument, staging adi command can splits each package to different adi staging project, the argument can work by 'osc staging adi --split' or 'osc staging adi --move --split'. Note that, it will be
ignore --by-develproject argument too.
=> Add --split argument to adi command

osc-staging.py, osclib/accept_command.py, osclib/stagingapi.py
This changes 'osc staging accept' to remove any left packages in the staging projects.
it can be skipped by 'osc staging accept --no-cleanup'
It helps us not having to run after all stagings all the time and it intentionally prints the list of what it removed, as often we make use of this to know what we need to link additionally to rings.
=> Accept cleanup

osclib/accept_command.py
Since we recently fixed the regex to actually match when to add the devel prj, it now shows that the devel prj we insert is invalid (it is added in the escaped form... \; is not being written as '.
Just use ' for the outer limits and " inside the xml limits... makes it more readable anyway (and works)
=> Accept: fix escaping when creating linked package

totest-manager.py
operations / usage, and not only for debug / verbose runs.
It's really annoying not to get the list of failed modules unless one specifies --debug or --verbose
Normal program output should just not be killed off
=> totest-manager: The information about failed jobs is meant for normal

osclib/request_finder.py, osclib/select_command.py
Scenario: the accepted request from adi staging what was queued for next Factory check-in round, if executing staging select command against a PROJECT , the processed request will picks up by staging tool again. So use 'newcand' param ensure staging-group's review state is new if selecting a PROJECT unless 'mov'e param is show up.
=> Use newcand param make sure don't select the processed requests

ReviewBot.py
Package patchinfo should not be checked if it already exists in Factory since it doesn't make sense. Therefore I added this check to exclude the patchinfo if it exists in the request.
=> Ignore package patchinfo for checking

source-checker.pl
This mode is used withing the build host and does not change the sources.
Is is thus no risk to have it enabled for the products.
=> Allow the new service mode "buildtime"

create_test_Factory_dvd-2.testcase
Inkscape now are Suggests in the pattern rather than Recommends, hard require it in the staging DVD instead of drop the test from openQA.
Already applied it in the packagelists actually.
=> Hard require inkscape due to the pattern change

openqa-maintenance.py
otherwise the request will be blocked as FAILED without reason
=> Report fails without modules too

openqa-maintenance.py
Please merge after https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1989
=> Remove backward compatibility with qam-minimal tests

openqa-maintenance.py
The VM is not hosted by perseus but by pegasus.
=> fixed WORKER_CLASS for host kGraft18

create_test_dvds.sh
Support of https://github.com/openSUSE/osc-plugin-factory/pull/593 in the create_test_dvds
=> Do not regenerate pl if the testdvd build is disabled

osclib/accept_command.py
Since commit 295fcd we newly also require http_POST in order to
put a new file in place after accepting.
Also add quotes around the fakepkgname when injecting it into the kiwi file.
=> Import http_POST for accept_command

create_test_dvds.sh
that ```|| true``` is prevent set -e kills program
=> Move testdvd status chack part under the condition protect

openqa-maintenance.py
urllib is for some reason *much* slower - like minutes instead of microseconds
=> Move to requests module

osc-check_source.py
In this case, sourceinfo is not sub-element but root.
=> Just findall linked tag to instead of search sourceinfo

manager_42.py
Not all packages in there are accepted yet so we need to avoid manager42
to mark them as FORK.
=> Add back SLE-workarounds

osclib/conf.py
Leap doesn't have ppc in staging so split defaults so we don't need
an .oscrc
=> Split config for Leap

osclib/select_command.py
Given the select command can take a significant length of time to complete an indication of progress is handy. Uses the same format as zypper during installation.
=> Indicate select command progress.

ReviewBot.py
Seems to be an exact duplicate of the function?
Based on blame seems a bit odd:
- efbcd75064342040aa3aa4f4ddd3945a4b77ce04
- 1106da20ccbaecc881ba8389b3b07fb391e72232
=> Remove duplicate ReviewBot.set_request_ids_project()

ReviewBot.py, abichecker/abichecker.py, check_maintenance_incidents.py, check_source_in_factory.py, check_tags_in_requests.py, leaper.py, openqa-maintenance.py
Alleviates the need for a lot of duplicate code, some of which is already out-of-sync. Some examples of out-of-sync code are as follows.
- `check_source_in_factory.py`: not include group parameter
- `check_tags_in_requests.py`: missing default user
Either way this is primarily intended as a cleanup. I ran into this when I started porting `osc-check_source.py` to `ReviewBot` and needed to copy/paste a bunch of code for no good reason.
=> Rework ReviewBot.CommandLineInterface to provide class option.

ReviewBot.py
Seems to be an exact duplicate of the function?
Based on blame seems a bit odd:
- efbcd75064342040aa3aa4f4ddd3945a4b77ce04
- 1106da20ccbaecc881ba8389b3b07fb391e72232
=> Remove duplicate ReviewBot.do_project().

devel-project-list.py
Simotek in #opensuse-factory was looking for a list of devel projects for Factory. I figured this could be handy and the code already exists in `osc-check_source.py`. Perhaps this is not the right place, but if so here it is.
=> Provide a utility to print the list of devel projects for a given project.

osc-staging.py, osclib/cache.py, osclib/stagingapi.py, tests/checktags_tests.py, tests/factory_source_tests.py, tests/fixtures/statistics/latest_updated, tests/obs.py
The two slowest staging API calls are for information that rarely changes. By caching the result the commands typically execute over twice as fast. Going further can see improvements of an order of magnitude or more by caching almost all the GET requests.
In contrast to osclib/memoize.py this cache operates at the HTTP request level. This has several advantages:
- Caches the expensive part (ie the HTTP request). There are a number of functions in osc.core and elsewhere that make the same API request, but process the result differently which would require multiple API calls using memoize.
- Handles cases were a loader function uses class attributes as input and output and thus no relevant method parameters or return. An important example is StagingAPI._generate_ring_packages().
- Storage …
=> Provide cache for expensive and cache-able staging requests.

leaper.py
Minor and perhaps others have a better idea for wording, but I find myself squinting to see if the origin has changed when reading the comment.
Example output:
```
INFO:leaper.py:checking 448728
INFO:leaper.py:SUSE:SLE-12-SP2:Update/libzypp.3458@6256a456cdd115084ec37121e16af717 -> openSUSE:Leap:42.3/libzypp
INFO:leaper.py:expected origin is 'SUSE:SLE-12-SP2:Update' (unchanged)
```
Could make it more like a sentence: `origin matches the expected origin '...'` and `origin (does not match|differs from) the expected origin '...'`.
=> leaper.py: indicate if origin differs from the expected origin.

osc-staging.py, osclib/adi_command.py, osclib/ignore_command.py, osclib/list_command.py, osclib/stagingapi.py, osclib/unignore_command.py
It is not uncommon for a request to be in a pending state which requires action beyond the scope of the staging workflow, but does not make sense to deny the request. For lack of a "postponed" or "pending" state on OBS a sudo-state of "ignore" is provided for the staging workflow. The ignore state will remove a request from the "list" and "adi" commands so as not to be accidentally staged. This avoids the need for keeping a context of what requests should be ignored in one's memory.
It is expected that an ignored request will have comments reflecting what is to be done or one should be added via the -m option of ignore command.
During our weekly call @lnussel seemed to agree that such a facility would be useful.
=> Provide ignore/unignore request staging commands.

check_source.whitelist
It could be useful for a few libraries hosted there.
=> Added X11:GNUstep as project.

osclib/list_command.py
In the previous state this worked for any project except factory, now it works on factory too.
I normally avoid running commands against factory, but given `list` makes no changes it should be fine. Anyway, I seem to have been focused on ensuring the `\n` was added after
```python
result[devel][-1] += ' ({})'.format(source_prj)
```
that I included the check in
```python
if self.api.project != "openSUSE:Factory" and action.find('source') != None:
```
which clearly would not work for factory. Glad to see @DimStar77 already tried to use it though. ;)
=> Correct indentation level of in requests_ignored check.

check_source_in_factory.py
Adds --limit option to specify how many revisions back to iterate over
when checking for match. Leaving default at 5.
=> Make revision depth (limit) configurable

osc-check_repo.py
As noted in https://github.com/openSUSE/osc-plugin-factory/pull/629#issuecomment-274010120 the machine used to run the `osc-check_repo.py` script does not have write access to `~/.cache`. I copied the style that is already working, but this can obviously be set to anything.
=> osc-check_repo.py: alter http cache directory due to box constraints.

totest-manager.py
When running as a systemd daemon, it is useless to wait for user input
to possible trigger an earlier re-run. Interaction is not possible.
Additionally, there is no stdin assigned to the process when running as
a systemd daemon, which results in raw_input() failing with EOFError
=> ttm: Add --daemon parameter

check_source.whitelist
To resolve the error at https://build.opensuse.org/request/show/452889 Not sure if this is correct. I guess https://en.opensuse.org/openSUSE:How_to_contribute_to_Factory#How_to_request_a_new_devel_project needs an update.
=> Added X11:Solus to the Factory devel project whitelist

totest-manager.py
the 'continue' was wrongly kept in the loop for tty mode but is also applicable in daemon mode
=> ttm: fix the loop in daemon mode

issue-diff.py
Compare packages from a project against factory for differences in referenced issues and present changes to allow whitelisting before creating bugzilla entries.
First draft of tool as discussed with @coolo. Note that at the moment I am unable to confirm the bugzilla portion works due to `401 Client Error: Authorization Required` which is also referenced in a mailing list thread and never resolved. It seems the api server expects HTTP Authr and does not work properly with the api tool. Perhaps someone knows something?
My understanding of the requirements:
- manually run script
- ability to whitelist issue references
- ignore issues newer than X
- create bugzilla entries for issues missing from factory
The current design creates a `$PROJECT.yml` file containing the list of references and an …
=> Provide referenced issue diffing tool.

osc-staging.py, osclib/adi_command.py, osclib/list_command.py, osclib/request_splitter.py, osclib/stagingapi.py, requirements.txt, tests/api_tests.py
While working on `openSUSE:Leap:42.3` I have maintained a few local wrapper scripts to assist in some of the staging work. With the addition of #631 proposals would not include undesired requests and so I decided to build out what I had been thinking about.
The goal is threefold:
1) replace `list` and `adi` parts with a common request filter/group code base
2) utilize such a framework for adding filter/group capability to select command
3) lay the groundwork for potential future work in creating higher level select strategies to fully automate the process as much as possible
I believe the first two are achieved quite well by this and much of the third.
The following is taken from the included documentation.
```
When using --filter-by or --group-by the xpath will be applied to the
request …
```
=> RequestSplitter and staging selection proposals

repo-checker.pl
Otherwise there is a bootstrap issue
=> Repochecker: add rpmlint-mini to the whitelist to not have an rpmlint.log

osc-staging.py, osclib/adi_command.py, osclib/list_command.py, osclib/request_splitter.py
Followup on confirmation that previous adi logic was bad and some further testing.
- Remove incorrect devel project lookup copied from adi.
- Move @devel_project to action/target.
=> Remove source devel project check carried over from flawed adi logic

ReviewBot.py, osclib/stagingapi.py
The search/package query is typically very slow and can spend several minutes timing out. The concept of loading all package meta data at once is attractive, but given that the query regularly increases the runtime of the script by an order of magnitude or more making individual calls seems advantageous. These calls are already included in the cache which means the initial request avoids the 10+ minute wait and repetitive calls have no additional cost.
I ran into this query failing >5 times today and have been considering this change for a while. In the `check_source.py` port I changed to query for individual packages since it should requests as they come and would not see much benefit from loading all package data at once. See [ReviewBot.get_devel_project()](https://github.com/openSUSE/os …
=> stagingapi: Avoid search/package query to determine devel project.

totest-manager.py
The openQA group has now been officially created and named slightly
different
Additionally, there is only one job being run at this moment: make
this sufficient for ttm to detect the snapshot being tested.
=> ttm: Fix configuration for s390x

source-checker.pl
See sr#455547 which now functions properly.
Before:
```
Output of check script:
No such file or directory: _old/u-boot-nanopineo.changes at /home/repochecker/src/osc-plugin-factory/source-checker.pl line 203.
```
After:
```
INFO:check_source.py:checking 455547
INFO:check_source.py:Base:System/u-boot@230 -> openSUSE:Factory/u-boot
INFO:check_source.py:POST https://api.opensuse.org/request/455547?by_group=None&cmd=addreview
INFO:check_source.py:POST https://api.opensuse.org/request/455547?cmd=addreview&by_user=factory-repo-checker                               
INFO:check_source.py:455547 accepted: Check script succeeded                                                                               
DEBUG:check_source.py:455547 review not changed
```
=> source-checker: handle add/remove changes files for patch diff check.

osc-staging.py, osclib/list_command.py, osclib/request_splitter.py
- list: remove case for delete request without ring.
- non-ring projects consider all requests in rings.
- utilize ring attribute rather then lookup again.
- rather than an empty group name use 00.
=> request_splitter: house keeping (and fix for SLE [non-ring] workflow)

issue-diff.py
Re-initialized the issue-db repo and granted @coolo write access per discussion.
- update description to include a short reason.
- change default project to SLE-12-SP3.
- use bugowner or maintainer as assignee for bug.
Still not sure on what is desired for description text. @coolo: How wordy do you want it?
=> issue-diff: use bugowner or maintainer as assignee for bug (and small changes)

osclib/adi_command.py
=> adi: map wanted_requests to str() before passing to splitter.

check_source.py
Requested in #569. Using request provided as example (sr#428605).
Before:
```
INFO:check_source.py:checking 428605
INFO:check_source.py:openSUSE:Factory/translate-toolkit@17 -> openSUSE:Factory/translate-toolkit
INFO:check_source.py:428605 declined: Expected submission from devel package M17N/translate-toolkit
DEBUG:check_source.py:setting 428605 to declined
```
After:
```
INFO:check_source.py:checking 428605
INFO:check_source.py:openSUSE:Factory/translate-toolkit@17 -> openSUSE:Factory/translate-toolkit
INFO:check_source.py:POST https://api.opensuse.org/request/428605?by_group=None&cmd=addreview
INFO:check_source.py:POST https://api.opensuse.org/request/428605?cmd=addreview&by_user=factory-repo-checker
INFO:check_source.py:428605 accepted: Check script succeeded …
```
=> check_source: allow self-submission.

check_source_in_factory.py, leaper.py
No need to duplicate the log message in multiple places.
=> ReviewBot: use super().check_source_submission() in subclasses.

osc-staging.py
- **add missing documentation and correct/clean existing.**
- check command does not support 2 arguments.
- adi command min should be 0 for consistency.
- drop extraneous space in freeze method call.
=> osc-staging: add missing documentation and correct/clean existing

totest-manager.py
If not connected to a tty output probably goes to systemd's journal.
=> Only output timestamps when run on tty

osclib/stagingapi.py
Requested in #573.
Fully tested by running:
```python
api.update_status_comments('openSUSE:Leap:42.3:Staging:adi:9', 'select')
```
Which resulted in the correct link in [comment](https://build.opensuse.org/project/show/openSUSE:Leap:42.3:Staging:adi:9).
I debated if the link should be placed around a new piece of text like `(dashboard)` or somesuch, but given the comment is on the project page the only other relevant link related to just the project seems like dashboard. Either way easy to change since url is correct.
The new `extract_staging_short()` from `request_splitter` did the trick and works for both letter and adi. :)
=> stagingapi: update_status_comments() include link to dashboard.

ReviewBot.py, leaper.py
Simple interface:
- comment_handler_add(): Add handler to start recording log messages for comment.
- comment_write(): Write comment from log messages if not similar to previous comment.
Previous implementation had some interesting quirks that I will list in case some were intentional.
- Checked `if self.comment_log:` before processing comment even though that will always be set. I changed to `do_comment` and removed from subsequent functions. Could also move do_comment into ReviewBot, but it seemed more like a guarding flag when turning on the feature rather then something to be part of the API.
- `Leaper.comment_add()` provided a result parameter, but it was never used. It was however calculated, but never passed along.
- Checked state of comment in `find_obs_request_comment()` and …
=> ReviewBot: refactor leaper comment from log functionality.

ReviewBot.py
Allow future bots to change the name used to represent the bot.
Requested in #684 by @lnussel.
=> ReviewBot: extract __class__.__name__ as default for self.bot_name.

check_tags_in_requests.py, tests/checktags_tests.py
Requested in #677.
- handle failed to load issue diff for existing package.
- correct backwards diff.
- use len() instead of list() since only count is of interest.
- **warn when issue references are removed.**
- grammatical corrections.
Interestingly enough the diff would appear to have been performed backwards. Since only the existence of issues was checked this worked fine, but given the request was about warning when removed it seemed proper to flip rather than look for `added` when meaning `deleted`.
For example, sr#455816 which is clearly adding one bug reference showed it as being `deleted`:
```xml
<sourcediff key="c9b42dc9c3a1f9435342cbe12cad4d3d">
<old package="python3-requests.6329" project="openSUSE:Leap:42.2:Update" rev="baa02f86911ca86af78b4f0db1b7b882" …
```
=> check_tags: warn when issue references are removed (plus other fixes)

ReviewBot.py, leaper.py
- **ReviewBot & leaper: provide deduplicate method for leaper comment.**
- leaper: utilize ReviewBot check_action__default() message.
- ReviewBot: check_action__default() should return None not set ret.
- leaper: drop extra definition of check_action__default().
- ReviewBot: drop duplicate import namedtuple.
This resolves the duplicate line in comment on unhandled request types (like sr#457061).
Before:
```
unhandled request type delete
unhandled request type delete
request needs review by release management
```
After:
```
unhandled request type delete
request needs review by release management
```
I debated making the maintbot check conditional or similar, but seems like this can occur in a variety of ways and even more in the future. If maintbot ends up supporting different types of …
=> ReviewBot & leaper: provide deduplicate method for leaper comment (and other fixes)

osclib/stagingapi.py
A sample is currently
https://build.opensuse.org/project/show/openSUSE:Factory:Staging:adi:1
of course this will change over time, as the projects come and go. OBS could need some UI love to present the link better though
=> Add a link to the dashboard of the respective adi project being created

osc-staging.py, osclib/unignore_command.py, requirements.txt
This would make sense to run under some bot credentials to auto-cleanup. I will go ahead and run again Leap 42.3 for the time being. Since the ignored_requests file is version controlled messages and such can always be recovered if some sort of mistake is made.
Here is the output for Factory:
```
Removing 459341 which was superseded 5 days ago                                                                                            
Removing 451216 which was revoked 33 days ago                                                                                              
Removing 448595 which was superseded 45 days ago
Removing 454181 which was superseded 17 days ago
Removing 454246 which was superseded 15 days ago
Removing 459240 which was superseded 5 days ago
Removing 448102 which was …
```
=> osc-staging: provide --cleanup option for unignore.

osclib/stagingapi.py
Properly, supports the intentions of `adi:1` shorthand.
=> stagingapi: extract_staging_short() correction for non-letter parse.

check_tags_in_requests.py
Set expand:1 to expand links in case the target is a links.
Eg. comparing
iosc api -X POST /source/home:mlin7442:boo1026534/libqt5-qtdeclarative?cmd=diff&withissues=1&view=xml&oproject=SUSE:SLE-12-SP3:GA&opackage=libqt5-qtdeclarative&expand=1
and
iosc api -X POST /source/home:mlin7442:boo1026534/libqt5-qtdeclarative?cmd=diff&withissues=1&view=xml&oproject=SUSE:SLE-12-SP3:GA&opackage=libqt5-qtdeclarative
the change in .changes does not count actually. libqt5-qtdeclarative in
SUSE:SLE-12-SP3:GA is a link to libqt5-qtdeclarative.3900
=> Expand links in diff cmd POST

osc-staging.py, osclib/rebuild_command.py, osclib/stagingapi.py
Often packages will fail to build after becoming stuck or other false negative cases and need to have a rebuild triggered. The process can be tedious if several packages failed in various stagings.
For instance today, there are three Factory stagings that all had stuck packages, but otherwise built fine (E, F, and H). This is another part of the automation flow that I plan to add logic to try and be smart so it can be run automatically, but this is useful as it stands.
I have been keeping a list of stuck and flaky builds that could be used as a basis for the tool. Alternatively, plugging into statistics data should with simple flaky detection pattern should provide fairly decent automation to avoid stuck stagings that just need a package or to rebuilt.
For example the three stuck packages …
=> osc-staging: provide rebuild command.

osc-staging.py
Handy to get an overview. I typically run with all letters.
=> osc-staging: allow frozenage to be invoked with no arguments.

check_source.py
Repo-checker at least has some code to validate if it's safe to delete
a package and gives us the information what else we would break with it.
https://progress.opensuse.org/issues/17746
=> Delete requests should be handled by repo checker

leaper.py
In the same spirit as #682.
Example that makes sense to allow: https://build.opensuse.org/request/show/479616.
Output after change:
```
DEBUG:leaper.py:adding comment to 479616: 
openSUSE:Leap:42.3/postfix@8 -> openSUSE:Leap:42.3/postfix
self submission detected
GET https://api.opensuse.org/request/479616
INFO:leaper.py:can't change state, 479616 does not have the reviewer
INFO:leaper.py:479616 accepted: ok
```
=> leaper: allow self submission.

osclib/request_splitter.py
Per IRC discussion with @DimStar77 it seems these are only isolated when an issue arises. Is there any other packages you can think of that should be labeled special that I can add while I'm at it?
=> special strategy: drop python*.

osclib/accept_command.py, osclib/stagingapi.py, osclib/unselect_command.py
- **unselect: cleanup stagings left empty after request removal.**
- accept: refactor staging cleanup into stagingapi.
Resolves #735 in addition to a missing cleanup case. I have noticed this in occurring in both Factory and Leap and this explains why.
=> unselect: cleanup stagings left empty after request removal.

osclib/request_splitter.py
Per discussion with @DimStar77 the devel strategy minimum should be lower for YaST:Head packages. Not sure if 2 is right. Additionally, not sure if you just wanted packages to be force group together or isolated. Currently all the strategies result in only those packages placed in a staging. The concept of "handcuffing" packages together that can still be included in a larger group is something I have toyed with, but is not yet implemented.
Also are there any other devel projects that should have special minimums while we are at it?
=> request_splitter: add group min map to devel strategy.

osc-staging.py
The proposals should never be generated with requests that are already staged and as such should never be moved. Presumably this should never work, but as such makes sense to remove from the call.
=> osc-staging: --move and --from do not make sense with select proposal.

osc-staging.py, osclib/check_command.py
Tiny cleanup that does not fit with anything else, but noticed while working on other requests.
- check: stagingapi.check_project_status() does not have verbose argument.
- osc-staging: check command replace REPO with STAGING in doc.
=> Cleanup check command doc and extra argument

osclib/ignore_command.py, osclib/stagingapi.py, osclib/unignore_command.py
Some ignore/unignore related cleanup based on observed usage.
- ignore|uningore: use past tense in output.
- **ignore: add default comment message if none provided.**
- ignore: remove validation since that is handled by RequestFinder.
- **unignore: add comment when a request is unignored.**
- **unignore: utilize RequestFinder.**
Without a comment the only indication of when a request was ignored/uningored is in the revision history of ignored_requests file.
=> Cleanup ignore and always provide a comment.

osc-staging.py, osclib/repair_command.py, osclib/stagingapi.py, osclib/unselect_command.py
Replaced PR #769 with common code in stagingapi.
- repair: support the --cleanup flag to include all untracked requests.
- unselect: support the --cleanup flag to include all obsolete requests.
- stagingapi: project_status_requests() to extract all requests of type.
Resolves #736.
=> support --cleanup for obsolete and untracked requests in unselect and repair commands

osc-staging.py, osclib/prio_command.py
Per note by @lnussel to leave refactoring to utilize `project_status()` to me.
The existing setup was inconsistent in that it was copied from check, but documented that it supported multiple specific stagings. Assuming that would be a desired feature anyway it has been reworked to both utilize `project_status()` and multiple stagings as input.
=> setprio: utilize project_status() and refactor to support list of stagings.

source-checker.pl
Solve boo#1028567.
Tested via:
```perl
#! /usr/bin/perl
my $var = "README.asciidoc; echo evil;";
system("cat $var"); # outputs evil
system(("cat", "$var")); # does not output evil
```
=> source-checker: utilize array system() calls to handle unescaped input.

osclib/list_command.py, osclib/stagingapi.py
Implement Leap suggestion tracked in #739 along with some other supersede issues and cleanup refactoring.
- **stagingapi: refactor supersede logic and handle different source projects.**
Primarily an issue for Leap in that requests originating from different source projects may be submitted for the same package at once. Instead of always superseding the previous request the request will only be superseded if it originates from the same project.
If different sources md5s are found the request will be ignored and left for manual review and an identical request will be declined.
- **stagingapi: do not attempt to supersede ignored requests.**
- stagingapi: simplify finding action in superseded_request().
- stagingapi: provide source_info_request() helper.
- stagingapi: provide source_info() …
=> refactor supersede logic and handle different source projects (additional cleanups)

factory-package-news/factory-package-news.py
Initial work for #703.
I generated a 63MB pickle file from a full Tumbleweed tree and a 26MB using the latest s390x DVD.
=> package-news: support s390x arch and walking rpm tree

osclib/stagingapi.py
Resolve #780 caused by caching the `get_open_requests()` call which is invoked before supersede and after. As such superseded requests are not reflected in list until the next run.
=> stagingapi: invalidate get_open_requests() memoize cache after supersede.

osclib/accept_command.py, osclib/adi_command.py, osclib/stagingapi.py
- **adi: create accept comment to be consistent with letter stagings.**
- stagingapi: provide accept_status_comment() based on accept command.
- accept: remove unused requests list in perform().
Seems to make sense for the same reasons it does for letter stagings.
I cannot run accept (other than tests) and have not had an adi staging to accept since writing this code.
=> adi: create accept comment to be consistent with letter stagings. (and cleanups)

osclib/select_command.py, osclib/stagingapi.py, osclib/unselect_command.py
- handle build disable in select command just like comment instead of stagingapi move_between_project() for consistency and to reduce double checking the same information via extra API calls
- build_switch_staging_project() provides target_flag parameter rather than trying to figure out flag value since caller has the context to know and again reduces API calls
- build_switch_staging_project() checking conditions are essentially checking if True is True since non-adi projects will always have ring packages or rings disabled entirely. The condition of interest is non-empty. Additionally adi projects are removed if empty so not a terribly useful distinction to make.
- provide helper update_status_or_deactivate() to handle common logic and replace in calling locations
Primarily, `select …
=> osc-staging: handle `select --move` cleanup of empty source project.

osclib/stagingapi.py
Fixes #788.
I have been running this locally for the last few days.
=> stagingapi: correct supersede call to IgnoreCommand.

leaper.py
Perhaps this should be handled on a larger scale where initial variable states are not set in __init__ but rather in special method or reset in some manor.
Fixes #781. (or so it would seem)
=> leaper: reset automatic_submission to False on each review.

osclib/stagingapi.py
=> stagingapi: rebuild_broken(): ignore unresolvable packages.

devel-project.py
Given that previous comment is used as a basis for determining the time since last reminder if it cannot be removed a new reminder should not be created.
Provides workaround for #800. This code should be irrelevant after all previous reminder comments are either removed or no longer relevant. This also allows for others to run the reminder script without causing each other to crash.
I'll go ahead and delete my previous comments after seeing a full run using this code.
=> devel-project: gracefully skip when removal of previous comment fails.

update_crawler.py
Prevents situation that can create a loop of update_crawler requests, superseded and another update_crawler request.
Should fix #791.
=> update_crawler: include superseded requests when looking for existing.

osc-staging.py, osclib/request_splitter.py, osclib/stagingapi.py, tests/obs.py
- **request_splitter: provide and utilize an aged attribute on requests.**
- request_splitter: use capital for boolean strings in supplement().
- request_splitter: s/suppliment/supplement/().
- stagingapi: get_open_requests() provide query_extra option.
- stagingapi: get_open_requests(): replace query string with dictionary.
Fixes #733.
=> request_splitter: provide and utilize an aged attribute on requests.

osclib/request_splitter.py, osclib/stagingapi.py
- 446a30dde05a3583665a25ce14438376750f20af:
**request_splitter: switch from build percentage to staging age for merge.**
Using build percentage is sub-optimal since many events can reset the
percentage which can result in additional requests being merged into the
staging. A better metric is the time since the first request was added to
the staging (the age of the staging). Unfortunately, this is not trivial to
determine especially given that the original request may be superseded or
unstaged entirely. As such the datetime at which the staging was activated
is stored in the staging pseudometa. A max age is then used to allow for
merging up until that point.
- d8f7d03c339b5106c761edc76f4ff4068271a08e:
**request_splitter: allow user to override merge conditions.**
- …
=> request_splitter: switch from build percentage to staging age for merge.

osc-staging.py, osclib/request_splitter.py
- cc8a53f5172767e39b00284e52f75f82c20067af:
osc-staging: select: extend doc to cover [try-]strategy[s] and merge.
- 5e0ed06ae6aead3924e7892e56471dd3112cb9f0:
osc-staging: select -i: include note about skipping.
- 959a8f7905225107dadef9cc02b82cddfc2c826d:
**request_splitter: add super strategy for representing devel groups.**
- 59eda5d82db110d3b99aabb450f9b2361490f7b2:
request_splitter: group_by(): provide required option and use in devel.
Staging packages with no devel project as a result of devel strategy seems
like the incorrect behavior.
- 232219363cd87f4175963a72cbae4bee6baa5e8a:
request_splitter: s/supliment/supplement/ in comment.
=> request_splitter: add super strategy for representing devel groups.

osclib/request_splitter.py
- cde24ba8b2127789e7d8262f6259a195d337cfb1
**request_splitter: provide quick strategy based on lack of reviews needed.**
- 380c3f1b77315f6bd81d81db2b688353d44b082c
request_splitter: provide Strategy.desirable() in base.
Default should be all groups are desirable which the strategy can override.
Fixes #737.
This looks for requests that have been reviewed by `leaper` and do not require any further review. It may also make sense to allow `leap-reviewers`. The approach seems better than trying to look at source projects and author or some such since all the logic from leaper can be used.
Additionally this could be changed to allow reviews that have already been accepted. This can happen when all stagings are full or during the 55 minute none strategy delay. Either way when the staging-bot is …
=> request_splitter: provide quick strategy based on lack of reviews needed.

devel-project.py
Otherwise, `openSUSE:Factory` ends up in the list and causes undesirable results when using the requires sub-command.
Fixes #802.
=> devel-project: ensure self does not end up in list.

Makefile, check_tags_in_requests.py, tests/checktags_tests.py
The old code would decline requests instead of waiting for matching
Factory submissions to pass reviews.
=> Wait for Factory reviews

osclib/stagingapi.py
final: packages in final state (not final count ie total)
tobuild: packages remaining to build
Fixes #771.
=> stagingapi: correct project_status_build_percent() formula.

osclib/stagingapi.py, osclib/unselect_command.py
=> unselect: filter superseded when using --cleanup.

check_source.py
- check_source: package_source_parse() drop unused apiurl parameter.
- **check_source: skip staging process if only .changes modifications.**
Fixes https://progress.opensuse.org/issues/18648.
Test request https://build.opensuse.org/request/show/489331.
Skips add repo_checker review and accepts factory-staging review if only .changes modifications.
=> check_source: skip staging process if only .changes modifications.

factory-package-news/factory-package-news-web.py
Allows for multiple aliases to host different distro/version changes.
Hopefully last code change towards #703.
Was shooting for the fewest changes to leave the basic flow intact. Multiple aliases can be setup which ensure that only the desired paths can be read for changes without hard-coding in the web app.
```conf
WSGIScriptAlias /snapshot-changes/opensuse/tumbleweed .../factory-package-news-web.py
WSGIScriptAlias /snapshot-changes/opensuse/42.3 .../factory-package-news-web.py
```
Similar config changes are pending in my repo on openqa.
=> factory-package-news-web: infer basedir from url_root.

osclib/stagingapi.py
Was working on this in relation to the `unselect --cleanup` change (#831), but didn't end up needing it. Still seems useful.
Fun fact when a project has a `subproject` the array looks like:
```
[ { name: project1:DVD, ...} ]
```
When the `:DVD` project `subprojects` key is looked at it is not an empty array as one might expect, but rather.
```
[ null ]
```
:'(
=> stagingapi: simplify project_status_build_sum() with a generator.

osc-staging.py, osclib/list_command.py, osclib/stagingapi.py, osclib/supersede_command.py
- cf3ce7435eb6c57bbce01bf12d840cb2ecccb4b4
stagingapi: bypass ignored list when supersede with target_requests.
- 08a31563c44d7a1b268397b8fdccabe5c5a6061c
supersede: provide feedback about what requests were superseded.
- e213385ca4b174f1189edc92712e2f744ce2a22d
supersede: allow list of request IDs or packages.
- acc95dbb8499c90d4d9cb987489a0a6d4afb22e9
stagingapi: enhance supersede target_pkgs to skip source project check.
This creates a facility for forcing a request, that was ignored due to
the source check, to supersede the existing one.
- 54f502da375843ce35a9d09ada00505b8fb595bf
osc-staging: break out `list --supersede PACKAGES...` as separate command.
Maintains `list --supersede`, but places the explicit supersede based on
a list of packages in a separate command.
I confirmed that …
=> supersede: separate command, feedback, and force supersede post source project check

osclib/rebuild_command.py, osclib/stagingapi.py
Otherwise, the rebuild command does not print output until all the rebuilds for a whole staging are completed. With this change each package should be printed immediately.
Plus `project_status_walk()` reduces lines and complexity. It is actually required since python 2.7 does not support `yield from` for recursive calls.
=> stagingapi: convert rebuild_broken to a generator for instant feedback.

ReviewBot.py
Fixes #843.
Line 406 include info since that is desired when comparing if too similar:
```python
comment, _ = self.comment_api.comment_find(comments, self.bot_name, info)
```
The new call will broaden search (without `info`) if no comment found (due to state change).
=> ReviewBot: always remove previous comment regardless of the state.

osclib/cleanup_rings.py, osclib/stagingapi.py
- 41e4d5ae2bd09f35889984367bb5ed7c266bb025:
**cleanup_rings: provide package whitelist for special cases.**
- aca88d19c08c802f94a537979be6342b7ede171c:
**cleanup_rings: check runtime requiredby if not a build requirement.**
This check only works if the runtime requirement resides in the same ring.
The fun case being kernel-syms which is required by virtual box (ring-2),
but must remain in ring-1 to ensure matching build revision with other
kernel packages.
- ac031bb915fa026b4886a43b7edb2f5169628774:
stagingapi: provide fileinfo_ext_all() and fileinfo_ext().
- 4d0e98a00c4ce0a5e73569f3261559f3b7188cac:
**cleanup_rings: print summary of packages to be dropped and commands last.**
- 39a4914e485035bd058bc02331a45b8cedd89da4:
cleanup_rings: check ring index instead of string comparison.
- …
=> cleanup_rings: runtime requiredby check, whitelist, summary, and substantial refactoring

check_maintenance_incidents.py, tests/maintenance_tests.py
- 11dc2e167e0c6d8aa48041c8d1072363cd695640:
MaintenanceChecker: add memoize to owner_fallback().
- 3d768c3f2ed2d67faf21c35b084ff03f137ad8cb:
MaintenanceChecker: include project in owner query to utilize local devel.
For Leap the devel project may override the Factory one.
- a1cb4aa772882eb3aca2844ebb4febd43339a313:
MaintenanceChecker: utilize osc.core.owner().
Tested on https://build.opensuse.org/request/show/490193.
Before:
```
DEBUG:leaper.py:author: tiwai, maintainers: michals,jirislaby,michal-m => need review
GET https://api.opensuse.org/search/owner?binary=kernel-source
DEBUG:leaper.py:Kernel:stable/None already is a reviewer, not adding again
```
After:
```
DEBUG:leaper.py:tiwai is maintainer
```
Confirmed previous behavior remained the same in two other cases:
- …
=> MaintenanceChecker: include project in owner query to utilize local devel and improvements.

osclib/conf.py, osclib/request_splitter.py
For the initial Factory usage the bot will be allowed to stage on a subset of the available stagings.
@DimStar77 suggestion in relation to #823.
=> request_splitter: add staging whitelist config option.

osc-staging.py
Currently, crashes when `osc staging --version` is run.
```
AttributeError: Osc instance has no attribute 'OSC_STAGING_VERSION'
```
Number is fairly meaningless, but seems silly to crash.
=> osc-staging: correct --version print.

osc-staging.py, osclib/obslock.py, tests/fixtures/source/openSUSE:Factory:Staging/_attribute/openSUSE:LockedBy, tests/obs.py, tests/obslock_tests.py
- 630663a1a7557a26461ca8da326011d7bf30e0cf:
**lock: provide command to place a multi-command hold on a project.**
- 02cd0cf0f8e789e3abd99df0652d9cd34efaaeb9:
obslock: add reason to indicate what command is being run.
Is backwards compatible so others on older version should still be locked out, but will show the reason as part of username. For example:
```
Lock acquired by [jberry_factory#hold: test] 0:01:55.212672 ago. Try later
```
This provides a reason when seeing a locked out message which will either be the command being run or an indication that a manual hold has been placed on the project.
A normal command lock is still acquired when placing a hold on the project so one will not be able to place a hold if someone else already has a lock. After a hold has been acquired commands may …
=> lock: provide command to place a multi-command hold on a project (and lock reason).

osc-staging.py, osclib/cache.py, osclib/conf.py, osclib/request_splitter.py, tests/config_tests.py, tests/fixtures/oscrc, tests/fixtures/source/openSUSE:Factory:Staging/dashboard/config
- 4dd6eb8df870a50749aaae6e8403d0ab145c8c77:
request_splitter: expose age thresholds to config.
- ed9488fb35e68f1d7bb8bc12007e474bed8b6bb1:
cache: include dashboard files.
- a08c55b6028305f4ff64ff06551480a18670d659:
osc-staging: implement remote config.
Seems to make sense to use the same format as `.oscrc` the only potential downside is storing more complex data structures in config. Note that the config is loaded in two parts since the most basic config information is required to even know where to look for the remote config. As such the early values loaded in `StagingAPI` may not be overridden remotely, but that makes sense since changing the `cstaging` after loading the config from that staging does not make a lot of sense.
Order of precedence:
- code defaults
- remote config …
=> osc-staging: implement remote config and expose more settings to config.

copy-to-132.py, osc-check_repo.py, osc-staging.py, sync-rebuild.py, totest-manager.py
`totest-manager.py` likely never needed it.
Fixes #757.
=> Drop sys.path plugindir workaround.

osc-staging.py
- ecc97e05401a0f80e4fd03604eaa5e92ada878ee:
osc-staging: cleanup command and argument number checking.
- 0d92f3e4a4fafb487ccd7c0d5756409d278c8be6:
check: support multiple specified projects.
- 7e7cae55578672aead3c2e64bd8a8b5eb60d01ed:
osc-staging: correct arg count for list.
=> osc-staging: cleanup command and argument number checking (and check multiple projects)

osclib/conf.py, tests/config_tests.py, tests/obs.py, tests/obslock_tests.py
- cb282eaeace20b60549e78d983a3628b2d121f8d:
obslock-tests: correct class name.
- cabc9abf402eb10f6002d3ffbb838454070cdba0:
conf-tess: ensure a blank config is not rewritten (ie loop).
- e755c061aa6d5125c1b5333ea255a34545f47351:
conf: explicitly check if config is None.
Otherwise a blank file may repeatedly submitted.
=> conf: explicitly check if config is None (and test).

docs/staging.asciidoc, osc-staging.py
I have been rolling this idea around in the back of my head for a while.
Combined with a PS1 it makes it rather clean and clear what project will be used. Simple interface of changing directories to switch targets. For IBS I imagine such users will have the apiurl defaulted to IBS. Obviously, alias works, but kill any autocomplete potential and requires some short-hand abbreviations to be useful.
Just like git operating on current repo, `vagrant up`, etc this seems to fit in.
Combined with a PS1 its a rather nice experience.
```
<jberry> 10:09:11 {project-from-dir} ~/osc-plugin-factory $ cd ../openSUSE:Leap:42.3
<jberry> 10:09:12 <<openSUSE:Leap:42.3>> $ ls
osc-plugin-factory
```
Should not effect those who do not want to use it.
=> osc-staging: provide project from directory functionality.

osc-check_repo.py
Followup to #862 which broke `check_repo` due to usage of `PLUGINDIR` to execute script contained in this repo. Due to the fact that `osc` includes the source of plugins rather than importing and does not leave any trail behind this is really the only way to do this.
=> check_repo: include PLUGINDIR for executing scripts.

factory-package-news/factory-package-news-web.py
Leap version numbers are currently formatted with a leading zero which is stripped when converted to an int.
Another for #703.
=> factory-package-news-web: do not restrict version to int.

osclib/cache.py
With the query PUTs are not match and thus the local cache is not cleared until the next statistics/latest_updated call.
Overlooked when I made the recent remote config change. Can cause repeat ignores when something like `adi` is run multiple times in < 5 min with multi-source ignore logic (leap).
=> cache: correction to match all dashboard file requests.

osclib/obslock.py, tests/obslock_tests.py
- 1e511e9c85f8d775b7944a0c2d8128cced91624b:
obslock: delta.total_seconds() is more resilient than delta.seconds.
- 73f0ed895f4f9c2ff06c6f0765aa86a7d7a30a96:
obslock: cleanup hold logic and resolve inheriting an expired hold.
Prior to fix the added test failed:
```
File "/home/jberry/osc-plugin-factory/tests/obslock_tests.py", line 116, in test_expire_hold
self.assertEqual(reason_sub, None)
AssertionError: 'hold: test' != None
```
Which demonstrates the issue seen in #823.
=> obslock: cleanup hold logic and resolve inheriting an expired hold.

osclib/stagingapi.py, osclib/unselect_command.py, tests/config_tests.py, tests/fixtures/project/staging_projects/openSUSE:Factory.json, tests/obs.py, tests/obslock_tests.py, tests/unselect_tests.py
- ad9ffc486ee554c24d336c87781e5027be61cb27:
tests/unselect_tests: add test for cleanup fitler.
- 4e26f2cb27a5b448230e3609252c69b8a979cecd:
tests/obs: define PROJECT as openSUSE:Factory.
- fb47742431d50d5e03ab74650986e5b6ab6b725d:
**unselect: add conditions to obsolete filter used by --cleanup.**
- 35fce8136699ae25b1443b86826b0fa020b00a4a:
stagingapi: project_status_requests(): provide filter function.
- 007ed1a21b98d2344fba9b21b1c8001f636a470b:
**stagingapi: project_status_requests(): filter requests changed < 5 min ago.**
Tests handle the cases of interest along with the general `< 5 min` case which also applies to `untracked`.
Fixes #871.
=> unselect: add conditions to obsolete filter used by --cleanup (along with refactor and tests).

osclib/stagingapi.py, tests/api_tests.py, tests/fixtures/source/openSUSE:Factory:Rings:1-MinimalX
We have a corner case that package A in Ring2 and points to package B in Ring1, map_ring_package_to_subject have to handle that as another non-inner project link case, ie. the sub-package link must be created.
https://github.com/openSUSE/osc-plugin-factory/issues/876
With this change:
```
maxlin_factory@tigercity:~> osc api /source/openSUSE:Factory:Staging:G/libunbound-devel-mini?expand=1
<directory name="libunbound-devel-mini" rev="97a63451d3b9e5fbc28d602e186ddd1b" vrev="4" srcmd5="97a63451d3b9e5fbc28d602e186ddd1b">
<linkinfo project="openSUSE:Factory:Rings:2-TestDVD" package="unbound" srcmd5="4386c97ad0b6541866be8b714a403f37" lsrcmd5="21343c588907214069c013b4886f7c48" />
Selected to :G
maxlin_factory@tigercity:~> osc api /source/openSUSE:Factory:Staging:G/libunbound-devel-mini?expand=1 …
```
=> Refactor map_ring_package_to_subject to support corner case

osclib/request_splitter.py
Simplistic precursor to #811.
If the consensus is that this is generally alright we can accept, but I can see this not always being the best. For things like KDE updates that are long standing stagings with fixes over a week or more this seems very useful, but for troublesome stagings it may just end up adding more clutter.
For example the proposal generated for Factory at the moment:
```yaml
0#devel@Base:System:
bootstrap_required: true
group: Base:System
merge: true
requests:
491274: bash
492375: rpm
492649: coreutils
492807: systemd
staging: B
strategy:
name: devel
1#devel@devel:languages:python3:
bootstrap_required: false
group: devel:languages:python3
merge: true
requests:
492721: python3-numba
492722: python3-llvmlite
492896: python3-fastcluster
492900: python3-patsy
492926: …
```
=> request_splitter: should merge: allow devel and super if not ready.

osc-staging.py, osclib/obslock.py, tests/obslock_tests.py
- 3d7a7d487b4b9ddf1eac2643c47b422213cc0a70:
obslock: unlock other user lock if force.
- f4523078b45f4f315eac79f93587516b03b100b1:
**osc-staging: skip lock for observation commands.**
Fixes #886.
=> osc-staging: skip lock for observation commands (and other unlock fix).

leaper.py
It seems unlikely that checking for requests would be acceptable for SLE.
Fixes #873.
=> leaper: indicate if submission is already accepted to SLE origin.

leaper.py
No idea how I managed to push this. I ran the code multiple times so I must have somehow added an underscore before commit.
=> leaper: drop extraneous _ prefix to src_srcinfo during in_sle_origin check.

check_tags_in_requests.py
Fallback to leaper which can wait for Factory submission.
I believe this does what was requested, but one should double check that the logic matches your intent. This will now accept any new package or one with tags. Otherwise, it will fallback and only accept if in Factory.
Fixes #900.
=> check_tags: accept immediately if tags instead of waiting for Factory.

osclib/unselect_command.py, tests/fixtures/project/staging_projects/openSUSE:Factory.json, tests/unselect_tests.py
- [492287](https://build.opensuse.org/request/show/492287)
- superseded by [494593](https://build.opensuse.org/request/show/494593), but declined
Such requests will never be unselected since the request is `superseded`. This still allows for requests to be reopened or the supersede chain continued while eventually cleaning it up if left to languish.
=> unslect: --cleanup handle superseded request that is never replaced.

check_source.py
It's a regression from https://github.com/openSUSE/osc-plugin-factory/commit/8db3461a00784e999cb3218c70d16a10b2e70f38
``show_project_sourceinfo`` is returned a string of `sourceinfolist` element. ie.
```
<sourceinfolist>
<sourceinfo XXX >
<linked XXX/>
</sourceinfo>
</sourceinfolist>
```
=> Fix wrong parsing from root

osc-staging.py
Would need to rename `osc-staging` to `osc_staging` to allow import for test. Would be annoying to have to tweak everyone's `~/.osc-plugings`, but does not seem like a bad idea in the long run.
Handles several styles while trying to avoid stripping commas from quoted messages.
```
select --move A pac1, pac2, and pac3
select --move A pac1,pac2,pac3
select --move A pac1,pac2,pac3 "a string containing a comma, in it even though it does not make sense"
unselect -m "a string containing a comma, in it" pac1, and pac2
```
Fixes #892.
=> osc-staging: provide clean_args() to allow for lists containing commas.

osclib/stagingapi.py
I noticed `staging-bot` crashed in logs and was able to reproduce locally.
```
File "/usr/bin/osc", line 41, in <module>
r = babysitter.run(osccli)
File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
return prg.main(argv)
File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
return self.cmd(args)
File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
retval = self.onecmd(argv)
File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
return self._dispatch_cmd(handler, argv)
File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
return handler(argv[0], opts, *args)
File "/home/jberry/.osc-plugins/osc-staging.py", line 597, in do_staging …
```
=> stagingapi: handle old source removed and assume supersede.

osclib/comments.py, osclib/stagingapi.py, tests/obs.py, tests/select_tests.py
- 33cad7287de926570868ad8100fcb10a7205efef:
stagingapi: update_status_comments() provide diff comments.
Instead of always providing a full comment whenever packages are added
an original comment will be posted and diff comments will be replied to
the original comment. The diff comments will provide a summary of what
changed while the complete state can be seen in the project pseudometa.
- 4e6cf006ddaa64c6a69a66509666fbefeed17483:
stagingapi: provide get_prj_meta_revision().
- 204d58e46515a31db2f0cf6f11a830a9bb98a044:
stagingapi: update_status_comments() utilize newer comment APIs.
- comment_find()
- add_marker()
- 4abbd8900ef7b0b4b07d19e18092df4f8503b702:
stagingapi: get_prj_pseudometa() provide revision parameter.
- 5f2d2f291084d6c7e3a90652238ed6b8c72a3563:
stagingapi: get_prj_meta() …
=> stagingapi: update_status_comments() provide diff comments.

osclib/stagingapi.py, osclib/supersede_command.py
- e91e12ab68ef782364aec79ced106f00f574df7f:
**stagingapi: rework supersede logic to handle different request types.**
- 39799f0235cbda9e96b1e5d7ac3a83a5c1e48e05:
stagingapi: include new request ID in supersede review message.
Fixes #808.
Since the supersede logic is rather complicated to handle with the given test setup there are no tests. As such this cannot be fully tested without finding one of each case in the wild.
=> stagingapi: rework supersede logic to handle different request types.

suppkg_rebuild.py
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]: Traceback (most recent call last):
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]:   File "/usr/local/bin/suppkg_rebuild", line 203, in <module>
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]:     sys.exit(main(args))
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]:   File "/usr/local/bin/suppkg_rebuild", line 185, in main
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]:     uc.crawl()
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]:   File "/usr/local/bin/suppkg_rebuild", line 135, in crawl
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]:     root = tree.getroot()
Jun 06 22:51:45 packagelists suppkg_rebuild[25461]: AttributeError: getroot
=> Fix suppkg_rebuild crash

osclib/stagingapi.py
=> stagingapi: skip supersede for next comment by updating requests_comment.

openqa-comments.py
- cd937e1f6141bb7c9beaac5d4bf5648dfae435e8:
openqa-comment: add headings to avoid paragraph formatting mess.
- c61247240b6ec495d135559a1b3aefac5815fce3:
openqa-comment: strip whitespace when only one type of openqa report.
The ugly formatting on some comments has bothered me for a while.
```
* Build failed rpm-python ([i586](https://build.opensuse.org/package/live_build_log/openSUSE:Leap:42.3:Staging:B/rpm-python/standard/i586), [x86_64](https://build.opensuse.org/package/live_build_log/openSUSE:Leap:42.3:Staging:B/rpm-python/standard/x86_64))
* Build failed rpm ([i586](https://build.opensuse.org/package/live_build_log/openSUSE:Leap:42.3:Staging:B/rpm/standard/i586), [x86_64](https://build.opensuse.org/package/live_build_log/openSUSE:Leap:42.3:Staging:B/rpm/standard/x86_64))
* Succeeding …
```
=> openqa-comment: add headings to avoid paragraph formatting mess.

openqa-maintenance.py
the /api/v1/jobs route in openQA returns the jobs in the 1, 10, 2, ..., 9 order.
So we need to avoid jumping backwards when we look for the latest build id
=> Work around wrong sorting of jobs

ReviewBot.py
BEFORE: 
```
$ python2 ReviewBot.py --dry -c ./pokus.yml
Traceback (most recent call last):                         
File "ReviewBot.py", line 575, in <module>               
sys.exit( app.main() )   
File "/usr/lib/python2.7/site-packages/cmdln.py", line 251, in main                                                  
retval = self.postoptparse()                           
File "ReviewBot.py", line 476, in postoptparse           
self.checker.load_config(self.options.config)          
File "ReviewBot.py", line 92, in load_config             
self.config = self._load_config(fh)                    
File "ReviewBot.py", line 86, in _load_config            
y = yaml.safe_load(handle) if handle is not None else {}                                                           
NameError: global name …
```
=> Fixes loading config file

leaper.py
Introduced in #890.
Before (all kinds of crazy that confused markdown parser):
```
Package is in [SUSE:SLE-12-SP2:GA](/package/show/SUSE:SLE-12-SP2:GA/lua-lmod) ([diff]([[SUSE:SLE-12-SP2:GA/lua-lmod](/package/rdiff/network:cluster/lua-lmod?opackage=lua-lmod&oproject=SUSE:SLE-12-SP2:GA&rev=10)]))
```
After:
```
Package is in [SUSE:SLE-12-SP2:GA/lua-lmod](/package/rdiff/network:cluster/lua-lmod?opackage=lua-lmod&oproject=SUSE:SLE-12-SP2:GA&rev=10)
```
=> leaper: correct invalid diff link when package present in SLE.

issue-diff.py, osc-staging.py, osclib/check_duplicate_binaries_command.py, osclib/core.py
Fixes https://progress.opensuse.org/issues/17996.
`osc staging list` works to see output.
What is the desired outcome of the command? Doubtful there can be any automated resolution as it will likely require deleting packages. Simply print a list of duplicates?
Seems like we want to integrate with repo checker potentially and a one off command potentially similar to `devel-projects.py` that could generate a map/list in dashboard container to be picked up by repo checker and refreshed nightly. Could enhance to only rescan packages that have been updated.
=> Detect duplicate binaries within a project

osc-cycle.py
This new plugin creates dot files, visualizing the relation between the
package speciied on the command line. A major use case is visualizing
build cycles that are reported by OBS, but often not very clear to debug.
=> New osc plugin 'cycle': help visualizing build cycles

osclib/comments.py
=> comments: avoid attempt to delete non-existent parent comments.

.travis.yml, dist/ci/Dockerfile, dist/ci/deploy.obs.sh
Should be updated to point to proper home once accepted. Could also use a different user, not sure if there is a standardized one for this type of deployment.
Might also be worth submitting a proper OBS deployment plugin for Travis.
=> travis: add deployment to OBS package on master branch commit.

dist/ci/deploy.obs.sh
I have this in my normal scripts, but for some reason didn't think it was needed. Minor fix to keep sources from only being added.
=> dist/ci/deploy.obs.sh: remove previous source.

.travis.yml, Makefile, dist/package/openSUSE-release-tools.spec
- 5dde1801da242b02d1a503e9caf804c962dc7786:
travis: target proper home in openSUSE:Tools for deployment.
- 32aa60bab48a1bd65b64d919d6e8574c583fc450:
dist/spec: utilize obs_scm renaming which properly includes version in source.
- 651c7d57f136d4f49461a533633c3f093e6ab9a4:
travis: include OBS_EMAIL environment variable when deploying.
- 95c43d0ce68bd959d54ea7ea34bc98bd297d16fa:
dist/spec: include %defattr on all %files entries.
- dc07d5980b5a94d736f771c71cbf52dbca423488:
dist/spec: add missing osc requires.
Just missing SLE deps or branch in proper repo from #1007.
=> dist/spec: utilize obs_scm renaming which properly includes version in source (and followups)

dist/ci/Dockerfile, dist/ci/deploy.obs.sh
- 8de99935bb9aec86d1bfda2164ff02fa3c2e020e:
dist/ci/deploy.obs.sh: include apiurl in general so email is used during service run.
- 8df27b1de275505134c012950b70f9bed2ca53bf:
dist/ci/Dockerfile: include obs-service-{download_files,format_spec_file} for deployment.
=> dist/ci/deploy.obs.sh: include apiurl in general so email is used during service run.

devel-project.py
- 623e9d5cbf71c1142a6b9816703e33caec02bcdf:
devel-project: provide maintainer command to check for relevant groups.
- cf65210d2c39d0a2f6bcab74de211a928a0d2dd6:
devel-project: get(): utilize osc.core.search() and improve xpath loop.
Would it make sense to expand this to auto request roles for relevant groups (and could even run nightly to auto followup on new devel projects). Equivalent to:
```
osc requestmaintainership PROJECT group:NAME
```
Fixes #1001.
=> devel-project: provide maintainer command to check for relevant groups. (and search() usage)

osc-cycle.py
Instead of crashing on packages that do not exist, simply skip over them, but
add the package as 'unlinked' into the graph
=> osc-cycle: ignore invalid packages

create_test_Factory_dvd-2.testcase
Accompanies https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3171
openQA no longer tests postgresql94, but 96, so we need to follow suite here
=> Factory test dvd: upgrade to postgresql96

devel-project.py, osc-staging.py, osclib/conf.py, osclib/stagingapi.py, repo-checker.pl, repo_checker.py, suppkg_rebuild.py, tests/config_tests.py, totest-manager.py
- 491a42ee858d3948c98878b5de72b4d177464a61:
**repo_checker: provide project_only subcommand to write result to installcheck.**
- 8f0aba6d6227a7372663a4a9b0aef91fb129f6c7:
repo_checker.pl: allow empty $repodir allowing just a project-wide check.
- 797c92f26b2702acacb1b49c7fe71f7189351851:
stagingapi: provide dashboard_content_{load,save,ensure}() and utilize.
Finally decided to add dashboard_content specific methods since the same pattern is all over. Makes for a bit cleaner usage.
This is still relevant since the `repo_checker` will only actively check requests and ring packages. This check should run once a day against the whole project to see if anything introduced due to interesting build interactions or packages staged separately.
The existing bash script will be replaced by …
=> repo_checker: provide project_only subcommand to write result to dashboard/repo_checker.

check_maintenance_incidents.py, check_source.py
Since the new repo_checker does not require maintainer submission `check_source` will now add the review in-line with other responsibilities. This is the same style as `leaper.py` although the code-base could likely use a bit or re-organization.
For example:
```
./check_source.py --osc-debug --debug --dry --group factory-auto --review-team=None id 511969
GET https://api.opensuse.org/request/511969?withfullhistory=1
INFO:check_source.py:checking 511969
GET https://api.opensuse.org/source/openSUSE:Factory?view=info&package=python3-twine&nofilename=1
GET https://api.opensuse.org/search/owner?project=openSUSE%3AFactory&binary=python3-twine
DEBUG:check_source.py:author: sebix, maintainers: aledr,TheBlackCat,matejcik,sleep_walker,apersaud,posophe => need review
INFO:check_source.py:POST …
```
=> check_source: add devel review for delete request using MaintenanceChecker logic.

dist/ci/Dockerfile
Test on travisci already https://travis-ci.org/openSUSE/osc-plugin-factory/builds/259612273.
=> dist/ci/Dockerfile: drop hard-coded mirror now that Tumbleweed issues resolved.

osclib/cycle.py, repo_checker.pl, repo_checker.py
- e526c964c989cf97c1f9ad6e24ef306b7c02ecc2:
osclib/cycle: remove extra leading slash.
- f56cb54d9046dc51464105dd3ecb2b336328a1ed:
repo_checker: add whitelist for adoption phase.
Given all the pent up issues hidden by the previous checker this is sadly necessary.
Workaround for #1012 during adoption phase.
=> repo_checker: add whitelist for adoption phase.

ReviewBot.py, osclib/core.py, repo_checker.py
- f42cc4bcc9f599b1059127e7ce310fe926e3eef6:                                                                                                
repo_checker: truncate long messages to avoid crashing OBS.                                                                            
- 722764a1f528e0cb9bd1cc9a29086c7f04656c32:
**repo_checker: provide --post-comments option on project_only subcommand.**
- ce35a686ddafa6dd8943ef808fa5e7ee1e0c4f93:
repo_checker: provide optional parsing of install check output and mapping to package.
- d87ee4c38ea59ed86f87774113b9d5bcf060374f:
repo_checker: package_whitelist() does not need to support group splitting to find product.
- 924db6024b3587a177ce860a27b9d5d46886d9f0:
osclib/core: provide package_binary_list() to efficiently obtain binary to package map.
- …
=> repo_checker: provide --post-comments option on project_only subcommand (and cleanups).

osclib/check_duplicate_binaries_command.py
We can leverage an api call that returns all binaries.
=> Speed up duplicate binaries check

update_crawler.py
Hack to make update crawler work for SLE15. Really needs refactoring on
ToolBase.
=> update crawler: latest_packages across instances

check_source.py
To distinguish from the old factory-repo-checker and use a generic name applicable to Leap as well.
Seems like the best plan to use the same user for identical bots to remove any possible confusion by being consistent. There are no other references, outside of tests, in this repo, and I would not expect them elsewhere.
=> check_source: change repo_checker default to new OBS username.

osclib/accept_command.py
Have to clean up supportpkg list also during accepting staging project, otherwise suppkg_rebuild can not handle it correct in case next time staged package in the same staging project had the same supportpkg list.
=> suppkg_rebuild: Clean up supportpkg list also

repo_checker.py
Due to https://lists.opensuse.org/opensuse-buildservice/2017-08/msg00035.html. Rather ugly.
=> repo_checker: ignore non-existant binaries during lookup.

dist/ci/Dockerfile
=> dist/ci/Dockerfile: include `dup` before `in` to handle major base changes.

osclib/stagingapi.py
Make sure the links of package in Rings must are valid before processing, otherwise someone had package linked to the Ring package in somewhere else than Rings will breaks select/delete/rm_to_prj, ie. _link will be created. Therefore, only return the candidate if it has proper linked from another ring and have different package name.
Example of failure:
```
mlin@rana:~> osc api -X POST `/source/openSUSE:Factory:Rings:2-TestDVD/telepathy-logger-qt5?cmd=showlinked
<collection>
<package project="home:Vogtinator:branches:openSUSE:Factory:Rings:2-TestDVD" name="telepathy-logger-qt5"/>
</collection>
```
=> stagingapi: Ensure the links is valid before processing

ReviewBot.py
- 164b04903cfc56828b08e0fbb6041d3cb15c6e67:
ReviewBot: add_review(): remove left-over print() line.
- d565f46123bc7208f034bfc8c2388a0eb4c79081:
ReviewBot: get_devel_project(): correct error handling to only allow 404.
The original intent was clearly to allow 404 (package does not exist for
new packages), but crash on anything else. Instead it consumes all
exceptions and does nothing different even with the e.code condition.
=> ReviewBot: get_devel_project(): correct error handling to only allow 404.

osclib/core.py
This allows for cases where the requested project was something like openSUSE:Leap:42.3:Update and the returned project was openSUSE:Leap:42.3. With this change the fallback will be triggered and the global maintainer will then be used.
Worth considering if this will negatively effect `leaper` or `check_source`.
Fixes #1068.
=> core.owner_fallback(): check if startswith() instead of equal.

osclib/stagingapi.py
In the say way that I had to rework the supersede logic to actually keep track of what changes were made to print messages indicating the changes the select and unselect commands should likely know if the command they were asked to evaluate ended up doing nothing rather than just calling `update_status_or_deactivate()` always. Short of that ends up not being an issue except for `update_status_comments()` so just check for empty `package-diff` comments to avoid making them.
Fixes #1081.
=> stagingapi: avoid making an empty package-diff comment.

ReviewBot.py
The output is rather verbose, especially inside journals, and not terribly helpful.
```
[D] openSUSE:Factory:Staging:M:DVD/i586 not available
[I] cycle check: start
[I] cycle check: passed
[I] install check: start
[I] install check: passed
[D] no previous comment to replace on openSUSE:Factory:Staging:M
[I] can't change state, 517044 does not have the reviewer
[I] 517044 accepted: cycle and install check passed
[D] 517044 review not changed
```
vs (similar output)
```
INFO:repo_checker.py:install check: failed
INFO:repo_checker.py:mirroring openSUSE:Factory/standard/i586
DEBUG:repo_checker.py:openSUSE:Factory:Staging:adi:259/i586 not available
INFO:repo_checker.py:cycle check: start
INFO:repo_checker.py:cycle check: passed
INFO:repo_checker.py:install check: start …
```
=> ReviewBot: simplify logger format.

ReviewBot.py, repo_checker.py
- ad9f76bf4618081958a0bd491c0d1750b25fd7b5:
repo_checker: post passed comment only if previous failed comment.
- ebd2f580ec2ddf13e23c6beb88ec625bffd183fe:
ReviewBot: comment_write(): provide only_replace option.
- ca13855d2e8829b70df2f446d347164db586a883:
ReviewBot: comment_write(): pull dryrun protected bit out individually.
- 757d31cf35ab19605b4ea989beda74e3669ad4af:
ReviewBot: comment_write(): place debug_key at the end for consistency.
If turns out to be handy, it could be useful for other bots to behave in a similar fashion.
=> repo_checker: post passed comment only if previous failed comment (and debug improvements).

osclib/comments.py, repo_checker.py, tests/comment_tests.py
- c8ee7dc2cf2034ace88d56c69766ee81fc8cf7d2:
repo_checker: package_comments(): drop truncation in favor of commentapi.
- b8dc98a6e93efb423ed8d4bce38358cb0796ea36:
commentapi: provide truncate() and apply during add_comment().
Current limit from openSUSE/open-build-service#3584, but should likely be lower due to serialization in openSUSE/open-build-service#3638.
Fixes #1061. All comments will now automatically be truncated while handling preformatted text and not breaking tags or leaving unbalanced tags.
=> commentapi: provide truncate() and apply during add_comment() (and use in repo_checker).

osclib/cycle.py
With the new repo_checker utilizing the staging process none of this should be necessary.
I ran against the texlive staging a few days ago, but could wait for another to confirm. All of the other ignore lists were removed in main `repo_checker` as the root cause seemed to be mixing devel project packages deps with target project which is no longer done.
These packages are in rings, so they are checked during any letter staging review and those pass with this code as well.
=> cycle: remove ugly ignore code from _get_builddepinfo_graph().

repo_checker.py
Other `<pre>` switch in #1089, but I'll just leave it there as a lot to break out.
=> repo_checker: use <pre> instead of ``` to avoid html entity escaping.

dist/package/openSUSE-release-tools.spec
Presumably this will fail travis until new `osc` is in Tumbleweed. Now that the package is situated it may make sense to rework build test to build out of `openSUSE:Tools`.
=> dist/package/spec: utilzie %osc_plugin_dir provided by osc post sr#512849.

osclib/stagingapi.py
This allows for project configuration to be injected.
Fixes #1102.
=> osclib/stagingapi: create_adi_project(): use :Staging passthru project.

.travis.yml
It seems upstream changed packages so this is no longer available by default.
Fixes #1118.
=> travis: install libxml2-utils which provides xmllint.

repo_checker.py
I duplicated Factory config so it will work both ways. Once this has been confirmed deployed we can drop the old form, but best to do this sooner rather than later.
Fixes #1096.
=> repo_checker: rename package-whitelist to binary-whitelist to be more accurate.

ReviewBot.py
- eb350bdf73a2d4dd62dd9878808117fdc4ad43da:
ReviewBot: comment_write(): skip posting empty comments extracted from handler.
- 17d8ea8b3a606b161f778df3bc0afd1ea4fb8580:
ReviewBot: downgrade message about skipping duplicate review to debug.
This matches the original intent along with ensuring such messages never
end up in the default CommentFromLogHandler.
Such comments are possible post #1100.
=> ReviewBot: comment_write(): skip posting empty comments extracted from handler.

osclib/stagingapi.py
This seems like the best solution since any other default values make little sense to change in remote config.
Replaces #1116.
=> osclib/stagingapi: lazy-load nocleanup-packages to allow for placement in remote config.

dist/package/openSUSE-release-tools.spec
To make it clear one needs to be running recent `osc`.
=> dist/package/spec: include version on osc Requires.

osclib/freeze_command.py, tests/fixtures/staging-meta-for-bootstrap-copy.xml
Products are too touchy - I had now 3 cases where the product would not
rebuild if a meta package changed
=> Do not use direct flag for images

osclib/list_command.py, osclib/request_splitter.py
This change allows SLE to more effectively use `--try-strategies` since `devel` and `super` strategies have useful grouping information. It also effects `adi` and `list` command output grouping. As such I would like those involved with SLE to agree that the output change is desirable.
```
00
139414 dmapi                          -> 1-MinimalX   (delete request)
needs changes in installation-images
139651 ffado-mixer                    -> delete       (delete request)
home:RBrownSUSE:branches:SUSE:SLE-15:GA
139609 patterns-sle                   -> 1-MinimalX  
openSUSE.org:openSUSE:Factory
137876 libquvi-scripts                -> 1-MinimalX  
problematic for now
137881 lua51                          -> 1-MinimalX  
problematic for now
137882 lua52                          -> 1-MinimalX …
```
=> osclib/request_splitter: for SLE, fallback to openSUSE:Factory devel projects.

osclib/freeze_command.py
Make freeze SLE Staging's DVD subproject can work. Update product version is necessary for openSUSE only.
=> freeze_command: update product version for openSUSE only

data/apimap.json, data/incidents.json, openqa-maintenance.py
I'm working on this for a week and more - it's no longer looking at requests, but at incident projects and test updates and then only aggregates into the request if it opened.
This way the release managers get to know about problems in incident *before* they open the request into testing.
But I didn't find a good way to make this work for opensuse too - and the kgraft testing needs work too.
=> WIP: Major rework of the openqa bot 

osclib/stagingapi.py
Allows for packages being added to rings to remain enabled after being superseded.
Likely need to test on a local OBS, build out a supersede test case (not trivial), or cross-fingers.
DO NOT ACCEPT UNTIL SOMEONE HAS HAD A CHANCE TO SEE THIS WORK.
Fixes #896.
Presumably, it is desirable to keep sub package states which is what I did.
=> stagingapi: carry over build state during supersede.

osclib/list_command.py, osclib/request_finder.py
- 0f869ab8867dbe15b41b9bf0978141879e947a6a:
osclib/request_finder: restrict to submit and delete request types.
This avoid set_bugowner and change_devel requests from causing a select
command to die due to more than one request.
- 77e70feef706eb184ea5c64992931a998d430314:
osclib/list: rework change_devel_requests to include set_bugowner.
Since set_bugowner requests are essentially equivalent to Factory
change_devel requests they should be presented in the same manor.
- 4234706f30bcfe00e39532b1c83d8fb698c5bcc9:
osclib/list: only present submit and delete requests in main list.
Should be verified by @coolo since SLE is the one having the problem, but openSUSE will benefit from not crashing if people make these type of requests.
=> Handle set_bugowner requests to avoid mixing them where they do not belong

osclib/stagingapi.py
The new logic is introduced, the description is below:
* If adi package: return sub-package list according to the specfiles of main package.
* If ring package: return sub-package list by showlinked call and the sub-package must be in another ring.
* The others: return empty list, no reason to return anything or even checking it in the devel project. Otherwise selecting a non-ring package to a letter staging probably would created unneeded sub-package.
With this, https://github.com/openSUSE/osc-plugin-factory/pull/948 should work.
=> stagingapi: refactor get_sub_packages() to support adi package

osclib/stagingapi.py
The variable project might got changed through map_ring_package_to_subject(), according to release process, we have to given the origin project path to set_review() always.
The case would like - a ring2 pacakge's review was a letter staging project and it can not be accepted as the `project` variable is changed to `$PROJECT:DVD` , accepts `:DVD` review is wrong. Regression from https://github.com/openSUSE/osc-plugin-factory/commit/831c73a3bc2cfca45bbb69a10244ad295329ea40
=> rm_from_prj: always use the origin project path to set_review()

osclib/stagingapi.py
Fixes #1142. The comments part anyway.
=> osclib/stagingapi: accept_status_comment(): avoid making comments for empty projects.

osclib/adi_command.py
If users build against an adi project OBS will refuse to delete, but in
that case breaking other projects is fine as the branches should only be
used to work on fixes seen in adi stagings.
See #1142 for an example, details, and discussion.
Fixes #1144.
=> osclib/adi: include force=True when invoking delete_project().

osclib/adi_command.py
Wihtout selected_requests then that adi staging project is an empty project, adi command should clean it up rather than go through the logic to check the project status. Since we have introduced a kind of frozenlinks adi staging, the project status might be build broken or so but it doesn't have any request
staged in that staging actually, those kind of projects must be deleted.
=> adi_command: do not checking adi staging status if there is no selected_requests

check_source.pl, rebuildpacs.pl
As noted by @DimStar77 the packagelists machine filled up `/tmp` and these two instances seem to at least leave directories behind and are thus worth fixing. It is also possible that the perl scripts crashing will leave behind the tmp directories.
I ran `check_source.py` locally and verified the fix works correctly before and after. Currently running `repo_checker.py`
=> Include CLEANUP => 1 during temp directory creation in perl scripts.

osclib/accept_command.py, osclib/conf.py, osclib/stagingapi.py, tests/api_tests.py, tests/obs.py
https://progress.opensuse.org/issues/20420
Workflow:
* selecting a request to a staging, the pseudometa is changed to 
{id: 100, package: FOO, author: user, type: submit}
{id: 101, package: BAR, author: user, type: delete}
* during accepting a delete request:
If 'type' is exists in pseudometa and delreq-monitor was set in conf.py, the delete request will through *virtual accept* process, the binary will be removed on standard repo. If 'type' is not exists, go through the old route make sure it will not break the current stuff.
* in the later check-in round:
If it has found the virtual accepted request's package doesn't have binary on any build repo in the main project, the accept command accepts delreq-monitor review and continue accepts this request to the main project via …
=> Implements virtually accept the delete request

leaper.py
Some projects may not exist yet, such as SLE :Update.
Don't bail out because of that.
=> leaper: ignore 404

ReviewBot.py
- caa7ab5560ac96df223fb0b63a144bf81a1dc692:
ReviewBot: comment_write(): add overview documentation.
- b886949e836efd45367bfa748dec4530fc90bc14:
ReviewBot: comment_write(): add info_extra parameter.
In order to move forward rather than pretending that the refactored `CommentAPI` and `ReviewBot` code cannot handle the [openqa comment case](https://github.com/openSUSE/osc-plugin-factory/pull/1148#discussion_r141487855).
=> ReviewBot: comment_write() add info_extra parameter (and overview documentation).

Makefile, Makefile.common, dist/package/openSUSE-release-tools.spec, repo_checker.py, systemd/osrt-repo-checker-project_only@.service, systemd/osrt-repo-checker-project_only@.timer, systemd/osrt-repo-checker.service, systemd/osrt-repo-checker.timer
Should be first service compatible with #1006.
@lnussel: We can use to deploy for IBS.
=> dist: provide repo-checker sub-package with binary in path, service, and user.

check_source.py
- a825af82a0f9f04d2a82766556ebf8c4da6cec9a:
check_source: lookup staging group using StagingAPI rather than flag.
- c081de602564c16b96e19de459621f3808b08a07:
check_source: interpret "None" as python None for review-team and repo-checker.
Allows for disabling adding those reviews from the command line.
- 1e9c389617b0b9f9dee77ef36cb27879652fd8de:
check_source: drop inaccurate "with > 8 diff" from --review-team option.
- 73df8871f14812dabb78a6dac675e9fc7169b70c:
check_source: drop unnecessary dest from add_option().
Fixes #1015.
For SLE `review-team` can be disabled and devel check disabled. Leap works with just devel check disabled.
```
./check_source.py -A ibs --debug --dry --ignore-devel --review-team None id 142766
[I] checking 142766
[I] …
```
=> check_source: allow usage by SLE to primarily add repo-checker review

.travis.yml
Unfortunately, since nearly impossible to test deploy scripts as run by travis missed including environment variable during deployment run in #1171. The script itself works as I tested locally, but missed the variable so it ran `osc request list "" "openSUSE-release-tools"` which does not match grep and thus does not create submit.
=> travis: include OBS_TARGET_PROJECT env variable during deploy script.

.travis.yml, dist/ci/deploy.obs.sh
Same reason as #1172, works, but too quick since after commit OBS spends a second or two try to run `_service` which ends up being a nop.
While I was at it made link detection automatic.
- 4161a7ec0dd7e09b707ffd3a558c57707f047b7b:
dist/ci/deploy: pipe `osc sr --diff` to cat to ensure same behavior manually run.
- ace27a9385187d20052e19dfd12f61bb9f8e084b:
dist/ci/deploy: automatically detect target project and package.
- a99faac2ba29c8a4a1b34f2cf9f6a629cee053b7:
dist/ci/deploy: wait for service to complete before create submit request.
=> dist/ci/deploy: wait for service to complete before create submit request (and automatically detect link)

dist/ci/deploy.obs.sh
One of those days...when a fresh checkout is performed prints "expanded link" instead of "project". Follow-up to #1173.
Really would be nice to be able to test this in full environment.
=> dist/ci/deploy: handle expanded links during target project loookup.

check_source.py
https://build.opensuse.org/request/show/530180 is an example where this actually happened. Really not something we want to see
=> check_source: Ensure the source and destination package name matches

Makefile, dist/package/openSUSE-release-tools.spec, systemd/opensuse-totest-manager.service, systemd/osrt-totest-manager@.service
=> dist: rework totest-manager subpackage to provide new style service.

openqa-comments.py, osc-staging.py, osclib/config_command.py, osclib/freeze_command.py, osclib/stagingapi.py, repo_checker.py
- 1e39042569e5b05cd64a4dc3419920453202175c:                                                                                                
repo_checker: filter empty whitelist entries.
- f0ff9cb542ded92de4279cffa2b31e8b063df235:
repo_checker: utilize staging configuration for whitelist additions.
- d2b50c0a1bb8e5edfd764f283830fdb0b407d459:
osclib: provide ConfigCommand and expose via osc-staging.
- 336a0e54addf4f8122e1e338c4134acf3c47c63b:
osclib/stagingapi: get_staging_projects(): provide include_dvd option.
I played around with various approaches for modifying `osclib/conf.py` to be able to apply staging config, but given that for the `repo_checker` use-case the values are to be appended and I cannot foresee trivial uses of this elsewhere I left it up to utilizing code to use the …
=> osclib: provide ConfigCommand and expose via osc-staging (utilize in repo_checker)

check_source.py, osclib/conf.py
- c05a26d154818b2725a1dc1e1d07d89df478a2a0:
check_source: move all relevant flags to config to work properly without flags.
- 52af5b3d75a1840132b65c616e473def136f5840:
check_source: print message if checking devel project.
Currently, no indication unless ends in decline. More important when moving
option to config rather than flag.
This approach seems preferable to flags, just as I already moved devel whitelist to be able to load from remote config. It means users do not need to know the right flag combination to run the tool, rather it just figures it out. This also means we can run same service with same options and same user on OBS which again seems preferable.
=> check_source: move all relevant flags to config to work properly without flags.

check_source.py
Decline the delete request in case there is pending delete/submit request to the same package, if there is another submit request against the same package that we should prefer the submit one which should be passed staging already, what it means just queued for accepting, like request go through adi or virtual accept delete request.
Fixes https://github.com/openSUSE/osc-plugin-factory/issues/1193
=> check_source: decline the delete request if duplicated

totest-manager.py
The totest-manager crashed on Factory:ARM when it tried to release
a build.
=> Fix undefined variables 'release'

osc-staging.py
- f6ce6deb87afe2998d0245cf754afee1fb5976b0:
osc-staging: select -i: s/merged/mergeable/ in stat comment.
- 96ac84064698f5ab582a02732f5d2dc19fc80b77:
osc-staging: select -i: include remaining requests in comment.
Useful for manually adding open requests to proposal.
=> osc-staging: select -i: include remaining requests in comment.

osclib/request_splitter.py
- e8c27991568f69e7db699dfde0953914df01f9fe:
osclib/request_splitter: reduce default list of special packages.
- c9743b5df0a7d48d4ece942c76a5a3c657c6e713:
osclib/request_splitter: provide splitter-special-packages config variable.
@coolo Can thus be overridden by project config (like for Leap or SLE).
@DimStar77 The default reduction to special package list look already?
=> osclib/request_splitter: provide splitter-special-packages config variable.

devel-project.py, dist/package/openSUSE-release-tools.spec
The addition of queries to search() breaks the altered implementation of search. The custom search() can be dropped since openSUSE/osc@902b48f provides the missing functionality.
Fixes #1205.
=> devel-project: utilize get_request_list(withfullhistory) param provided by osc 0.160.0.

.travis.yml
I always suspected based on percentage and change, but when working on #1207 I dug in when trying to get `check_source.py` to show up in report as covered. It's a bit interesting that no `--cover-package` argument will no result in what you would expect as documentation indicates current directory which one would assume is the same as `.`, but apparently not in nose land.
Makes sense to correct this before I finish up the fancy test PR so we can see the impact.
Summary: PITA + overly optimistic coverage reports.
=> travis: include all files instead of just osclib in coverage.

tests/obs.py
Otherwise, the real caches are cleared whenever tests are run.
Noticed while work on #1207.
=> tests/obs: move Cache.delete_all() after CACHE_DIR changed.

osclib/conf.py, tests/obs.py
This is consistent with expected behavior when using:
- osc.core.conf.get_config(override_conffile...)
Also removes the need to change the environment in OBS() which removes a leak.
Partial fix for #1214.
=> osclib/conf: prefer already parsed conffile over OSC_CONFIG env variable.

.dockerignore, .flake8, .gitignore, .travis.yml, devel-project.py, dist/ci/docker-compose-obs, dist/package/openSUSE-release-tools.spec, obs_clone.py, osclib/cache.py, tests/OBSLocal.py, tests/devel_project_tests.py
- bda410b5aa0c4fd1c99726d4ea60465c5e9c7459:
travis: provide local OBS setup and clone base data.
- 40f8ed27288f3ca877ad2709dc27269a080bde81:
tests/devel_project: provide basic test against local OBS.
- d3cf5fddf13faf45756411cd79d39f03d1bfcc6b:
tests/check_source: provide basic test against local OBS.
- 98963a8ebd9c25ac33355f9d47a50973b76d6d21:
tests/OBSLocal: provide based class for testing against local OBS.
- d87cd051a3be95fa687958aca68e1e4b2e2ebd06:
obs_clone: clone projects and dependencies between OBS instances.
- 438350ba4bd3f60ed0001396568b1a1a9b983b59:
devel-project: list: only remove self if in devel project list.
Summary of what this accomplishes:
- bring up local OBS from source using new `docker-compose` setup from `OBS`
- clone all relevant projects, groups, users, and …
=> Provide local OBS setup, base data creation, test harness, and initial set of tests.

osclib/memoize.py
Otherwise, multiple StagingAPI instances which are unique per project will share caches for short-hand projects. For example:
StagingAPI.project_status('adi:1') called on two different instances will share a cache.
Fixes #1224.
=> osclib/memoize: include first argument, sometimes instance, in cache key.

osclib/cache.py, repo_checker.py
- 95777e194f420d1a829af75ff11a3b3d0ed160cc:
repo_checker: project_only place dashboard update behind dryrun check.
- b8d81e15f6540d63217ff8b8a8dccfb88b8daa4c:
repo_checker: project_only ensure project repository is published.
- 9b7d12142c198a1075b6d3b858530eb9e6b6c085:
repo_checker: store and compare build hash to skip more aggressively.
Fixes #973.
Fixes #1029.
=> repo_checker: store and compare build hash to skip more aggressively (similar check for project_only)

systemd/osrt-staging-bot-devel-list.service
Need to confirm service file makes systemd happy.
=> systemd/devel-list: allow three retry attempts to handle regular OBS crash.

osclib/accept_command.py
If --force parameter is given, it must to force to change the request state, otherwise --force does not work if still had pending review.
=> accept_command: force to accept the staging if --force parameter is given

dist/package/openSUSE-release-tools.spec, osc-vdelreq.py
<pre>
maxlin@tigercity:~/.osc-plugins $ osc vdelreq list openSUSE:Factory
536563 lxqt-common state is review 
- Virtually accept review is new ( binary: Yes )
maxlin@tigercity:~/.osc-plugins $ osc vdelreq list --all openSUSE:Factory
527486 python-argparse state is accepted 
- Virtually accept review is accepted ( binary: No )
528637 vlock state is accepted 
- Virtually accept review is accepted ( binary: No )
529955 perl-CPAN-Meta state is accepted 
- Virtually accept review is accepted ( binary: No )
529956 perl-CPAN-Meta-YAML state is accepted 
- Virtually accept review is accepted ( binary: No )
530181 keybinder3 state is accepted 
- Virtually accept review is accepted ( binary: No )
530703 perl-YAML-Perl state is accepted 
- Virtually accept review is accepted ( binary: No )
530796 …
=> osc vdelreq: new command lists pending virtually accepted delete request status

Makefile, Makefile.common, dist/package/openSUSE-release-tools.spec, docs/metrics.md, systemd/osrt-metrics@.service, systemd/osrt-metrics@.timer
- a0c7dc362cd2670372c25b795ba25a0dede47bfe:
dist: provide metrics service and timer.
- 10311c12c66d230cb57cf70eb4a7bc72f8d5e1d8:
dist: install exported dashboards in grafana dashboard directory.
- 159790907e2f79c3586267b75a4a5ed65a7f6f7b:
dist: include metrics.py in bindir.
- 02d5749d2835fdc1d24aed253bb6536ed2433456:
dist: move package_name variable to Makefile.common.
Pre-requisite of #1170.
=>  dist: provide metrics service and timer and install grafana dashboards.

dist/package/openSUSE-release-tools.spec, metrics.py, metrics/grafana/compare.json, metrics/grafana/review.json, metrics/grafana/staging.json
- 9a6b483948b44602d612c54ea0b706f29a0d4bec:
metrics/grafana/review: include opensuse-review-team who graphs.
- 586b177a97d9620646600ccd2688a297f5bb9e61:
metrics/grafana/review: default to openSUSE:Factory.
- 736bfa235ea4060dbd5d9bda126ef7b228f67849:
metrics/grafana/review: disable annotations by default.
- 6aafeba0c1d6f63fa9bfab5ac7998a554295a2e7:
metrics/grafana/staging: "Project stats" to "Totals"
- 41c3c6948d9d0d8440121b9f78cc74023138ea85:
metrics/grafana/staging: remove 1s interval as it causes RAM issues.
- c01a8a71ed2a5bc251315205eb3ae5eca6b1374a:
metrics/grafana: standardize title prefix with 'OSRT: '.
- 0201a82722c2c73335081057bc9d3435651aa710:
dist/ci: grafana dir must be owned by grafana user since it writes lock.
- dc74b8d0be10f9efcbf0bd19a490878479982744:
dist/spec: correct …
=> metrics: post deployment tweaks and fixes + opensuse-review-team who graphs

check_maintenance_incidents.py
Perform src_project checks only on actions that actually have a
src_project
closes #1239
=> Don't die on delete requests

metrics.py
- d1b6125d4f2bfa1b2754d665dd331a4e50b8843a:
metrics: rework to store points as named tuple and write in batches.
Savings of around 400MB per 10,000 requests. Using a named tuple was the
original approach for this reason, but the influxdb interface requires
dict()s and it seemed silly to spend time converting them. Additionally,
influxdb client already does batching.
Unfortunately, with the amount of data processed for Factory that will
continue to grow this approach is necessary. The dict() final structures
are buffered up to ~1000 before being written and released. Another
benefit of the batching is that influxdb does not allocate memory for the
entire incoming batch.
- 6a2598779286d5b842bddd81f4a0e65ba61b1393:
metrics: rework request pagination to provide as generator.
This prevents the …
=> metrics: reduce memory footprint by over 60%

dist/package/openSUSE-release-tools.spec
- f3d23f31f58356f218d7fd4613251388270ae452:
dist/spec: restart totest-manager instances properly.
- e45fe4814a4970dcfe2bfd487c438eea4f0eee61:
dist/spec: only run %systemd_postun for oneshot services.
Fixes #1243.
=> dist/spec: only run %systemd_postun for oneshot services (and handle instanced services)

issue-diff.py, osc-staging.py
Fixes #1271.
@fcrozat: if you have the time could you confirm? I tested with `cat -n`.
=> Split EDITOR environment variable to handle flags in prefix.

osclib/cache.py, osclib/cycle.py
- 824fc98afd276befc345bc8be2c0ba2b05a0c251:
osclib/cycles: only cache target project build graph to avoid excessive cache.
- 57d9d2986bf96cc104fc413707780a2ae12dddf9:
osclib/cycles: drop _get_builddepinfo and _get_builddepinfo_cycles since unused.
Fixes #1265.
=> osclib/cycles: only cache target project build graph to avoid excessive cache.

rebuildpacs.pl
Rebuildpacs has quite some issues when it comes to multibuild packages as
it can trigger packages over and over.
This works around the major pains for now, see https://github.com/openSUSE/osc-plugin-factory/issues/1222 for
more details.
=> rebuildpacs: Ignore some more multibuild packages

totest-manager.py
Fixes a problem I saw in the logfiles 'ERROR 'ToTestFactory' object has no
attribute 'update_pinned_descr'' in case of a failed snapshot.
=> totest-manager: Make sure internal object for notifications is always valid

osc-cycle.py
This allows the user to simply copy a list from OBS' webui, which happens to be comma-separeted, without having to manually modify the list, saving another minute of tedious work
=> Auto strip commas from the command

osclib/freeze_command.py
Side note: do not need to give it arch parameter as the result list should not architecture specific.
Fixes https://github.com/openSUSE/open-build-service/issues/4245
=> freeze_command: use result call to get proper multibuild package information for aggregatepac

rebuildpacs.pl
perf needs to be rebuilt when kernel-source changes
=> rebuildpacs: rebuild perf

fcc_submitter.py
Do not add multibuild flavor package to the list, only main package should lists in the pacakge list, also make sure all flavor under multibuild pacakge are build succeded otheriwse drop the main package from the list.
For example:
<status package="lua-lua-dbus" code="excluded" />
<status package="lua-lua-dbus:lua51" code="unresolvable">
<details>nothing provides lua51-ldbus</details>
</status>
<status package="lua-lua-dbus:lua53" code="unresolvable">
<details>nothing provides lua53-ldbus</details>
</status>
would not be added to the list, the case below is going to be added,
<status package="lua-ldbus" code="excluded" />
<status package="lua-ldbus:lua51" code="succeeded" />
<status package="lua-ldbus:lua53" code="succeeded" />
=> fcc_submitter: handle multibuild package in build_succeeded package list

ReviewBot.py, osclib/comments.py, repo_checker.py
In effect, only update comment when either:
- target project is published and build hash has changed
- comment changed
Best of both worlds presumably.
Changes the identical comment comparison to first strip the comment marker before comparing text to allow for non-identical `info_extra` to be present in comments that are compared.
Still some edge-cases for long-running cases where state changes during/before review, but at most a second comment might result for one project.
In the process of testing more extensively.
Fixes #1296.
=> repo_checker: only update comment if published or message changed.

check_source.py
Otherwise, causes fatal crash trying to access self.repo_checker.
Confirmed crash and fix after be running.
```
./check_source.py --osc-debug --debug --dry id 561280
```
Fixes #1204.
=> check_source: load target project config during check_action_delete().

osclib/stagingapi.py
Fixes #1304.
I have a test prototype, but too much local hax to run it pending #1221.
Tested again by running:
```
osc staging adi --move wine
```
Which moved [request 561156](https://build.opensuse.org/request/show/561156) and enabled `i586` in the new staging where it was not enabled in previous and had `repo-checker` comment.
=> osclib/stagingapi: detect baselibs.conf in adi package and ensure archs enabled.

osclib/conf.py
Originally, my thought was to add the flags back and take them as defaults if unable to load project config, but that would require the continued use of that pattern for all `ReviewBots`. `repo-checker` already has a pending issue to support devel projects (#1210) and makes use if this config in the same manor. It seems more useful to allow the config to work for non-openSUSE/SUSE projects. Obviously, `StagingAPI` will not work for them, but the config and local overrides should. Additionally, `remote-config` could work if a project decided to add a `dashboard` container, but not something I am worried about at the moment.
Tested using the following.
```
./check_source.py --osc-debug --debug --dry id 539170
```
The `gnome-review-bot.service` on `packagelists` should be changed:
```diff
- …
```
=> osclib/conf: allow devel projects to utilize tools that require conf.

tests/OBSLocal.py, tests/comment_tests.py
Since generally helpful and making a variety of changes of last couple months to this heavily relied upon code it seems worth a few more tests.
=>  tests/comment: flesh out tests and fix OBSLocal same process authentication.

tests/ReviewBot_tests.py
Following on the footsteps of #1318. The important `comment_write()` functionality is basically fully covered.
=>  tests/ReviewBot: add full set of comment_write() tests.

osclib/conf.py, tests/config_tests.py
- 61c83500d3ca8a21b772fc1100437411a8643a71:
osclib/conf: allow devel projects to utilize tools that require conf.
- 865750258cd853dc4d69f42b307522cf58b76891:
osclib/conf: order config defaults by priority.
Ensures that less specific patterns do not overtake more specific patterns
by allowing for priority based ordering.
Followup to #1321 which was reverted due to catch-all pattern being ordered before SLE. The lack of ordering is pre-existing, but luckily not encountered. I went ahead and added an optional `priority` key to allow for clear sorting. This could also be done by defining the defaults using `OrderedDict`, but this seems preferable.
I added a lower priority to the general (older) SLE config since it would gobble up SLE-15 if mis-ordered. Included a test while at it. :)
=> osclib/conf: order config defaults by priority and allow devel projects to utilize.

osclib/conf.py, pkglistgen.py, systemd/osrt-pkglistgen@.service
As indicated in #1312, I had not yet performed a complete run so it was not clear everything worked. The following as tweaks needed to fix some minor issues and added `--dry` handling for `undelete_package()` from wrappers. One interesting bit is `LOCALES_FROM` was set to `openSUSE-product`, but as far as I can tell either this was not trickled all the way down or should have been `openSUSE.product` (period instead of dash) [@lnussel thoughts?]. Also added config mapping for remaining flags which is likely main bit needed for SLE.
Still completing a full run locally before updating tortuga.
- ce650ffbdbf15e1ef62fea746b49c29fcbd63391:
pkglistgen: update_and_solve: include step in output for debugging.
- 407a802fec8ae64ade1e3ac761bf16b7351e34c5:
pkglistgen: update_and_solve: handle --dry …
=> pkglistgen: migrate bash scripts to python followup

dist/package/openSUSE-release-tools.spec, pkglistgen.py
- ba07d6b51271bee7b8d2da07490898f9c50da13c:
pkglistgen: do_update_and_solve: staging correct :DVD subproject append.
- cf2b591c09622949dc852ebd22f64967d90e7c0c:
pkglistgen: first pass __file__ through realpath due to packaging symlink.
Same setup as repo-checker.py rather than what worked due to wrapper
scripts.
- 80f46a2d5d7b4f87c7f356184258b82cd8799903:
dist/spec: move pkglistgen.py under subpackage ownership.
- 5a2d955dfb4099a52e873e2daaf669bebc72e87d:
dist/spec: add python-requests requirement were applicable.
=> pkglistgen: post deployment spec requirement and bug fixes

obs_clone.py
- ecda2f03031e7bfc29f7d628c646f1940878c774:
obs_clone: workaround openSUSE:Factory meta revision 429 self reference.
- 494702ba11dd47a60c8b926b3127643c6d2ac627:
obs_clone: set the exit code to 1 when HTTPError encountered.
Fixes #1335. Need to verify travis-ci is happy.
I have some further improvements I made to handling links which enable cloning the rings, but even with that the super loop self reference is a bit too much without a solver so this seems like best solution since it is temporary. Simply revert ecda2f0 once reverted in Factory.
Included changed to set exit code to 1 on exception so that travis-ci will stop on the failure instead of running tests.
=>  obs_clone: workaround openSUSE:Factory meta revision 429 self reference.

dist/package/openSUSE-release-tools.spec
After discussing #1322 it would seem best to fix our own case.
=> dist/spec: license: s/and/AND/ to follow standard.

metrics.py, systemd/osrt-metrics@.service, systemd/osrt-metrics@.timer
Until OBS exposes the sort field via API as referenced in #1244 incremental ingest is not possible. As such fallback to full ingest once weekly instead of completely disabled at the movement.
Presumably the data amount will not be an issue once weekly.
=> systemd/metrics: change service to be non-incremental and weekly.

osclib/request_splitter.py
@lnussel I added this variable override a while back, but seems we forgot about it since you asked in IRC the other day. Given it sounds like you would like no special packages for Leap I updated code to handle empty string variable override.
I'll go ahead and update project config for Leap 15.0 to set the special list to empty, but feel free to update.
=> osclib/request_splitter: allow special packages to be empty.

obs_clone.py
- bae6c8db6b71b27704d1ecb23b9405369a83ff8d:
obs_clone: reword comment in project_workaround() since not temporary.
- 4a131573c66bd53184c86d441f6d9ff4e73aacd3:
obs_clone: clone rings.
- 7fa5156474c6e1063283a7812c3018db2eb9c1ac:
obs_clone: handle project links.
Fixes #1339.
=>  obs_clone: handle project links, clone rings, reword workaround comment.

osclib/conf.py, pkglistgen.py
Replace config option pkglistgen-delete-kiwis by
pkglistgen-delete-kiwis-$scope. The main project needs all kiwis while
in Rings and Stagings we don't want the ftp tree for example.
=> pkglistgen: delete kiwis by scope

fcc_submitter.py
There is a previous commit causes fcc_submitter does not store linkinfo package information to data list, this causes fcc_submitter fails to find the main-package information.
Regression from https://github.com/openSUSE/osc-plugin-factory/commit/62f50d267fd1f6e5c2a78ac88dda9bd305900cdf#diff-f7f109926d6b387e4ab4b2488a47bd13
=> fcc_submitter: fix a regression from previous commit

ReviewBot.py, check_source.py, fcc_submitter.py, leaper.py, osclib/core.py, osclib/request_splitter.py, osclib/stagingapi.py, repo_checker.py, update_crawler.py
- 5e73e9498fcd9b47e8ce3623b0ebdf75c0ceb2db:
osclib/request_splitter: replace devel_project_get() with core.devel_project_fallback().
- 62d432c7c8b1c9e97d2e07ddfa8ed5bda3175582:
osclib/stagingapi: replace get_devel_project() with core.devel_project_get().
This implementation does not handle the 404 correctly like ReviewBot did
originally.
- 5e7220ddd0fa5c328b63a4d3c22c143339f1a8ce:
update_crawler: replace get_devel_project() with osclib.core.devel_project_get().
- 16cef90dc3f8f084de2efd32d3e537899b0fd8d6:
fcc_submitter: replace get_devel_project() with osclib.core.devel_project_get().
- 8c4891bd95404fc58bcd2ec7adfcfad0589d797a:
ReviewBot: replace get_devel_project() with osclib.core.devel_project_get().
- ce4cc656907450a5a8cde2e5cc4bffce1ef49e9e:
osclib/core: devel_project_fallback(): do …
=> Replace all get_devel_project() implementations with common one in osclib.core.

check_source.py
Builds atop #1351 and should wait until rebased post merge.
Only review/discuss:
- 63b79b25fed3c1cd4a8f9a6b2bee93ff8a22a4fb:
check_source: add_role: utilize devel project fallback.
Otherwise, for Leap the message will always print None/None.
=> check_source: add_role: utilize devel project fallback.

dist/ci/obs-deploy
- d05b591a0145aeb4db466ab2a37a57649e529820:
dist/ci/obs-deploy: only bother making request if diff.
- 88add9aefa9b48be8c8ae11d88c46057572a1abd:
dist/ci/obs-deploy: limit `request list` by user to avoid source requests.
Otherwise, requests from Factory to Leap will prevent request to Factory
from being generated.
Fixes #1246.
=> dist/ci/obs-deploy: only bother making request if diff and avoid source requests

dist/ci/obs-deploy
- 6326c60990bfe9fd579af03399fc3730765eeac2:
dist/ci/obs-deploy: only commit if new source revision.
- 02f11fa66e5e08d41f8eb7574cd13f8ac8ba4518:
dist/ci/obs-deploy: require greater than six lines changed to create request.
=> dist/ci/obs-deploy: only commit/submit request if new source revision (for cron).

repo_checker.py
This can occur when a package is removed from Factory, but still present in Leap like `libtxc_dxtn` currently.
=> repo_checker: skip packages for which not devel project exits.

dist/ci/docker-compose-obs
To aid in future debugging of `osc` failures as seen in #1361.
=> dist/ci/docker-compose-obs: print osc output on timeout for debugging.

dist/ci/obs-deploy
Even after trying to workaround requests sourced from target package
(ex. Factory -> Leap) by using -U the query still behaves incorrectly
since both -U and -M do not return request created by user as documentation
suggests, but rather those who are last user in state. This works as
expected directly after a request is created, but not once another user
modifies it.
At this point just avoid the mess entirely and issue query for exactly
what is desired which avoids user altogether.
=> dist/ci/obs-deploy: replace `osc request list` with `osc api` call.

osc-staging.py, osclib/accept_command.py
I went for the simplest implementation, just `todo` key. If this ends up being heavily used in such a way that it makes sense to support `todo*` or similar then adding something like `--add` support to `config` command where that adds incremental `todo` keys and reads them back with `todo*` then it can be added to accept as well.
For now this seems sufficient. I went ahead and ran the following for `Leap:15.0`.
```
osc staging config C todo something
```
So this can be tested in production when C is accepted. Otherwise I tested the added code manually outside of `accept` command. The result should be the follow after the normal output.
```
todo = something
```
Fixes #1324.
=> osclib/accept: print todo from staging config after completion.

devel-project.py, osclib/core.py, osclib/request_splitter.py, status.py
- 704fc50dca208dd4c2e0f22d295137518aff1abe:
status: provide initial implementation for checking bot status.
- b84beb6958f0b3386caba55ac9d1b3842fec54e5:
osclib/request_splitter: utilize osclib.core.request_age().
- b8c91eaed7653d2d7de0495a2e552dbe31d892ac:
devel-project: utilize osclib.core.request_age().
- f11daf3d6296ba750dddbd5f9e1a7a08d40df8d8:
osclib/core: provide request_age().
Basically implementation for our use and https://progress.opensuse.org/issues/25750. Would benefit a lot from openSUSE/open-build-service#4108. Would likely also make sense to provide two threshold one indicating possible failure or high load and the other indicating service down.
Depending on how this could be deployed (if that happens) I can easily provide a subpackage for it.
Example output:
``` …
```
=>  status: provide initial implementation for checking bot status and request_age() refactor.

create_test_Factory_dvd-1.testcase
vim now requires vim-data instead of recommends.
was in packagelists vm already.
=> create_test_dvds: do not lock vim-data

status.py
This was the intention for factory-auto.
=> status: fallback to request_age() even if no comment.

osclib/adi_command.py, osclib/request_splitter.py, osclib/stagingapi.py
Refactored version of #1378 that allows for two level grouping to maintain splitting by devel project first. End result is groups like the following, where you can have two groups for same devel project.
- Archiving
- devel:libraries:c_c++
- devel:tools:building
- **network:telephony**
- **network:telephony__nonfree**
- openSUSE:Factory
- systemsmanagement:wbem
=> adi: place :NonFree requests in separate adi with :NonFree path.

pkglistgen.py
Don't remove packages from modules *below* overlap or they are gone for good
=> pkglistegen: Fix overlap generation

data/incidents.json, data/repos.json
We are still actually running off an old version off f5c4750fdcc2f0f0123edbf9bbaf589adfa44f30 as advised by @coolo
=> remove Leap 42.2 from tests

osclib/conf.py
Taken from [remote config](https://build.opensuse.org/package/view_file/openSUSE:Leap:15.0:Staging/dashboard/config) these are settings used for `42.3` and now `15.0` and seem to work well so rather than have to copy to future remote configs might as well make them defaults.
Leaving `splitter-whitelist` out since future Leap may or may not have non-whitelisted and they can change like _Factory_.
=>  osclib/conf: leap: incorporate proven settings for future releases.

osclib/conf.py, osclib/core.py, osclib/stagingapi.py, osclib/util.py, pkglistgen.py, tests/obs.py, tests/util_tests.py
- dc3b9e15e126e40c71757f544c504dec95ed7051:
osclib/conf: include Leap for Factory during pkglistgen.
- c56c23f14808880e60bca633acba1428e20fbbdd:
pkglistgen: include some hints about the difference between solv files.
- b58cb89641a7a23ebae3a5150c2c79efd1333014:
**pkglistgen: integrate drop list creation into update_and_solve.**
In order to generate a complete drop list the nonfree repository must also
be cached for both current and published builds. The solv files are then
merged and used to generate drop list.
- 5e35baac618bac8b106d0afc567360d51a976950:
pkglistgen: do_dump_solv(): handle old-style product repo format.
This allows for generating solv cache for Leap versions prior to 15.0
which avoids the need to have them checked into git like previous
package-lists repository.
- …
=> pkglistgen: integrate drop list creation into update_and_solve and project family methods

osclib/conf.py, osclib/util.py, pkglistgen.py, tests/util_tests.py
First fix towards #1392. I will likely update, but just published to start collecting any fixes needed.
=> pkglistgen: do_update_and_solve(): check for existence of :DVD instead of rings and pkglistgen-product-family-last config option.

pkglistgen.py
UNWANTED is a bit heavy weapon to filter unsorted.yml, so leave
its role to packages we sure don't want (e.g. -mini and -bootstrap
packages). Packages that are there but would end in unsorted otherwise,
filter by means of package regular expressions in unneeded.yml
The format of that file is yml with a list of groups of regular
expressions.
```
global:
- .*-32bit
texlive:
- texlive.*
=> Support unneeded.yml as list of regular expressions

osclib/conf.py
See [boo#1080987](https://bugzilla.novell.com/show_bug.cgi?id=1080987).
=> osclib/conf: leap: repo_checker-arch-whitelist to x86_64.

metrics.py
- 76ac5d6b2e29d526d0a16380bfad127c338a4437:                                                                                                
metrics: ingest_release_schedule(): disable for Tumbleweed until #1250.
- f0fee5ec8d69bb2ad92cf2ae514bc1dfe85808f6:
metrics: update Leap config key to match osclib/conf post #1386.
Gained access to heroes VPN after migration so updated to latest and enabled weekly ingest.
=> metrics: ingest_release_schedule(): disable for Tumbleweed and update Leap config key to match osclib/conf

osclib/conf.py, pkglistgen.py
- 21961daf8a96f8411caa437201584e67f71bb75f:
**pkglistgen: solv_cache_update(): support update repo and 4 way merge.**
- 460ab740d99b9a55f296a2b19c9af1be5a346312:
pkglistgen: do_dump_solv(): support update repos.
Always pull down update repo and only overwrite if changed. Could rework
more extensively to name based on hash of repomd.xml or somesuch, but would
likely also want to remove old versions.
- 84b142c00c321cb663c2cbba1809f46857fb867a:
pkglistgen: solv_merge(): allow array of solv files to merge.
- df4e23c22df2ef6906a7965f707e917ba373f9ba:
pkglistgen: solv_merge(): skip when inputs are older than merged.
- a11192affd5ec34dacf082cf2dfda06def962c41:
osclib/conf: leap: set download-baseurl-update.
Fixes #1396.
=> pkglistgen: solv_cache_update(): support update repo and 4 way merge (and merge skipping)

osclib/freeze_command.py, osclib/stagingapi.py
This reverts commit 239c6314c7a8b0192c85181e7f64ab274e74cc31.
The whole purpose of freeze is not to have target changes affect the stagings. We didn't notice yet in Factory as we don't have the product builder there - but in SLE this is an ongoing problem
=> Revert "staging: add exceptions for new 000* product files"

legal-auto.py
The `Authorization` value needs to be added to the `bot` object, not `self`.
=> fix a typo that currently breaks token authentication

ReviewBot.py
For consistency this would still make sense to post as a "report", but given the lack of such a facility in OBS disable comment to reduce noise.
```
./leaper.py -A ibs --dry --verbose id 156275
[I] checking 156275
[E] unhandled request type set_bugowner
[I] 156275 needs review by [leap-reviewers](/group/show/leap-reviewers)
[I] POST https://api.suse.de/request/156275?by_group=leap-reviewers&cmd=addreview
[I] can't change state, 156275 does not have the reviewer
[I] 156275 accepted: ok: unhandled request type set_bugowner
```
Fixes #1422.
=> ReviewBot: do not bother commenting for unhandled request type.

ReviewBot.py, legal-auto.py, osclib/comments.py, osclib/conf.py, osclib/core.py, repo_checker.py, tests/checktags_tests.py, tests/factory_source_tests.py, tests/maintenance_tests.py
- 68b93e1dbd4fbb395bb1ea4cf6aec35a45f4babb:
repo_checker: provide comment command to skip-cycle for group.
For example (on staging project):
@repo-checker skip-cycle
- 4f4e6da7efc48fc43dd63138081b61d9df01c960:
repo_checker: utilize ReviewBot.comment_api instead of new instance.
- e775d440494d39291b4ded228abb6ed3555463d3:
ReviewBot: provide comment command override.
For example:
@leaper override accept
@repo-checker override decline
- 3674191a41f4d6f82c530eee14ac85ce86150e3a:
osclib/core: maintainers_get(): utilize new group_members() function.
- e2efbf55a90b98755f9e889bf501069ca5405ad1:
osclib/core: provide group_members() function.
- eb19b827aa1b82dcf1880c98d761c5caed6ee2c7:
osclib/comments: provide command_find() for comment commands.
Fixes #1400.
Fixes #1365.
Should partial work …
=> Define comment commands and provide for ReviewBot review overrides and repo-checker skip-cycle.

leaper.py, osclib/conf.py
- 16f49c7518f9d1b39145b8091671cea776c90487:
leaper: do not decline SLE requests, but rather ask managers for input.
- 5e2834e4bda1d9b53365dd6f0ec37b3e3f6056cf:
osclib/conf: configure SLE-15 leaper-override-group.
- 8332692dada7a5ef89ad1c10463959b18ba4c947:
leaper: move review groups to osclib.conf.
Output when `origin_same` forced to `False`.
```
./leaper.py -A ibs --dry --verbose id 156436
[I] checking 156436
[I] home:mcgrof:branches:SUSE:SLE-15:GA/xfsprogs@2 -> SUSE:SLE-15:GA/xfsprogs
[I] expected origin is 'FORK' (unchanged)
[I] obsrq#583263 to openSUSE:Factory has different sources
[I] different sources in [openSUSE.org:openSUSE:Factory/xfsprogs](/package/rdiff/home:mcgrof:branches:SUSE:SLE-15:GA/xfsprogs?opackage=xfsprogs&oproject=openSUSE.org:openSUSE:Factory&rev=2)
[I] different …
```
=> leaper: do not decline SLE requests, but rather ask managers for input.

osclib/conf.py
Error only happens when local config to parse. :(
Fixes #1428.
=> osclib/conf: change priority to be string to work with ConfigParser.

osclib/accept_command.py, osclib/stagingapi.py
- e450a1519ee9083ff2580901c44241c1afab7ff8:
osclib/stagingapi: rename main_repo to cmain_repo.
The previous name is inconsistent and did not work with general lazy laod.
- 4bd9e9a2fbf5d0407e7b2aef1b2ff2cc10be1e67:
osclib/stagingapi: rename delreq_review to cdelreq_review.
The previous name is inconsistent and did not work with general lazy laod.
- d790a2ce6928b723c1152fbbe73c4300a44849c3:
osclib/stagingapi: rename cstaging_nocleanup to cnocleanup_packages.
The previous name is inconsistent and did not work with general lazy laod.
- e3168d6c3426aa10ebde1e9780acd8a50e6b3e9a:
osclib/staging-api: lazy-load all config values to allow for placement in remote config.
Feel free to test this out as we have many use-cases and few tests. I made sure the values I replaced worked for `Factory` which …
=> osclib/staging-api: lazy-load all config values to allow for placement in remote config.

dist/package/openSUSE-release-tools.spec, metrics.py, metrics/grafana/release.json, metrics_release.py, systemd/osrt-metrics-release@.service, systemd/osrt-metrics-release@.timer
Per my plans and factory mailing list requests this will ingest metrics data about TW snapshots and review data.
=> metrics: provide release metrics ingestion and dashboard.

create_test_Factory_dvd-2.testcase
kdelibs4-branding-openSUSE has been dropped, since there is nothing useful
left in it, and kdebase4 is slowly dying.
=> create_test_Factory: No longer block kdelibs4-branding-upstream

pkglistgen.py
That check is aiming to check request rather than package, for release package we indeed had multispecs and multibuild file together, just do not run local service when committing to release package.
fixes https://github.com/openSUSE/osc-plugin-factory/issues/1440
=> pkglistgen: Do not run local service check when committing to release package

issue-diff.py, osclib/git.py
- da7e0b43d68404a83a31eae78f25cc00b7bcf016:
issue-diff: rename --config-dir as --cache-dir to be more accurate.
- 17b6f0b7535d43692c0e9955f17cd5c429ef8bac:
issue-diff: replace git sync functionality with osclib.git.
- 90d538606d7503d399c71eb5f146a95062425ba1:
osclib/git: provide git utilities: clone() and sync().
Derived from issue-diff.py which was abstracted in
boombatower/tumbleweed-review.
Should be useful for #1438.
=> osclib/git: provide git utilities: clone() and sync() and utilize in issue-diff.py.

systemd/osrt-totest-manager@.service
Without an install section, systemctl enable osrt-totest-manager@openSUSE:Factory has no effect, which in turn results in the service not running upon reboot (unless manually being symlinked, whichis definitively not the way to go)
=> services: Add Install section to totest-manager service

pkglistgen.py
- f9b7832e8ba1f8f09e69ef52ae4cfde6ab3520f9:
pkglistgen: do_dump_solv(): include hash in update solv to avoid download.
- 28b467f4e8d9a8c40177b4d477729cabce850ba4:
pkglistgen: do_dump_solv(): utilize os.path.join().
Should be rebased on #1439.
=> pkglistgen: do_dump_solv(): include hash in update solv to avoid download.

dist/ci/Dockerfile
opensuse:tumbleweed will be removed and we want dogfooding anyway.
Fixes #1460. (added by jberry-suse)
=> Use opensuse/tumbleweed in the Dockerfile

check_source.py
This one was requested by @coolo. All checks should be skipped for 00* packages.
=> check_source: skip all checks for 00* packages

check_source.py, osclib/conf.py
- 42139de4d68490f8128cfae6451a21d8e9f2db5d:
check_source: delete: place maintainer review check behind ignore_devel.
SLE does not utilize devel projects and so adding such reviewer does not
make sense. Additionally, for Leap the right review will depend on origin
which leaper handles.
- e964cb58a4c551085eee5663d2741c8ce0301955:                                                                                                
osclib/conf: SLE-15: set check-source-in-air-rename-allow to True.                                                                     
- a7e36b03f7afc3112ff57dbd35f50a4240f1d40a:                                                                                                
check_source: provide in-air-rename-allow config setting.
Fixes #1464.
=> check_source: SLE: allow in-air-rename and place maintainer review check behind ignore_devel.

check_source_in_factory.py
This would be better done by using config, but that would require a larger
refactor since the underlying ReviewBot is not entirely setup when called
by leaper.
Fixes #1450 short of refactoring all these bits.
=> check_source_in_factory: allow repo-checker reviews.

totest-manager.py
Tested with `--dry --verbose release openSUSE:Leap:15.0:Images`:
```
2018-03-26 11:10:11,528 - totest-manager:451 INFO Updating snapshot None
2018-03-26 11:10:11,528 - totest-manager:434 INFO release openSUSE:Leap:15.0:Images/livecd-leap-gnome (None)
2018-03-26 11:10:11,529 - totest-manager:434 INFO release openSUSE:Leap:15.0:Images/livecd-leap-kde (None)
2018-03-26 11:10:11,529 - totest-manager:434 INFO release openSUSE:Leap:15.0:Images/livecd-leap-x11 (None)
2018-03-26 11:10:11,529 - totest-manager:434 INFO release openSUSE:Leap:15.0:Images/opensuse-leap-image (None)
```
=> totest_manager: Also release openSUSE:Leap:15.0:Images/opensuse-leap-image

totest-manager.py
Since openSUSE:Factory moved to the new prod builder, we need this now for TTM
I've been running it from the osc-plugin-factory for the last few days to get it sorted (osrt-totest-manager was disabled)
as TW was the last product on the old builder, I went the simple route of ```sed /_product/000product/g``` to get going quickly with TW snapshots again.
We can start looking into some cleanups/simplifications after that
=> totest-manager: Tumbleweed moved to the new product builder

osclib/cleanup_rings.py, osclib/core.py, osclib/stagingapi.py, repo_checker.py
I took a stab at this old P1 issue
Tested with the current gegl-unstable delete request:
```
$ ./repo_checker.py --dry  --skip-cycle --debug --force id 590049
[D] 590049: openSUSE:Factory:Staging:G ready
[D] requests: 0 skipped, 1 queued
[I] checking 590049
[W] gegl-unstable is still a build requirement of:
- bundle-lang-gnome
- gimp
- gnome-photos
- openttd-opengfx
[W] gegl-unstable provides runtime dependencies to:
- gimp
- gnome-photos
[D] removing previous comment on 590049
[D] adding comment to 590049: 
gegl-unstable is still a build requirement of:
- bundle-lang-gnome
- gimp
- gnome-photos
- openttd-opengfx
gegl-unstable provides runtime dependencies to:
- gimp
- gnome-photos
[I] 590049 ignored
```
In many cases, build deps and runtime deps will have some overlap, but as can already …
=> repo-checker: check delete requests for runtime deps

osclib/conf.py
Fix AttributeError: 'NoneType' object has no attribute 'lower' error
=> conf: make sure variable is not None before do lower()

ToolBase.py, biarchtool.py, update_crawler.py
All openSUSE distros in developments switched to the new product builder, meaning
they no longer use _product as the package container, but operate on the standardized
name 000product.
Addresses https://progress.opensuse.org/issues/20890
=> Change remaining usage of _product to 000product

devel-project.py, issue-diff.py, osclib/conf.py, osclib/core.py, osclib/util.py
- 961d3456dee4d1ad00749bd0ea6e98ff49239d71:
issue-diff: utilize entity_mail() as adapted into osclib.core.
- 156e81156577256a41f1e2157bef98688929c1b2:
devel-project: provide notify sub-command.
- db3fdf6d22b2237663bec0ff883bc391c5f15942:
osclib/util: provide mail_send(), modified from announcer.py.
Depend on config for relay, from, and followup-to.
- b472a899292a83d975f3db795c6e69529aab5116:
osclib/core: provide entity_email(), modified from issue-diff.py.
Fixes [poo#29277](https://progress.opensuse.org/issues/29277).
=> devel-project: provide notify sub-command.

ReviewBot.py
- f196526e733ee81c49692805e19a884029ebfad3:
ReviewBot: disable comment handler for default action handler.
Otherwise, if a bot overrides __default() and still calls super method and
then comment_write(), as leaper does, a comment will still be generated. If
a bot wants a comment even when "unhandled" it is likely deviating
enough that it should not call the super method.
With change:
```
$ ./leaper.py --debug --dry id 597102
[I] checking 597102
[E] unhandled request type set_bugowner
[E] unhandled request type set_bugowner
[D] has_correct_maintainer: None
[D] review result: True
[D] skipping empty comment for 597102
[I] 597102 needs review by [leap-reviewers](/group/show/leap-reviewers)
[D] skipped adding duplicate review for leap-reviewers
[I] 597102 accepted: ok: unhandled request type …
```
=> ReviewBot: disable comment handler for default action handler.

check_tags_in_requests.py, legal-auto.py
- f751f4768a84509f5c4b3efc3342ffd7564660f1:
check_tags_in_requests: replace check_action__default() with built-in.
- 202d1397437a9a0ba9f7df79d7ffbdb1ac21575b:
legal-auto: replace check_action__default() with built-in.
Noticed while working on #1490.
=> ReviewBot: replace default handler for legal-auto and check_tags_in_requests

devel-project.py, osclib/core.py
- 9c214723c18108d3ec7b99fd14bb00a739c2e059:
**devel-project: notify: utilize osclib.core.package_list_without_links().**
Otherwise, all packages are returned which include psuedo-packages like
kernel-default which is really a multi-build of kernel-source. When
invoking devel_project_fallback() the return ends up being
openSUSE:Factory/kernel-source which is less than desireable.
- c6289c8516f52e7add838ae0f922199100d233ed:
osclib/core: provide package_list_without_links().
- 1dc269feaf8ffd5730f15ae45c89202dc939bf4c:
devel-project: remove unused imports.
There should really be a distinction/API param for this on OBS side. Dropped package count from ~500 which should remove `kernel-default` from being considered a package apart from `kernel-source`. The special devel project for Leap is …
=> devel-project: notify: utilize osclib.core.package_list_without_links().

totest-manager.py
For Leap 15.0 Ports we need to be able to support two image
repos, one for arm and one for ppc because they get published
to two different locations. for now as we have only images_arm
add support for that while ppc is still making its way through
an initial build.
=> Handle Leap:15.0:Ports images_arm repository

metrics/annotation/openSUSE:Leap:15.0.yaml
To be confirmed by @lnussel, but we can always change as this is only used for annotating graphs.
=> metrics/annotation: add openSUSE:Leap:15.0 schedule.

metrics.py, metrics/grafana/dashboard.json, osclib/stagingapi.py, systemd/osrt-metrics@.service
- 0ec3569d7068bae5dff9417183499ce10c228768:
metrics/grafana: add dashboard.json.
- a45c3358df2e0b0e46c63677a394b5cdd69b35aa:
metrics: ingest relevant dashboard files and extract metrics.
- 4ee96ae3d20b5174d33c96e97ecaced65ff19ebf:
metrics: provide dashboard revision walking function and cache patterns.
- 079eda3ba69b883262635be945bf44bf0641a4dd:
metrics: instead of wiping cache place ephemeral patterns behind flag.
This allows for non-ephemeral queries to be cached indeinitely in the
future (like source queries that include the revision). For development
one may use --heavy-cache to be able to quickly iterate.
- 48913abc47e88f0d8416f7f5d1f6bd4665a2c241:
osclib/stagingapi: dashboard_content_load(): expose revision parameter.
This is also step one towards #1168 which is useful to cleanup …
=> metrics: walk dashboard revisions and extract metrics from relevant files

osclib/core.py, unmaintained.py
- d65e037d18380b520cd97de18b43378e93fafca9:
unmaintained: utilize package_binary_list(exclude_src_debug).
- 3c560d0c68ff1f2cffbb2abd53fab52dc09e415c:
osclib/core: package_binary_list(): provide exclude_src_debug option.
Per feedback in [poo#28815](https://progress.opensuse.org/issues/28815).
=> unmaintained: utilize package_binary_list(exclude_src_debug).

ReviewBot.py, data/incidents.json, data/repos.json, oqamaint/openqabot.py
Most of it affects only openSUSE, but I changed the logic in general when a release request is approved. It was a bit vague before as the check_one_request was called in various places. Now the logic is simpler:
- schedule all incident tests
- check latest updates repo tests
- review all release requests to verify:
- the incident tests passed
- the latest update repo tests pass
- the latest update repo tests involve the incident
- schedule new update repo tests if necessary
=> Fix several bugs with the bot scheduling and reviewing

osclib/core.py, repo_checker.py
- 35989be1da0688d7be3a28aea6f415908029ace9:
**repo_checker: provide whitelist_clean subcommand.**
Removes whitelist entries that are no longer mentioned in repo_checker
output and condenses entries common to all.
- c4f799d7ddcd04d23d47d1856440cec512ac8668:
osclib/core: correct BINARY_REGEX by making it greedy.
Should not effect RPM_REGEX usage since it appends suffix.
Automates the last portion of [poo#35425](https://progress.opensuse.org/issues/35425).
I ran locally for _Leap 15.0_:
```
$ ./repo_checker.py whitelist_clean openSUSE:Leap:15.0
```
```diff
--- config.orig
+++ config.new
@@ -15,9 +15,9 @@
repo_checker-arch-whitelist = x86_64
-repo_checker-binary-whitelist = atkmm1_6-doc autoyast2 build-mkbaselibs build-mkbaselibs-sle devscripts duplicity dvd+rw-tools gedit-plugin-zeitgeist …
```
=> repo_checker: provide whitelist_clean subcommand.

metrics.py, metrics/grafana/dashboard.json
- 1268165f53cb1f492ab1edd509e63ac7338dee71:
metrics: dashboard: drop dashboard measurement in favor of dashboard_revision.
- 6e74ae62fd92201d317389386f710a5074f25490:
metrics: dashboard: include revisions graph.
=> metrics: dashboard: include revisions graph.

metrics.py
- 40dd33f3e053c56688197155c56f473b85f6006d:
metrics: ingest_dashboard_config: rename seen to previous.
More accurately describes the new purpose.
- da3400b62ede6ecb674d65b461601d618c376a83:
**metrics: ingest_dashboard_config: initialize seen with last record keys.**
- 060ac43784df403ab0b81db5aee0cd0d132460b1:
metrics: ingest_dashboard_config: only fill missing values once.
Properly fills removed key with 0 if removed in between runs.
=> metrics: ingest_dashboard_config: initialize seen with last record keys.

osclib/freeze_command.py
Sometimes we has distributed a staging project for specific reason and given people the maintainership, after froze staging project the users data will be erased, freeze command should copy the users data therefore we do not need to add people back again. Staging Master have to remember reset users data when the goal of staging project has achieved.
=> freeze_command: rebase staging project do not erase users data

osclib/check_duplicate_binaries_command.py
Presumably an oversight when lnussel added.
@lnussel: Would it make more sense to just ignore all cases where `parch != arch`?
This changes drop the following from output:
```
glibc:
- glibc
- glibc:i686
glibc-debuginfo:
- glibc
- glibc:i686
glibc-debugsource:
- glibc
- glibc:i686
glibc-devel:
- glibc
- glibc:i686
glibc-devel-debuginfo:
- glibc
- glibc:i686
glibc-devel-static:
- glibc
- glibc:i686
glibc-locale:
- glibc
- glibc:i686
glibc-locale-debuginfo:
- glibc
- glibc:i686
glibc-profile:
- glibc
- glibc:i686
```
=> osclib/check_duplicate_binaries: ignore s/glibc.i686/glibc:i686/.

repo_checker.py, systemd/osrt-repo-checker-project_only@.timer
- b5320317d7e0c2a5dfba0e5e87707dc807c08391:
systemd/osrt-repo-checker-project_only@.timer: increase frequency to hourly.
Now that repo_checker will skip identical builds this will increase the
chances that repo_checker project_only hits the project when it is not
building and will decrease the wait time for updates.
- 4f26b0881af2991b93662a1c29406e731d79fe2a:
repo_checker: project_only: store build hash and skip when unchanged.
_Leap 15.0_ is running hourly on tortuga and SLE-15 was the same before it was migrated. The main reason for the daily run was prior to the published check to avoid changing all the time during builds, but with the check that is not longer an issue. To avoid lots of extra process and API calls when using `--post-comments` the same build hash style check is added. …
=> repo_checker: project_only: store build hash and skip when unchanged and increase timer frequency to hourly

ReviewBot.py, osclib/memoize.py
- 7b2f07c5f5e713f632cfa7296479cbb98facbfa7:
ReviewBot: runner: reload checker and reset memoize session caches.
Otherwise, memoize(session=True) caches are kept until the process is
stopped which is obviously not how they were intended to be used. This
can cause incorrect behavior and continued memory growth.
- 2a43297880d99d0fc1310c50d0469a4362da18c8:
osclib/memoize: provide memoize_session_reset().
Allows all session caches to be reset.
Fixes #1511. At least the glaring problems like never reloading build status until the process runs out of memory and crashes. I'd need to do more extensive testing to verify memory no longer climbs. I am doing some test runs locally, but may not be thorough enough.
=> ReviewBot: runner: reload checker and reset memoize session caches.

osclib/conf.py
- 628519d370fe597ded44d6b9958f8f9eb636e04f:
osclib/conf: update nocleanup-packages post migration to new pkglistgen.
- e7c611e9edba8e01c1ea2f14f073d119af3f20c9:
osclib/conf: change pkglistgen-include-suggested to False.
To be read for _Leap:15.1_.
=> osclib/conf: update remaining non-merged Leap:15.0 settings.

dist/package/openSUSE-release-tools.spec
Related to openSUSE/open-build-service#4373 as disabling s390x leaves old binaries in repo-md while publishing new ones :(((((((.
=> dist/spec: exclusively build on x86_64 to avoid needless builds and OBS bug.

dist/package/openSUSE-release-tools.spec
- 391da222b07e74c9f99e9792e6823aad341ed409:
dist/spec: bump copyright year.
- 85760ef43f7a3a568ba2fb305a66a5d5bb3b3b0d:
dist/spec: sort requirements.
- 8744773af8d37e987ed7508642e38ea0bec70717:
dist/spec: update to new license standard.
- d5868597b6a4ae312230252677460e019ac5f08f:
dist/spec: move ExclusiveArch up to apply to all packages instead of devel.
Appease the osc services to reduce diff seen in CI and make everything happy. Also fix ExclusiveArch usage as verified in home project.
Fixes #1532.
=> dist/spec: housekeeping

openqa-comments.py
- eca6670be1ce4aa262beb3de2e051cca233f1a63:
openqa-comments: drop openSUSE: prefix to allow for generic usage.
- 284584cc81530df7c59981ac42980a79e0932704:
openqa-comments: meant to be executable thus should include a shebang.
=> openqa-comments: drop openSUSE: prefix to allow for generic usage and shebang.

config/manager_42/openSUSE:Leap:15.0.yml
In order to allow for SLE packages to be taken from Factory while waiting on acceptance to SLE, but still mark as from SLE and avoid delete request to SLE-workarounds.
The output when simulated to not be in SLE-15, but marked previous as from there while being in Factory is:
```
2018-05-11 15:53:54,274 - manager_42:361 - INFO - netcdf is from openSUSE:Leap:15.0:SLE-workarounds but should come from SUSE:SLE-15:GA
```
whereas before it would have switched the origin to Factory and the filed a delete request against SLE-workarounds since not utilized.
I believe this make sense rather than a code change since it really is a priority over Factory.
=> config/manager_42/leap:15.0: increase priority of SLE-workarounds.

osclib/conf.py, pkglistgen.py
this architecture is also part of port, not only aarch64, and
we need architecture specific expansions, so extend default list
of architectures accordingly.
=> Add ppc64le to pkglist gen for Leap 15.0 Ports

repo_checker.py
Otherwise, if len(binaries_common) causes crash when no arch specific entries. Of which Leap:15.0 is the only one currently.
=> repo_checker: whitelist_clean: handle binaries_common being None.

osclib/stagingapi.py
Check the devel project from the first package in frozenlinks won't work if the package has been deleted, check the first package in metadata instead.
Tested it on Factory adi:27
=> Freeze adi: do not check the first package in frozenlinks but metadata

metrics/annotation/openSUSE:Leap:15.0.yaml
Per https://lists.opensuse.org/opensuse-factory/2018-05/msg00223.html.
=> metrics/annotation/leap:15.0: update final release date.

metrics.py
After change from dropping entire database to individual measurements this was overlooked and instead new points are simply written each time which results in duplicates.
=> metrics: drop release schedule before writing.

oqamaint/openqabot.py
module names may contain # - especially if the module is loaded twice
and openQA appends #1 and #2
=> openqabot: Quote the module name

factory-package-news/announcer.py
Rather then replying to the generated email we would like people to create new issues on bugzilla.opensuse.org
=> Update announcer.py to ask people to report bugs

metrics/grafana/release.json
With scores reaching near 100 :) the auto axis is leaving margin.
=> metrics/grafana/release: score yaxis max 100.

oqamaint/openqabot.py
By appending the IDs of incidents considered, e.g.
'REPOHASH': '9b9ff324e95d25dc6bb216cb45bdd855:8198,8200,8201,8203',
=> oqamaint: Make debuging of incident list in repohash easier

totest-manager.py
http://download.opensuse.org/ports/armv7hl/distribution/leap/15.0/repo/oss/ is currently empty, this should fix it.
Untested.
=> Also release 000product:openSUSE-ftp-ftp-armv7hl for Leap 15.0 ports

totest-manager.py
Recently we decided to incorporate armv6 and armv7 publishing into
ToTest as well.
=> Handle armv6/armv7 with totest manager as well

dist/ci/Dockerfile
Pending a proper resolution to openSUSE/osc#429.
This has been failing for a few days...
```
File "/usr/bin/osc", line 10, in <module>
from osc import commandline, babysitter
File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 9, in <module>
from . import conf
File "/usr/lib/python2.7/site-packages/osc/conf.py", line 44, in <module>
import ssl
ImportError: No module named ssl
```
=> dist/ci/Dockerfile: add python2-pyOpenSSL as dependency.

totest-manager.py
Derive project-base from project argument.
This removes some redundancy from cli.
=> TTM: Remove project-base option

totest-manager.py
Add option `--release` to explicitly enable release for SLE.
This finally allows us to reuse the systemd units for both openSUSE and SLE.
=> Make norelease the default for SLE

systemd/osrt-metrics-access.timer
Since:
> weekly → Mon *-*-* 00:00:00
per https://www.freedesktop.org/software/systemd/man/systemd.time.html and verified logs for length. Hasn't happened yet, but would rather avoid.
=> systemd/metrics-access.timer: skip Monday to avoid conflict with metrics.timer.

totest-manager.py
for openqa_group def in ToTest150Ports class
Required to avoid bad makeurl generated string.
Add pending question about all entries of main_products.
Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>
=> ttm: Use openSUSE Leap 15.0 AArch64 not Ports

metrics.py, osclib/stagingapi.py
As explained in my reviews #1573 original broke metrics parsing going forward, but was upgraded to create corrupt data. I would suggest the author use the toilet at home as this prevents it from being deployed to metrics.o.o.
Additionally, as noted and noted before, the update contained lots of style changes for code that was otherwise untouched which is very annoying at best. The worse two I reverted.
Since reviews are generally ignored there is no sense to wait.
=> Revert crap from 'Use attribute to store staging config' that create corrupt data

totest-manager.py
In order to release the live images for Factory:ARM we need
to check if they finished building. Currently JeOS is multibuild
for armv7l and aarch64 but the main package is just building for armv7l,
so thats what we check for now. Without this change it was checking
for the default architectures (i586, x86_64) which did never pass.
=> Fix JeOS snapshotable detection for Factory:ARM

osclib/stagingapi.py
OBS likes to not follow its API documentation and tends to ignore the
specific attribute option and returns everything. This results in
returning the first element that lxml decide to match to the pattern.
Not sure if OBS broke this recently, or if #1573 was poorly tested.
Documentation: https://build.opensuse.org/apidocs/index#32
Actual result:
```
$ osc api /source/openSUSE:Factory/_attribute/OSRT:Config
```
```xml
<attributes>
<attribute name="VeryImportantProject" namespace="OBS"/>
<attribute name="InitializeDevelPackage" namespace="OBS"/>
<attribute name="ApprovedRequestSource" namespace="OBS"/>
<attribute name="IgnoredIssues" namespace="OSRT">
<value>last_seen:
boo#1062803: '20180506'
boo#1064836: '20180626'
boo#1068938: '20180506'
boo#1076835: '20180603'
boo#1079320: '20180516' …
```
=> osclib/stagingapi: attribute_value_load(): ensure using desired value.

obs_clone.py
:Rings:2-TestDVD was dropped from Factory and Leap.
Resolves CI failure:
```
$ python ./obs_clone.py --cache --debug --apiurl-target local
clone openSUSE:Factory from https://api.opensuse.org to http://0.0.0.0:3000
clone source/openSUSE:Factory:Rings:2-TestDVD/_meta
CACHE_MISS https://api.opensuse.org/source/openSUSE:Factory:Rings:2-TestDVD/_meta (expired)
GET https://api.opensuse.org/source/openSUSE:Factory:Rings:2-TestDVD/_meta
<status code="unknown_project">
<summary>openSUSE:Factory:Rings:2-TestDVD</summary>
</status>
```
=> obs_clone: start from :Rings:1-MinimalX instead of :Rings:2-TestDVD.

totest-manager.py
```
fvogt@packagelists:~/osc-plugin-factory> /usr/bin/python2 totest-manager.py --dry --verbose run --interval 5 openSUSE:Leap:15.0:Images
2018-06-28 15:17:50,311 - totest-manager:525 INFO current_snapshot 17.9: passed
2018-06-28 15:17:52,428 - totest-manager:483 INFO Updating snapshot 20.2
2018-06-28 15:17:52,431 - totest-manager:466 INFO release openSUSE:Leap:15.0:Images/livecd-leap-gnome (Snapshot20.2)
2018-06-28 15:17:52,432 - totest-manager:466 INFO release openSUSE:Leap:15.0:Images/livecd-leap-kde (Snapshot20.2)
2018-06-28 15:17:52,432 - totest-manager:466 INFO release openSUSE:Leap:15.0:Images/livecd-leap-x11 (Snapshot20.2)
2018-06-28 15:17:52,432 - totest-manager:466 INFO release openSUSE:Leap:15.0:Images/opensuse-leap-image:docker (Snapshot20.2)
2018-06-28 15:17:52,433 - …
```
=> Update definitions for openSUSE:Leap:15.0:Images

ReviewBot.py, check_maintenance_incidents.py, check_source.py, osclib/conf.py
- 4c129bec3ca000f8b989508119cdfc8e19b44ff4:
check_source: skip adding reviews for incidents in favor of maintbot.
- da36ae99310804273ecfcdc0ffe01bda6c6b8d2e:
check_source: replace one action limitation with configurable rule.
Allows tool to be used on multi-action requests while still enforcing
the rule for Factory and Leap which should reject such requests due to
staging process.
- 6092ff55c8b03128c0f30097103a0ace8eadc7a2:
check_source: override rename project setting for maintenance_incident.
- bfcc1ddf86ead4213e653366bb99d6f67d8939a5:
check_source: rework rename check to allow for suffixed :Update packages.
Exact name matching is thus always enforced for projects requiring devel
project enforcement (ie. Factory), but relaxed to compare without suffix
for packages coming from an :Update …
=> check_source: handle maintenance incident workflow.

dist/ci/Dockerfile
This reverts commit c3df9508696dbca3b8e0835704814442ac1871dc.
Fixed upstream in openSUSE/osc#429.
=> Revert "dist/ci/Dockerfile: add python2-pyOpenSSL as dependency."

osclib/stagingapi.py, pkglistgen.py, repo_checker.py
The break on openQA failures is a left over from 93ee829260a6abf094cbbc31e26eb21bf45e8f15
where we stopped the loop over subprojects. We don't want to break out of
the review loop on openQA failures
=> repo_checker: Fix the review loop

pkglistgen.py
The OUTPUT groups need to specify the status now or it will default to
unsupported (which should still be fine for leap/factory)
=> pkglistgen: remove default-support-status option

osclib/check_command.py, tests/fixtures/project/staging_projects/openSUSE:Factory.json
OBS is going to drop the superseded_by_id attribute soon as it is just
an alias for superseded_by.
=> Rename superseded_by_id to superseded_by

leaper.py
due to the leaper bot is crashed I've hot-patched this on packagelists.
=> leaper: fix error with no lookup_150 attribute exist after introduced PackageLookup

pkglistgen.py
Respect main_repo setup for other variant eg. ARM. Also removed ports from SCOPES. Passing `apiurl` to `update_and_solve_target_wrapper()` also wrong here.
=> pkglistgen: respect main_repo setup for other variant

check_source.py
Based on a report by mgerstner regarding IBS requests 170009 and 170008.
The logic passes for both requests in question, although one has other issues, and tested on a factory request. Also simulated update request to ensure regex logic matches properly.
=> check_source: allow for dot in package name during in-air rename check.

ReviewBot.py, leaper.py
- aad8e611ef15066b0552c4f804d22ea94e76dac0:
ReviewBot: check_one_request(): correct logic to return "lowest" result.
Without this change if two actions return True and None, True is returned
which is not desirable.
- f4460ebb146bdd8bccb44ea9eaf9ea8be5bc6548:
leaper: remove only_one_action limitation.
Leaper will now be used on maintenance incidents which commonly have
multiple actions. A similar change was done to check_source.py where the
restriction was moved to a review setting which is more appropriate rather
than a hard limitation. Going forward it makes sense to lift the limitation
and have only one bot enforce the rule where appropriate.
- 5e06287ac8a5e5fb5aec1bb6dd4be01808899fe5:
leaper: provide maintenance_incident support.
Initial stab at #1635, but some questions are …
=> leaper: provide maintenance_incident support.

repo_checker.py
@coolo decided to miss this the first time around then "fix" it (#1593) without running even once. Wrong number of arguments.
Actually fixes #1587.
Otherwise, you get this lovely error.
```
File "./repo_checker.py", line 648, in <module>
sys.exit(app.main())
File "/usr/lib/python2.7/site-packages/cmdln.py", line 261, in main
return self.cmd(args)
File "/usr/lib/python2.7/site-packages/cmdln.py", line 284, in cmd
retval = self.onecmd(argv)
File "/usr/lib/python2.7/site-packages/cmdln.py", line 422, in onecmd
return self._dispatch_cmd(handler, argv)
File "/usr/lib/python2.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
return handler(argv[0], opts, *args)
File "./repo_checker.py", line 640, in do_project_only
self.checker.project_only(project, …
```
=> repo_checker: whitelist_clean(): correct attribute_value_save().

repo_checker.pl, repo_checker.py
- a1cf089572535b7ea5e839d32c649c33b35d9f3d:
repo_checker: support multi-layer projects during project_only run.
Include problems from all the layers instead of just the top layer as this
is effectively what the end-user would see.
- 9e862efeb7488fb81f1c14bb60d402fe8feacf13:
repo_checker: properly support multi-layer projects during request mode.
Previously, the additional layers supported added by coolo treated them
like staging projects which meant that everything except the bottom
override the bottom. Obviously, for SLE service packs this is not correct.
This rewrorks the underlying perl script to support a stack of directories
where the second directory is assumed the be the target project for the
purposes of the toignore (-f) argument and the top layer is the only
one for which …
=> repo_checker: properly support multi-layer projects

devel-project.py, fcc_submitter.py, manager_42.py, metrics.py, osclib/core.py, osclib/request_splitter.py, osclib/stagingapi.py
- ffcee027c011a2870eeb2dfb7e18e809ffc04d1e:
osclib/core: maintainers_get(): rework to properly supports groups.
Previously, group members were only added if no maintainers were present
whereas group members should always be considered. Additionally, project
queries never included group members. Now groups are included in both.
- 038bec6113c6a1a0b9653ab3e4402beb3a7d663d:
osclib/core: provide groups_members() to expand muliple groups users.
- 600a48674544034ea84affc30318042a9f43dc4f:
Utilize ET.fromstringlist() intead of joining strings.
Fixes #1293.
Verified new logic using:
- `server:php:applications`: `['jbroedelGB', 'weberho', 'ralflangb1', 'poeml', 'computersalat', 'lrupp', 'arclyde', 'maxlin_factory', 'elvigia', 'dstoecker', 'asemen', 'lnussel_factory', 'dimstar_suse', …
=> osclib/core: maintainers_get(): rework to properly supports groups.

osc-staging.py, osclib/prio_command.py
- a90bf0e07b830b415b8da9c308f142e77040d15b:
osc-staging: add documentation for setprio command.
- 9c0eb82f512ebf875e890dbb82645cf8515bf3aa:
osclib/prio: support non-important priority.
Fixes #971.
=> osclib/prio: support non-important priority.

ReviewBot.py, devel-project.py, metrics.py, openqa-comments.py, osc-staging.py, osclib/conf.py, osclib/core.py, osclib/stagingapi.py, pkglistgen.py, suppkg_rebuild.py, tests/accept_tests.py, tests/api_tests.py, tests/check_tests.py, tests/config_tests.py, tests/freeze_tests.py, tests/obs.py, tests/obslock_tests.py, tests/select_tests.py, tests/unselect_tests.py, totest-manager.py, update_crawler.py
- 0696a0fe6c47f93b0535c3ba88744e0898c925cd:
osclib/stagingapi: utilize osclib.core.attribute_value_*() implementations.
Provides convenience aliases that require less arguments.
- dace1c3997345968a5e560119a887c169e9fb655:
tests/obs: improve format of default Config attribute.
- 760ddf39e69bf376266ed8d6669b8bfd03847b83:
**osclib/conf: decouple from StagingAPI and always fetch remote config.**
As the remote config is no longer optional for SLE and is utilized by
openSUSE to the point were it is dangerous not to load the remote config
it should be required. Currently only certain users call apply_remote()
while this will make it built-in during construction and thus makes the
usage consistent and no longer require StagingAPI.
- 68c315006996d4dfb9494c9f139f8c9d9162f64e:
osclib/conf: utilize …
=> osclib/conf: decouple from StagingAPI and always fetch remote config.

ReviewBot.py, check_source.py, leaper.py, osclib/conf.py, repo_checker.py, tests/config_tests.py
- 2180c4a2c68397a1a819e9b55b72423d99f63ad3:
ReviewBot: drop self.staging_config post switch to Config.get().
- 8cffc2e553534a8e93df0cbbcf33cc1a3c6afc25:
repo_checker: use osclib.conf.str2bool() instead of bool().
- 1012b62830673c97674586f83d9ab5b62f4f5dbb:
ReviewBots: utilize Config.get() instead of self.staging_config.
- 5b5d9170741ca265663f60d4c5f25ceade63abe6:
osclib/conf: provide cached get() method to supersede ReviewBot cache.
Given the slow migration of everything to the shared project config in
tools that change project contexts multiple times a consistent way of
accessing the config without forcing remote calls is needed.
- 343213fb4869bafa03f0f862ddfd3a7e0b03aabe:
check_source: drop staging_group() for target_project_config().
The staging_group() method pre-dates the …
=> osclib/conf: provide cached get() method to supersede ReviewBot cache.

osclib/conf.py, tests/config_tests.py
- 5b44ea188d11415b1dc6a4f1de7536ccb769a0cb:
osclib/conf: provide Leap:N:Update default settings.
- 77e27fae9eea59e945034efc58ab02f1d207f06a:
osclib/conf: exclude sub-projects from matching project patterns.
Otherwise, :Update projects match the primary product settings which
gives the wrong impression to tools as things like :Update:Staging do
not exist. Since :Update and other sub-projects are in a different phase
of development they should really have separate settings. :Ports however
does have stagings and in theory should act like parent product. If it
becomes desirable to split that can be done in the future.
Some policy settings related to ReviewBots likely are desirable to carry
over, but that can be resolved in follow-up as they are not currently used.
@lnussel We've discussed the …
=> osclib/conf: exclude sub-projects from matching project patterns (and Leap:N:Update defaults)

devel-project.py, fcc_submitter.py, metrics.py, obs_clone.py, osc-staging.py, osclib/accept_command.py, osclib/check_duplicate_binaries_command.py, osclib/conf.py, osclib/core.py, osclib/freeze_command.py, osclib/stagingapi.py, repo_checker.py, suppkg_rebuild.py, systemd/osrt-staging-bot-devel-list.service, systemd/osrt-staging-bot-devel-list.timer, totest-manager.py
- 1fe03c16f0b836db70d0bd4145161a1199952a60:
osc-staging: update "config" documentation to point to OSRT:Config.
- 6d60708b5979424faef55f0794aa9744168df798:
osclib/core: source_file_save(): always include host in message.
- 536e17cb790628fadaf3d2c30a4bbbe87b8100f0:
osclib/stagingapi: rename dashboard_content_* methods to pseudometa_file_*.
No need to be confusing and use the deprecated dashboard name.
- 24b15d6b0bf2a161a8c9dc9ca64738d54b02bb67:
Replace relevant 'dashboard' package references with pseudometa lookup.
Skipping some of the broader once which have no tangible impact, but are
expensive to change.
- 5e6df089a6ff8438d877f9e2ad7b0d7b504ea9ef:
osclib/stagingapi: drop {load,save}_file_content() methods.
Since the implementations have been made generic and dropped to osclib.core
there …
=> osclib/core: provide project_pseudometa_*() functions (and related)

ReviewBot.py, osclib/conf.py, osclib/core.py, osclib/cycle.py, osclib/stagingapi.py, osclib/util.py, pkglistgen.py, repo_checker.py
- af0d74a2df5f65403c9ff0b394d3088ae9b4b910:
StagingAPI: drop inferior expanded_repos() implementation for osclib.core.
- 36a5a6c2e4b8836f534b6d1020acd2e39927a251:
pkglistgen: utilize osclib.core.repository_path_expand().
- a57fe7ba4e7e1493ac6487e00e98423e21cba2a2:
repo_checker: complete rework to handle arbitrary repos and maintenance.
The rework includes a variety of changes:
- multiple actions per request supported
- automatically detecting "main" repo (useful for devel/home projects)
- full layered repository path state and published taken into account
- arbitrary repository name (ie. not just standard) supported
- intermediate results (used for staging) no longer accept (even if no
problems detected) until all layers are published
- no longer tied to staging process, but still …
=> repo_checker: complete rework to handle arbitrary repos and maintenance (and related)

osclib/core.py
Something I notice during #1656, but was unrelated.
=> osclib/core: repository_path_expand(): skip adding duplicate path.

repo_checker.py
The code is all there, but in the rework missed wiring it up.
Missed after #1656.
=> repo_checker: project_only: hook up --post-comments flag.

leaper.py
```
The default is already set in check_one_request() (called before) to
self.do_check_maintainer_review = not self.ibs
```
=> leaper: remove duplicate maintainer review check for IBS in default action.

ReviewBot.py, check_source.py, dist/package/openSUSE-release-tools.spec, leaper.py
- dab65356d755746c93269adba1d5cc7e19637b3e:
leaper: replace maintbot usage with ReviewBot methods.
The maintenance_incident logic is always updated to mimic the maintbot
behavior in regards to when to add devel project review.
- 31d6a872c7a3a09ccb24f93284e374ba989375fe:
check_source: replace maintbot usage with ReviewBot methods.
- a1c13348037a82d37356b97d7042808d852a263b:
ReviewBot: add devel_project_review_*() methods adapted from maintbot.
The owner logic surrounding a package removed from Factory does not appear
to make sense as the current behavior of OBS never returns another owner
pair for such packages. As such the existing devel project lookup makes
more sense and is more straight forward.
This code causes headaches and takes far longer to figure out how to change than to write …
=> ReviewBot: add devel_project_review_*() methods adapted from maintbot (and port users)

CreatePackageDescr.pm
Drop in #1644, but as suspected it is needed. The reason the side-effect
was not notice right away is the package description cache for a package
making use of the requirement must be rebuilt. This means the package
must be updated since the last time cache was built.
After completely a force rebuild of entire cache the behavior is correct
by only adding this back. Unlike the case below these binaries are not
published to the end-user so this is more a quirk of the data present in
OBS for staging projects.
=> repo_checker: CreatePackageDescr: exclude build-env requirement.

osclib/conf.py, repo_checker.py
Since the tool has been expanded to work on any repository, there are more
repositories that would want direct comments than devel. Set the value
to be devel for the openSUSE products which are the places where that is
desirable.
=> repo_checker: change package comment default to be direct instead of devel.

osclib/conf.py, repo_checker.py, tests/config_tests.py
- dbfafe8e854ede1f38e8a9cb9efe1e0943651105:
osclib/conf: utilize repo_checker-project-skip for OBS SLE projects.
- bf694199969ce572c004103f753d2b75d48a954a:
repo_checker: provide repo_checker-project-skip option.
Allows for skipping review of an action based on the target project config.
This is another fun problem created by multi-action requests with the bonus of being multi-target. repo-checker can pick them up due to targeting `openSUSE:Leap:15.0:Update` and end up reviewing them for other projects. Since this was never apossibility before there is no "project fencing" which may be something we need to consider for other reasons as well. Lets hope maintenance appreciates this. :)
For example without this change (scary 20 level repository stack too!?!?!?):
```
$ ./repo_checker.py …
```
=> repo_checker: provide repo_checker-project-skip option (and utilize for OBS SLE projects)

repo_checker.py
The more accurately reflects what the hash represents since it grew to
include the staging project meta revision and may end up including more.
=> repo_checker: change build to state in comment info.

repo_checker.py
- 108e0a2bf47f4b35e706a25265844554cf23f429:
repo_checker: include repository as bot name suffix in direct package comment.
This allows for multiple project_only runs with a different main-repo set.
It is very unlikely this feature will be used, but will handle it properly
to be consistent with pseudometa file name.
- da507a414730bda00fe90be6f782dbcc1fdd8446:
repo_checker: include repository as bot name suffix for staging comments.
This becomes necessary for multi-action requests like those seen in
maintenance where there may be multiple repositories reviewed for a single
request. The result is multiple comments made on the staging project which
would override each other. This treats them separately just as devel
project comments do with target project.
The review result is correct without …
=> repo_checker: include repository as bot name suffix for staging and direct package comments.

repo_checker.py
Works, but overrides the base state properly which is not desired.
This reverts commit 3db3a182855510c0b016e83888693e03e227e000.
=> Revert "repo_checker: change build to state in comment info."

leaper.py
In factory for multi-action requests, like maintenance, this ends up hiding useful lines that should be repeated for actions with the same origin.
Noticed in #1662.
=> leaper: comment_handler_lines_deduplicate() call as no longer applicable.

leaper.py
After moved to ReviewBot from maintbot, follow the old rule of adding maintainer review, skip maintainer review if submission is from SLE; SLE's SP; Leap and Leap:Update.
=> leaper: proper maintainer review rule

Makefile, dist/package/openSUSE-release-tools.spec, metrics/grafana/history.json, metrics/grafana/provisioning/datasources.yaml, metrics/telegraf/agent.conf, metrics/telegraf/history.conf, systemd/osrt-metrics-telegraf.service
After deployment of [poo#36766](https://progress.opensuse.org/issues/36766) the pretty storage consumption graph reading from AWS Cloudwatch will no longer be relevant (long-term). The re-creates essentially the same thing, plus snapshot count, but using download.o.o as a source.
=> metrics: provide initial telegraf setup for ingesting historical snapshots

tests/factory_source_tests.py
Drop submit xpath references in favor of action only. A prime example of the brittleness of this style of test.
Not fun to manually update those half-decoded strings...
Fixes #1681.
=> tests/factory_source_tests: update query after osc@f1c3156.

dist/package/openSUSE-release-tools.spec
Discovered missing while building container from scratch.
=> dist/spec: include as requirement of check-source sub package.

.travis.yml
Although we still have `42.3` deployments this seems reasonable.Only potential problem is introducing new dependencies that are not available on `42.3` will not cause travis failure.
=> travis: increment targetted versions to openSUSE Leap 15.0 and SLE 15.

metrics.py
- d7d3d555786c17f119adca1fa0912ff7c8f18f90:
metrics: check for action/target instead of submit/target since removed.
In the wake of openSUSE/osc@f1c3156 removing the deprecated submit/target,
the special condition to limit Factory to "staging era" requests should be
updated to look for action/target.
- 0b342a5856050e816a17f183b95c366bd9f3873e:
metrics: remove workaround for OBS xpath bug during request search.
Now that the bug related to openSUSE/open-build-service#5571 has been fixed
the inverted behavior of exclude_target_projects no longer works. As such
the argument should be removed and only way to get the desired behavior
is to override include_request_from_project which includes request sourced
from specific project. For the purposes of metrics only interested in
requests targeting …
=> metrics: remove workaround for OBS xpath bug during request search.

check_source.py
skip_add_reviews needs to be reset, otherwise a single
maintenance_incident request affects the rest of the work queue.
=> check_source: reset skip_add_reviews for each request

metrics/access/aggregate.php, metrics/access/ingest.php, metrics/grafana/access.json
- 5c410b7c76aa85b5a0eb6b0859717f1e0aefe9c4:
metrics/grafana/access: add new row and graphs for image totals by product.
Includes a new variable for switching which product is displayed.
Unfortunately, there is no way to hide the variable within a row and it
seems like over-kill to create a separate dashboard.
- 7492b109e5f370988a2e95b9c22eded81e6d734b:
metrics/access/aggregate: process and summarize image totals by product.
Accessible in new measurement prefixed by 'image'.
- c84add0bf7081ce839f3c95a5e4d66f26b5cf28a:
metrics/access/aggregate: extract merge_product_plus_key() from merge().
- dc9afe2adf16e1375001eca9bc73c2211f73e27c:
metrics/access/ingest: detect product image paths and included in dump.
- 6203b52a420c66bb8c6f3b6ee0d4a4bf36803d50:
metrics/grafana/access: remove left-over …
=> metrics: add image totals by product to access dashboard.

ReviewBot.py, check_maintenance_incidents.py, check_source.py, repo_checker.py
- 406fc41a851a594f3cbcfa11b7afe9d793de3203:
ReviewBots: utilize delete_package check where it was already assumed.
- 658137b9e973b3fab66b0060d98acf44d71d9105:
check_source: split out delete repository check to new sub action check.
- ecbc806b2d480ee1d92b64fb1b20b733a10e51e4:
check_source: decline all delete project requests.
- d1b630b5dab3132f6dfaaf6febd825e59a190f8c:
ReviewBot: break down sub-types of delete requests.
Their is very little overlap in the types of reviews one typically wants
to perform on delete requests. Already all of the existing code will crash
if a delete project request is reviewed.
Fixes #1696, by producing:
```
$ ./check_source.py --debug --dry id 635926
[I] checking 635926
[I] 635926 declined: Deleting the openSUSE:Factory project is not allowed.
[D] 635926 review …
```
=> check_source: decline all delete project requests and ReviewBot sub-delete check types.

pkglistgen.py
The release managers are actually supposed to maintain the filter list
in unneeded.yml, but that only applies to unsorted.yml not to the unsorted.group
(which is basically unfiltered to be published into OBS's SLE-15)
=> Don't take unsorted.group as reference for SP1 product changes

osclib/stagingapi.py, tests/select_tests.py
Submitters complain more and more about the spam they're getting from
staging projects - and we rather leave that weapon for actual feedback.
One especially annoying case is if a package is added to one staging project
and then later moved to another, the submitter will receive notifications
of all kind of bots and actions for both staging projects.
=> Do no longer CC submitters in request comments

check_maintenance_incidents.py
Action of patchinfo does not have a releaseproject attribute, with bad luck it might be lists as the first action of an maintenance incident, we should skip it and try next action.
We got this error on maintbot with https://build.opensuse.org/request/show/641770 , this incident have patchinfo as the first action, then maintbot crashes with
`
Oct 15 09:53:06 packagelists osrt-maintenance[15562]:     if not entry or project.startswith(entry.get('project')):
Oct 15 09:53:06 packagelists osrt-maintenance[15562]: AttributeError: 'NoneType' object has no attribute 'startswith'
`
Note: I already hot-patched this change on packagelists VM so maintbot can working again.
=> check_maintenance_incidents: skip action if the action is for patchinfo

dist/ci/obs-build-target
- ae01d143c91f48b67d5109e464bc28f92aca9cc3:
dist/ci/obs-build-target: utilize TAR_SCM_TESTMODE to avoid URL check.
See #1732 for details, but summarized the CI uses a local path which
differs from the normal remote URL which causes tar_scm service to
complain and no re-create the obscpio. See
openSUSE/obs-service-tar_scm@44b3bee for the relevant change.
- 26c6dba22d826407fabeef81c6e4a52d6d592a1b:
dist/ci/obs-build-target: stop at first error.
Fixes #1732.
=> CI: resolve build-time tar service failure

leaper.py
This was disabled manually in production to effectively run leaper in
"comment-only mode" for maintenance with the expectation that this would
not remain for long. Since it seems it will it makes sense to merge the
state expected to be deployed.
Fixes #1729.
=> leaper: disable maintainer review addition for incidents.

osclib/conf.py
- 35594e5f05d5fc061fb700c48cac29fe799457bd:
osclib/conf: include NonFree subproject in openSUSE patterns.
Intentionally left outside of <project> group so that the NonFree
subproject still uses the main Staging subproject.
- 8ec1e1777b57985c8862ec91a0f471055015ce72:
osclib/conf: remove Ports subprojects as they no longer exist.
Fixes #1735.
=> osclib/conf: include NonFree subproject in openSUSE patterns.

ReviewBot.py, osclib/cycle.py, repo_checker.py
- 616281e75fcdb42a0a2dc9dfe6beeac9680e10d0:
repo_checker: utilize 'staging' config option for instantiating StagingAPI.
- c74e40ba70d5b30519a389da9d7ef9f6dc27abc5:
osclib/cycle: remove need for StagingApi instance in favor of apiurl.
- 2a50b8cf72a79de1ebe10813cddd44c54e6871ac:
ReviewBot: staging_api(): allow for Staging subproject to be used.
Fixes #1384.
Fixes #1247.
=> repo_checker: utilize 'staging' config option for instantiating StagingAPI (and related)
